CIRCT: lib/Dialect/Calyx/CalyxOps.cpp File Reference
CalyxOps.cpp File Reference
#include "circt/Dialect/Calyx/CalyxOps.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/Calyx/CalyxInterfaces.cpp.inc"
#include "circt/Dialect/Calyx/Calyx.cpp.inc"
Classes
struct CommonTailPatternWithSeq
seq { if a with @G { if a with @G { seq { ...
struct CommonTailPatternWithPar
if a with @G { par { par { if a with @G { ...
struct EmptyIfBody
This pattern checks for one of two cases that will lead to IfOp deletion: (1) Then and Else bodies are both empty.
Macros
#define ImplUnaryOpCellInterface(OpType)
#define ImplBinOpCellInterface(OpType)
#define GET_OP_CLASSES
Functions
template<typename Op >
static LogicalResult verifyNotComplexSource (Op op)
Verify that the value is not a "complex" value.
static std::string valueName (Operation *scopeOp, Value v)
Convenience function for getting the SSA name of v under the scope of operation scopeOp.
static bool isPort (Value value)
Returns whether this value is either (1) a port on a ComponentOp or (2) a port on a cell interface.
static bool hasControlRegion (Operation *op)
Returns whether the given operation has a control region.
static LogicalResult verifyControlBody (Operation *op)
Verifies the body of a ControlLikeOp.
static ParseResult parseGroupPort (OpAsmParser &parser, OperationState &result)
template<typename GroupPortType >
static void printGroupPort (OpAsmPrinter &p, GroupPortType op)
template<typename OpTy >
static LogicalResult collapseControl (OpTy controlOp, PatternRewriter &rewriter)
template<typename OpTy >
static void eraseControlWithGroupAndConditional (OpTy op, PatternRewriter &rewriter)
A helper function to check whether the conditional and group (if it exists) needs to be erased to maintain a valid state of a Calyx program.
static LogicalResult verifyProgramOp (ProgramOp program)
template<typename Op >
static Op getControlOrWiresFrom (ComponentOp op)
This is a helper function that should only be used to get the WiresOp or ControlOp of a ComponentOp, which are guaranteed to exist and generally at the end of a component's body.
static Value getBlockArgumentWithName (StringRef name, ComponentOp op)
Returns the Block argument with the given name from a ComponentOp.
static FunctionType getComponentType (ComponentOp component)
Returns the type of the given component as a function type.
template<typename Pred >
static SmallVector< PortInfo > getFilteredPorts (ComponentOp op, Pred p)
A helper function to return a filtered subset of a component's ports.
static void printComponentOp (OpAsmPrinter &p, ComponentOp op)
static ParseResult parsePortDefList (OpAsmParser &parser, OperationState &result, SmallVectorImpl< OpAsmParser::OperandType > &ports, SmallVectorImpl< Type > &portTypes, SmallVectorImpl< NamedAttrList > &portAttrs)
Parses the ports of a Calyx component signature, and adds the corresponding port names to attrName.
static ParseResult parseComponentSignature (OpAsmParser &parser, OperationState &result, SmallVectorImpl< OpAsmParser::OperandType > &ports, SmallVectorImpl< Type > &portTypes)
Parses the signature of a Calyx component.
static ParseResult parseComponentOp (OpAsmParser &parser, OperationState &result)
static LogicalResult hasRequiredPorts (ComponentOp op)
Determines whether the given ComponentOp has all the required ports.
static LogicalResult verifyComponentOp (ComponentOp op)
template<typename T >
static SmallVector< T > concat (const SmallVectorImpl< T > &a, const SmallVectorImpl< T > &b)
Returns a new vector containing the concatenation of vectors a and b.
static LogicalResult verifyControlOp (ControlOp control)
static LogicalResult verifyParOp (ParOp parOp)
static LogicalResult verifyWiresOp (WiresOp wires)
static LogicalResult isCombinational (Value value, GroupInterface group)
Verifies the defining operation of a value is combinational.
static LogicalResult verifyCombGroupOp (CombGroupOp group)
Verifies a combinational group may contain only combinational primitives or perform combinational logic.
static bool portIsUsedInGroup (GroupInterface group, Value port, bool isDriven)
Determines whether the given port is used in the group.
static LogicalResult portDrivenByGroup (GroupInterface groupOp, Value port)
Checks whether port is driven from within groupOp.
static LogicalResult allPortsDrivenByGroup (GroupInterface group, ValueRange ports)
Checks whether all ports are driven within the group.
static LogicalResult anyPortsDrivenByGroup (GroupInterface group, ValueRange ports)
Checks whether any ports are driven within the group.
static LogicalResult anyPortsReadByGroup (GroupInterface group, ValueRange ports)
Checks whether any ports are read within the group.
static LogicalResult verifyPrimitivePortDriving (AssignOp assign, GroupInterface group)
Verifies that certain ports of primitives are either driven or read together.
static void getCellAsmResultNames (OpAsmSetValueNameFn setNameFn, Operation *op, ArrayRef< StringRef > portNames)
Gives each result of the cell a meaningful name in the form: <instance-name>.
static LogicalResult verifyPortDirection (AssignOp op, Value value, bool isDestination)
Determines whether the given direction is valid with the given inputs.
static LogicalResult verifyAssignOpValue (AssignOp op, bool isDestination)
Verifies the value of a given assignment operation.
static LogicalResult verifyAssignOp (AssignOp assign)
static ParseResult parseAssignOp (OpAsmParser &parser, OperationState &result)
static void printAssignOp (OpAsmPrinter &p, AssignOp op)
static LogicalResult verifyInstanceOpType (InstanceOp instance, ComponentOp referencedComponent)
Verifies the port information in comparison with the referenced component of an instance.
static LogicalResult verifyGroupGoOp (GroupGoOp goOp)
static void printGroupGoOp (OpAsmPrinter &p, GroupGoOp op)
static ParseResult parseGroupGoOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyGroupDoneOp (GroupDoneOp doneOp)
static void printGroupDoneOp (OpAsmPrinter &p, GroupDoneOp op)
static ParseResult parseGroupDoneOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyMemoryOp (MemoryOp memoryOp)
static LogicalResult verifyEnableOp (EnableOp enableOp)
static LogicalResult verifyIfOp (IfOp ifOp)
static Optional< EnableOp > getLastEnableOp (SeqOp parent)
Returns the last EnableOp within the child tree of 'parentSeqOp'.
static llvm::StringMap< EnableOp > getAllEnableOpsInImmediateBody (ParOp parent)
Returns a mapping of {enabled Group name, EnableOp} for all EnableOps within the immediate ParOp's body.
template<typename OpTy >
static bool hasCommonTailPatternPreConditions (IfOp op)
Checks preconditions for the common tail pattern.
static LogicalResult verifyWhileOp (WhileOp whileOp)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
ImplBinOpCellInterface
#define ImplBinOpCellInterface (OpType)
Value:
  SmallVector<StringRef> OpType::portNames() {                                 \
    return {"left", "right", "out"};                                           \
  }                                                                            \
  SmallVector<Direction> OpType::portDirections() {                            \
    return {Input, Input, Output};                                             \
  }                                                                            \
  void OpType::getAsmResultNames(OpAsmSetValueNameFn setNameFn) {              \
    getCellAsmResultNames(setNameFn, *this, this->portNames());                \
  }                                                                            \
  SmallVector<DictionaryAttr> OpType::portAttributes() {                       \
    return {DictionaryAttr(), DictionaryAttr(), DictionaryAttr()};             \
  }
Definition at line 1767 of file CalyxOps.cpp.
ImplUnaryOpCellInterface
#define ImplUnaryOpCellInterface (OpType)
Value:
  SmallVector<StringRef> OpType::portNames() { return {"in", "out"}; }         \
  SmallVector<Direction> OpType::portDirections() { return {Input, Output}; }  \
  SmallVector<DictionaryAttr> OpType::portAttributes() {                       \
    return {DictionaryAttr(), DictionaryAttr()};                               \
  }                                                                            \
  void OpType::getAsmResultNames(OpAsmSetValueNameFn setNameFn) {              \
    getCellAsmResultNames(setNameFn, *this, this->portNames());                \
  }
Definition at line 1757 of file CalyxOps.cpp.
Function Documentation
allPortsDrivenByGroup()
static LogicalResult allPortsDrivenByGroup (GroupInterface group, ValueRange ports) static
Checks whether all ports are driven within the group.
Definition at line 831 of file CalyxOps.cpp.
References portIsUsedInGroup().
anyPortsDrivenByGroup()
static LogicalResult anyPortsDrivenByGroup (GroupInterface group, ValueRange ports) static
Checks whether any ports are driven within the group.
Definition at line 847 of file CalyxOps.cpp.
References portIsUsedInGroup().
anyPortsReadByGroup()
static LogicalResult anyPortsReadByGroup (GroupInterface group, ValueRange ports) static
Checks whether any ports are read within the group.
Definition at line 863 of file CalyxOps.cpp.
References portIsUsedInGroup().
collapseControl()
template<typename OpTy > static LogicalResult collapseControl (OpTy controlOp, PatternRewriter & rewriter) static
Definition at line 234 of file CalyxOps.cpp.
concat()
template<typename T > static SmallVector<T> concat (const SmallVectorImpl< T > & a, const SmallVectorImpl< T > & b) static
Returns a new vector containing the concatenation of vectors a and b.
Definition at line 569 of file CalyxOps.cpp.
Referenced by getConcatOperands(), and isZeroExtension().
eraseControlWithGroupAndConditional()
template<typename OpTy > static void eraseControlWithGroupAndConditional (OpTy op, PatternRewriter & rewriter) static
A helper function to check whether the conditional and group (if it exists) needs to be erased to maintain a valid state of a Calyx program.
If these have no more uses, they will be erased.
Definition at line 255 of file CalyxOps.cpp.
Referenced by EmptyIfBody::matchAndRewrite().
getAllEnableOpsInImmediateBody()
static llvm::StringMap<EnableOp> getAllEnableOpsInImmediateBody (ParOp parent) static
Returns a mapping of {enabled Group name, EnableOp} for all EnableOps within the immediate ParOp's body.
Definition at line 1484 of file CalyxOps.cpp.
Referenced by CommonTailPatternWithPar::matchAndRewrite().
getBlockArgumentWithName()
static Value getBlockArgumentWithName (StringRef name, ComponentOp op) static
Returns the Block argument with the given name from a ComponentOp.
If the name doesn't exist, returns an empty Value.
Definition at line 309 of file CalyxOps.cpp.
getCellAsmResultNames()
static void getCellAsmResultNames (OpAsmSetValueNameFn setNameFn, Operation * op, ArrayRef< StringRef > portNames) static
Gives each result of the cell a meaningful name in the form: <instance-name>.
<port-name>
Definition at line 982 of file CalyxOps.cpp.
getComponentType()
static FunctionType getComponentType (ComponentOp component) static
Returns the type of the given component as a function type.
Definition at line 337 of file CalyxOps.cpp.
getControlOrWiresFrom()
template<typename Op > static Op getControlOrWiresFrom (ComponentOp op) static
This is a helper function that should only be used to get the WiresOp or ControlOp of a ComponentOp, which are guaranteed to exist and generally at the end of a component's body.
In the worst case, this will run in linear time with respect to the number of instances within the component.
Definition at line 299 of file CalyxOps.cpp.
getFilteredPorts()
template<typename Pred > static SmallVector<PortInfo> getFilteredPorts (ComponentOp op, Pred p) static
A helper function to return a filtered subset of a component's ports.
Definition at line 358 of file CalyxOps.cpp.
getLastEnableOp()
static Optional<EnableOp> getLastEnableOp (SeqOp parent) static
Returns the last EnableOp within the child tree of 'parentSeqOp'.
If no EnableOp was found (e.g. a "calyx.par" operation is present), returns None.
Definition at line 1472 of file CalyxOps.cpp.
References None.
Referenced by CommonTailPatternWithSeq::matchAndRewrite().
hasCommonTailPatternPreConditions()
template<typename OpTy > static bool hasCommonTailPatternPreConditions (IfOp op) static
Checks preconditions for the common tail pattern.
This canonicalization is stringent about not entering nested control operations, as this may cause unintentional changes in behavior. We only look for two cases: (1) both regions are ParOps, and (2) both regions are SeqOps. The case when these are different, e.g. ParOp and SeqOp, will only produce less optimal code, or even worse, change the behavior.
Definition at line 1501 of file CalyxOps.cpp.
hasControlRegion()
static bool hasControlRegion (Operation * op) static
Returns whether the given operation has a control region.
Definition at line 110 of file CalyxOps.cpp.
Referenced by verifyControlBody(), and circt::calyx::verifyControlLikeOp().
hasRequiredPorts()
static LogicalResult hasRequiredPorts (ComponentOp op) static
Determines whether the given ComponentOp has all the required ports.
Definition at line 511 of file CalyxOps.cpp.
References intersection().
Referenced by verifyComponentOp().
isCombinational()
static LogicalResult isCombinational (Value value, GroupInterface group) static
Verifies the defining operation of a value is combinational.
Definition at line 710 of file CalyxOps.cpp.
References valueName().
Referenced by circt::ExportVerilog::isVerilogExpression(), and verifyCombGroupOp().
isPort()
static bool isPort (Value value) static
Returns whether this value is either (1) a port on a ComponentOp or (2) a port on a cell interface.
Definition at line 95 of file CalyxOps.cpp.
Referenced by verifyAssignOpValue().
parseAssignOp()
static ParseResult parseAssignOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1056 of file CalyxOps.cpp.
parseComponentOp()
static ParseResult parseComponentOp (OpAsmParser & parser, OperationState & result) static
Definition at line 477 of file CalyxOps.cpp.
References circt::calyx::direction::get(), and parseComponentSignature().
parseComponentSignature()
static ParseResult parseComponentSignature (OpAsmParser & parser, OperationState & result, SmallVectorImpl< OpAsmParser::OperandType > & ports, SmallVectorImpl< Type > & portTypes) static
Parses the signature of a Calyx component.
Definition at line 432 of file CalyxOps.cpp.
References circt::calyx::direction::get(), circt::calyx::direction::packAttribute(), and parsePortDefList().
Referenced by parseComponentOp().
parseGroupDoneOp()
static ParseResult parseGroupDoneOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1280 of file CalyxOps.cpp.
References parseGroupPort().
parseGroupGoOp()
static ParseResult parseGroupGoOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1246 of file CalyxOps.cpp.
References parseGroupPort().
parseGroupPort()
static ParseResult parseGroupPort (OpAsmParser & parser, OperationState & result) static
Definition at line 190 of file CalyxOps.cpp.
Referenced by parseGroupDoneOp(), and parseGroupGoOp().
parsePortDefList()
static ParseResult parsePortDefList (OpAsmParser & parser, OperationState & result, SmallVectorImpl< OpAsmParser::OperandType > & ports, SmallVectorImpl< Type > & portTypes, SmallVectorImpl< NamedAttrList > & portAttrs) static
Parses the ports of a Calyx component signature, and adds the corresponding port names to attrName.
Definition at line 405 of file CalyxOps.cpp.
Referenced by parseComponentSignature().
portDrivenByGroup()
static LogicalResult portDrivenByGroup (GroupInterface groupOp, Value port) static
Checks whether port is driven from within groupOp.
Definition at line 808 of file CalyxOps.cpp.
References circt::calyx::Output, and portIsUsedInGroup().
portIsUsedInGroup()
static bool portIsUsedInGroup (GroupInterface group, Value port, bool isDriven) static
Determines whether the given port is used in the group.
Its use depends on the isDriven value; if true, then the port should be a destination in an AssignOp. Otherwise, it should be the source, i.e. a read.
Definition at line 786 of file CalyxOps.cpp.
Referenced by allPortsDrivenByGroup(), anyPortsDrivenByGroup(), anyPortsReadByGroup(), and portDrivenByGroup().
printAssignOp()
static void printAssignOp (OpAsmPrinter & p, AssignOp op) static
Definition at line 1099 of file CalyxOps.cpp.
printComponentOp()
static void printComponentOp (OpAsmPrinter & p, ComponentOp op) static
Definition at line 374 of file CalyxOps.cpp.
References circt::calyx::PortInfo::attributes, if(), circt::calyx::PortInfo::name, and circt::calyx::PortInfo::type.
printGroupDoneOp()
static void printGroupDoneOp (OpAsmPrinter & p, GroupDoneOp op) static
Definition at line 1276 of file CalyxOps.cpp.
References printGroupPort().
printGroupGoOp()
static void printGroupGoOp (OpAsmPrinter & p, GroupGoOp op) static
Definition at line 1242 of file CalyxOps.cpp.
References printGroupPort().
printGroupPort()
template<typename GroupPortType > static void printGroupPort (OpAsmPrinter & p, GroupPortType op) static
Definition at line 218 of file CalyxOps.cpp.
Referenced by printGroupDoneOp(), and printGroupGoOp().
valueName()
static std::string valueName (Operation * scopeOp, Value v) static
Convenience function for getting the SSA name of v under the scope of operation scopeOp.
Definition at line 85 of file CalyxOps.cpp.
Referenced by isCombinational(), verifyIfOp(), and verifyWhileOp().
verifyAssignOp()
static LogicalResult verifyAssignOp (AssignOp assign) static
Definition at line 1046 of file CalyxOps.cpp.
References verifyAssignOpValue().
verifyAssignOpValue()
static LogicalResult verifyAssignOpValue (AssignOp op, bool isDestination) static
Verifies the value of a given assignment operation.
The boolean isDestination is used to distinguish whether the destination or source of the AssignOp is to be verified.
Definition at line 1030 of file CalyxOps.cpp.
References isPort(), verifyNotComplexSource(), and verifyPortDirection().
Referenced by verifyAssignOp().
verifyCombGroupOp()
static LogicalResult verifyCombGroupOp (CombGroupOp group) static
Verifies a combinational group may contain only combinational primitives or perform combinational logic.
Definition at line 751 of file CalyxOps.cpp.
References isCombinational().
verifyComponentOp()
static LogicalResult verifyComponentOp (ComponentOp op) static
Definition at line 540 of file CalyxOps.cpp.
References hasRequiredPorts().
verifyControlBody()
static LogicalResult verifyControlBody (Operation * op) static
Verifies the body of a ControlLikeOp.
Definition at line 115 of file CalyxOps.cpp.
References hasControlRegion().
Referenced by circt::calyx::verifyControlLikeOp(), and verifyControlOp().
verifyControlOp()
static LogicalResult verifyControlOp (ControlOp control) static
Definition at line 632 of file CalyxOps.cpp.
References verifyControlBody().
verifyEnableOp()
static LogicalResult verifyEnableOp (EnableOp enableOp) static
Definition at line 1417 of file CalyxOps.cpp.
verifyGroupDoneOp()
static LogicalResult verifyGroupDoneOp (GroupDoneOp doneOp) static
Definition at line 1258 of file CalyxOps.cpp.
References verifyNotComplexSource().
verifyGroupGoOp()
static LogicalResult verifyGroupGoOp (GroupGoOp goOp) static
Definition at line 1230 of file CalyxOps.cpp.
References verifyNotComplexSource().
verifyIfOp()
static LogicalResult verifyIfOp (IfOp ifOp) static
Definition at line 1438 of file CalyxOps.cpp.
References valueName().
verifyInstanceOpType()
static LogicalResult verifyInstanceOpType (InstanceOp instance, ComponentOp referencedComponent) static
Verifies the port information in comparison with the referenced component of an instance.
This helper function avoids conducting a lookup for the referenced component twice.
Definition at line 1129 of file CalyxOps.cpp.
References circt::calyx::direction::get().
verifyMemoryOp()
static LogicalResult verifyMemoryOp (MemoryOp memoryOp) static
Definition at line 1388 of file CalyxOps.cpp.
References size().
verifyNotComplexSource()
template<typename Op > static LogicalResult verifyNotComplexSource (Op op) static
Verify that the value is not a "complex" value.
For example, the source of an AssignOp should be a constant or port, e.g. and = comb.and a, b : i1 calyx.assign port = and, c1_i1 ? : i1 // Incorrect calyx.assign port = c1_i1, and ? : i1 // Correct TODO(Calyx): This is useful to verify current MLIR can be lowered to the native compiler. Remove this when Calyx supports wire declarations. See: https://github.com/llvm/circt/pull/1774 for context.
Definition at line 68 of file CalyxOps.cpp.
Referenced by verifyAssignOpValue(), verifyGroupDoneOp(), and verifyGroupGoOp().
verifyParOp()
static LogicalResult verifyParOp (ParOp parOp) static
Definition at line 656 of file CalyxOps.cpp.
verifyPortDirection()
static LogicalResult verifyPortDirection (AssignOp op, Value value, bool isDestination) static
Determines whether the given direction is valid with the given inputs.
The isDestination boolean is used to distinguish whether the value is a source or a destination.
Definition at line 1000 of file CalyxOps.cpp.
References circt::calyx::PortInfo::direction, circt::calyx::getPortInfo(), circt::calyx::Input, and circt::calyx::Output.
Referenced by verifyAssignOpValue().
verifyPrimitivePortDriving()
static LogicalResult verifyPrimitivePortDriving (AssignOp assign, GroupInterface group) static
Verifies that certain ports of primitives are either driven or read together.
Definition at line 880 of file CalyxOps.cpp.
Referenced by circt::calyx::verifyGroupInterface().
verifyProgramOp()
static LogicalResult verifyProgramOp (ProgramOp program) static
Definition at line 282 of file CalyxOps.cpp.
verifyWhileOp()
static LogicalResult verifyWhileOp (WhileOp whileOp) static
No combinational group was provided
Definition at line 1643 of file CalyxOps.cpp.
References valueName().
verifyWiresOp()
static LogicalResult verifyWiresOp (WiresOp wires) static
Definition at line 688 of file CalyxOps.cpp.