CIRCT: circt::hw::SymbolCache Class Reference
circt::hw::SymbolCache Class Reference
This stores lookup tables to make manipulating and working with the IR more efficient.
#include <HWOps.h>
Classes
class Item
Public Member Functions
void addDefinition (StringAttr symbol, Operation *op)
In the building phase, add symbols.
void addDefinition (StringAttr symbol, StringRef name, Operation *op, size_t port=~0ULL)
void freeze ()
Mark the cache as frozen, which allows it to be shared across threads.
Operation * getDefinition (StringRef symbol) const
Operation * getDefinition (StringAttr symbol) const
Operation * getDefinition (FlatSymbolRefAttr symbol) const
Item getDefinition (StringRef symbol, StringRef name) const
Item getDefinition (StringAttr symbol, StringAttr name) const
Private Member Functions
SmallVector< char > mkInnerKey (StringRef mod, StringRef name) const
Private Attributes
bool isFrozen = false
llvm::StringMap< Item > symbolCache
This stores a lookup table from symbol attribute to the operation (hw.module, hw.instance, etc) that defines it.
Detailed Description
This stores lookup tables to make manipulating and working with the IR more efficient.
There are two phases to this object: the "building" phase in which it is "write only" and then the "using" phase which is read-only (and thus can be used by multiple threads). The "freeze" method transitions between the two states.
Definition at line 170 of file HWOps.h.
Member Function Documentation
addDefinition() [1/2]
void circt::hw::SymbolCache::addDefinition (StringAttr symbol, Operation * op) inline
In the building phase, add symbols.
Definition at line 186 of file HWOps.h.
References isFrozen, and symbolCache.
addDefinition() [2/2]
void circt::hw::SymbolCache::addDefinition (StringAttr symbol, StringRef name, Operation * op, size_t port = ~0ULL) inline
Definition at line 192 of file HWOps.h.
References isFrozen, mkInnerKey(), and symbolCache.
freeze()
void circt::hw::SymbolCache::freeze () inline
Mark the cache as frozen, which allows it to be shared across threads.
Definition at line 200 of file HWOps.h.
References isFrozen.
getDefinition() [1/5]
Operation* circt::hw::SymbolCache::getDefinition (FlatSymbolRefAttr symbol) const inline
Definition at line 215 of file HWOps.h.
References getDefinition().
getDefinition() [2/5]
Operation* circt::hw::SymbolCache::getDefinition (StringAttr symbol) const inline
Definition at line 211 of file HWOps.h.
References getDefinition().
getDefinition() [3/5]
Item circt::hw::SymbolCache::getDefinition (StringAttr symbol, StringAttr name) const inline
Definition at line 226 of file HWOps.h.
References getDefinition().
getDefinition() [4/5]
Operation* circt::hw::SymbolCache::getDefinition (StringRef symbol) const inline
Definition at line 202 of file HWOps.h.
References isFrozen, and symbolCache.
Referenced by getDefinition().
getDefinition() [5/5]
Item circt::hw::SymbolCache::getDefinition (StringRef symbol, StringRef name) const inline
Definition at line 219 of file HWOps.h.
References isFrozen, mkInnerKey(), and symbolCache.
mkInnerKey()
SmallVector<char> circt::hw::SymbolCache::mkInnerKey (StringRef mod, StringRef name) const inline private
Definition at line 243 of file HWOps.h.
Referenced by addDefinition(), and getDefinition().
Member Data Documentation
isFrozen
bool circt::hw::SymbolCache::isFrozen = false private
Definition at line 231 of file HWOps.h.
Referenced by addDefinition(), freeze(), and getDefinition().
symbolCache
llvm::StringMap<Item> circt::hw::SymbolCache::symbolCache private
This stores a lookup table from symbol attribute to the operation (hw.module, hw.instance, etc) that defines it.
TODO: It is super annoying that symbols are defined as StringAttr, but are then referenced as FlatSymbolRefAttr. Why can't we have nice pointer uniqued things?? :-(
Definition at line 238 of file HWOps.h.
Referenced by addDefinition(), and getDefinition().
The documentation for this class was generated from the following file:
include/circt/Dialect/HW/HWOps.h