CIRCT: PlacementDB Class Reference
PlacementDB Class Reference
Public Member Functions
PlacementDB (MlirOperation top, PrimitiveDB *seed)
~PlacementDB ()
size_t addDesignPlacements ()
Walk the entire design adding placements.
bool addPlacement (MlirAttribute loc, MlirAttribute path, std::string subpath, MlirOperation op)
py::object getInstanceAt (MlirAttribute loc)
py::object getNearestFreeInColumn (CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
void walkPlacements (py::function pycb, std::tuple< py::object, py::object, py::object, py::object > bounds, py::object prim)
Private Attributes
CirctMSFTPlacementDB db
Detailed Description
Definition at line 43 of file MSFTModule.cpp.
Constructor & Destructor Documentation
PlacementDB()
PlacementDB::PlacementDB (MlirOperation top, PrimitiveDB * seed) inline
Definition at line 45 of file MSFTModule.cpp.
References circtMSFTCreatePlacementDB().
~PlacementDB()
PlacementDB::~PlacementDB () inline
Definition at line 49 of file MSFTModule.cpp.
References circtMSFTDeletePlacementDB().
Member Function Documentation
addDesignPlacements()
size_t PlacementDB::addDesignPlacements () inline
Walk the entire design adding placements.
Definition at line 50 of file MSFTModule.cpp.
References circtMSFTPlacementDBAddDesignPlacements().
addPlacement()
bool PlacementDB::addPlacement (MlirAttribute loc, MlirAttribute path, std::string subpath, MlirOperation op) inline
Definition at line 53 of file MSFTModule.cpp.
References circtMSFTPlacementDBAddPlacement().
getInstanceAt()
py::object PlacementDB::getInstanceAt (MlirAttribute loc) inline
Definition at line 59 of file MSFTModule.cpp.
References circtMSFTPlacementDBTryGetInstanceAt(), CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
getNearestFreeInColumn()
py::object PlacementDB::getNearestFreeInColumn (CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY) inline
Definition at line 66 of file MSFTModule.cpp.
References circtMSFTPlacementDBGetNearestFreeInColumn().
walkPlacements()
void PlacementDB::walkPlacements (py::function pycb, std::tuple< py::object, py::object, py::object, py::object > bounds, py::object prim) inline
Definition at line 74 of file MSFTModule.cpp.
References circtMSFTPlacementDBWalkPlacements(), CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
Member Data Documentation
db
CirctMSFTPlacementDB PlacementDB::db private
Definition at line 106 of file MSFTModule.cpp.
The documentation for this class was generated from the following files:
lib/Bindings/Python/MSFTModule.cpp
lib/Dialect/MSFT/DeviceDB.cpp