CIRCT: circt::msft::PlacementDB Class Reference
circt::msft::PlacementDB Class Reference
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
#include <DeviceDB.h>
Classes
struct PlacedInstance
In addition to an Operation which is the instance at the level being modeled in MLIR, the instance path within the MLIR instance is often necessary as most often the instance is an extern module.
Public Member Functions
PlacementDB (Operation *top)
Create a DB treating 'top' as the root module.
PlacementDB (Operation *top, const PrimitiveDB &seed)
LogicalResult addPlacement (PhysLocationAttr, PlacedInstance)
Assign an instance to a primitive.
LogicalResult addPlacement (PhysicalRegionRefAttr, PlacedInstance)
Assign an operation to a physical region. Return false on failure.
size_t addPlacements (FlatSymbolRefAttr rootMod, mlir::Operation *)
Using the operation attributes, add the proper placements to the database.
size_t addDesignPlacements ()
Walk the entire design adding placements root at the top module.
Optional< PlacedInstance > getInstanceAt (PhysLocationAttr)
Lookup the instance at a particular location.
PhysLocationAttr getNearestFreeInColumn (PrimitiveType prim, uint64_t column, uint64_t nearestToY)
Find the nearest unoccupied primitive location to 'nearestToY' in 'column'.
void walkPlacements (function_ref< void(PhysLocationAttr, PlacedInstance)>, std::tuple< int64_t, int64_t, int64_t, int64_t > bounds=std::make_tuple(-1, -1, -1, -1), Optional< PrimitiveType > primType={})
Walk the placement information in some sort of reasonable order.
void walkRegionPlacements (function_ref< void(PhysicalRegionRefAttr, PlacedInstance)>)
Walk the region placement information.
Private Types
using DimDevType = DenseMap< PrimitiveType, PlacedInstance >
using DimNumMap = DenseMap< size_t, DimDevType >
using DimYMap = DenseMap< size_t, DimNumMap >
using DimXMap = DenseMap< size_t, DimYMap >
using InstanceAndRegion = std::pair< PhysicalRegionRefAttr, PlacedInstance >
using RegionPlacements = SmallVector< InstanceAndRegion >
Private Member Functions
Optional< PlacedInstance * > getLeaf (PhysLocationAttr)
Get the leaf node.
Private Attributes
MLIRContext * ctxt
Operation * top
DimXMap placements
RegionPlacements regionPlacements
bool seeded
Detailed Description
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
Holds pointers into the IR, which may become invalid as a result of IR transforms. As a result, this class should only be used for analysis and then thrown away. It is permissible to persist it through transformations so long as it is maintained along with the transformations.
Definition at line 63 of file DeviceDB.h.
Member Typedef Documentation
DimDevType
using circt::msft::PlacementDB::DimDevType = DenseMap<PrimitiveType, PlacedInstance> private
Definition at line 115 of file DeviceDB.h.
DimNumMap
using circt::msft::PlacementDB::DimNumMap = DenseMap<size_t, DimDevType> private
Definition at line 116 of file DeviceDB.h.
DimXMap
using circt::msft::PlacementDB::DimXMap = DenseMap<size_t, DimYMap> private
Definition at line 118 of file DeviceDB.h.
DimYMap
using circt::msft::PlacementDB::DimYMap = DenseMap<size_t, DimNumMap> private
Definition at line 117 of file DeviceDB.h.
InstanceAndRegion
using circt::msft::PlacementDB::InstanceAndRegion = std::pair<PhysicalRegionRefAttr, PlacedInstance> private
Definition at line 119 of file DeviceDB.h.
RegionPlacements
using circt::msft::PlacementDB::RegionPlacements = SmallVector<InstanceAndRegion> private
Definition at line 120 of file DeviceDB.h.
Constructor & Destructor Documentation
PlacementDB() [1/2]
PlacementDB::PlacementDB (Operation * top)
Create a DB treating 'top' as the root module.
Definition at line 70 of file DeviceDB.cpp.
PlacementDB() [2/2]
PlacementDB::PlacementDB (Operation * top, const PrimitiveDB & seed)
Definition at line 72 of file DeviceDB.cpp.
References addPlacement(), circt::msft::PrimitiveDB::foreach(), and seeded.
Member Function Documentation
addDesignPlacements()
size_t circt::msft::PlacementDB::addDesignPlacements ()
Walk the entire design adding placements root at the top module.
addPlacement() [1/2]
LogicalResult circt::msft::PlacementDB::addPlacement (PhysicalRegionRefAttr , PlacedInstance)
Assign an operation to a physical region. Return false on failure.
addPlacement() [2/2]
LogicalResult circt::msft::PlacementDB::addPlacement (PhysLocationAttr , PlacedInstance)
Assign an instance to a primitive.
Return false if another instance is already placed at that location.
Referenced by PlacementDB().
addPlacements()
size_t PlacementDB::addPlacements (FlatSymbolRefAttr rootMod, mlir::Operation * op)
Using the operation attributes, add the proper placements to the database.
Return the number of placements which weren't added due to conflicts.
Definition at line 112 of file DeviceDB.cpp.
References if().
getInstanceAt()
Optional<PlacedInstance> circt::msft::PlacementDB::getInstanceAt (PhysLocationAttr)
Lookup the instance at a particular location.
getLeaf()
Optional< PlacementDB::PlacedInstance * > PlacementDB::getLeaf (PhysLocationAttr loc) private
Get the leaf node.
Abstract this out to make it easier to change the underlying data structure.
Definition at line 207 of file DeviceDB.cpp.
getNearestFreeInColumn()
PhysLocationAttr circt::msft::PlacementDB::getNearestFreeInColumn (PrimitiveType prim, uint64_t column, uint64_t nearestToY)
Find the nearest unoccupied primitive location to 'nearestToY' in 'column'.
walkPlacements()
void circt::msft::PlacementDB::walkPlacements (function_ref< void(PhysLocationAttr, PlacedInstance)> , std::tuple< int64_t, int64_t, int64_t, int64_t > bounds = std::make_tuple(-1, -1, -1, -1), Optional< PrimitiveType > primType = {})
Walk the placement information in some sort of reasonable order.
Bounds restricts the walk to a rectangle of [xmin, xmax, ymin, ymax] (inclusive), with -1 meaning unbounded.
Referenced by circtMSFTPlacementDBWalkPlacements().
walkRegionPlacements()
void PlacementDB::walkRegionPlacements (function_ref< void(PhysicalRegionRefAttr, PlacedInstance)> callback)
Walk the region placement information.
Definition at line 278 of file DeviceDB.cpp.
Member Data Documentation
ctxt
MLIRContext* circt::msft::PlacementDB::ctxt private
Definition at line 112 of file DeviceDB.h.
Referenced by circt.esi.System::run_passes().
placements
DimXMap circt::msft::PlacementDB::placements private
Definition at line 126 of file DeviceDB.h.
regionPlacements
RegionPlacements circt::msft::PlacementDB::regionPlacements private
Definition at line 127 of file DeviceDB.h.
seeded
bool circt::msft::PlacementDB::seeded private
Definition at line 128 of file DeviceDB.h.
Referenced by PlacementDB().
top
Operation* circt::msft::PlacementDB::top private
Definition at line 113 of file DeviceDB.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/MSFT/DeviceDB.h
lib/Dialect/MSFT/DeviceDB.cpp