CIRCT: circt::BuildOpGroups Class Reference
circt::BuildOpGroups Class Reference
Iterate through the operations of a source function and instantiate components or primitives based on the type of the operations.
Private Member Functions
LogicalResult PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override
Partial lowering implementation.
LogicalResult buildOp (PatternRewriter &rewriter, scf::YieldOp yieldOp) const
Op builder specializations.
LogicalResult buildOp (PatternRewriter &rewriter, BranchOpInterface brOp) const
LogicalResult buildOp (PatternRewriter &rewriter, arith::ConstantOp constOp) const
LogicalResult buildOp (PatternRewriter &rewriter, AddIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, SubIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, MulIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, ShRUIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, ShRSIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, ShLIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, AndIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, OrIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, XOrIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, CmpIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, TruncIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, ExtUIOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, ReturnOp op) const
For each return statement, we create a new group for assigning to the previously created return value registers.
LogicalResult buildOp (PatternRewriter &rewriter, IndexCastOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, memref::AllocOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, memref::AllocaOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, memref::LoadOp op) const
LogicalResult buildOp (PatternRewriter &rewriter, memref::StoreOp op) const
template<typename TGroupOp , typename TCalyxLibOp , typename TSrcOp >
LogicalResult buildLibraryOp (PatternRewriter &rewriter, TSrcOp op, TypeRange srcTypes, TypeRange dstTypes) const
buildLibraryOp will build a TCalyxLibOp inside a TGroupOp based on the source operation TSrcOp.
template<typename TGroupOp , typename TCalyxLibOp , typename TSrcOp >
LogicalResult buildLibraryOp (PatternRewriter &rewriter, TSrcOp op) const
buildLibraryOp which provides in- and output types based on the operands and results of the op argument.
template<typename TGroupOp >
TGroupOp createGroupForOp (PatternRewriter &rewriter, Operation *op) const
Creates a group named by the basic block which the input op resides in.
void assignAddressPorts (PatternRewriter &rewriter, Location loc, calyx::GroupInterface group, CalyxMemoryInterface memoryInterface, Operation::operand_range addressValues) const
Creates assignments within the provided group to the address ports of the memoryOp based on the provided addressValues.
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
Additional Inherited Members
Public Member Functions inherited from circt::FuncOpPartialLoweringPattern
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
LogicalResult partiallyLower (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override final
calyx::ComponentOp * getComponent () const
ComponentLoweringState & getComponentState () const
ProgramLoweringState & progState () const
Public Member Functions inherited from circt::PartialLoweringPattern< mlir::FuncOp >
PartialLoweringPattern (MLIRContext *ctx, LogicalResult &resRef)
LogicalResult matchAndRewrite (mlir::FuncOp op, PatternRewriter &rewriter) const override
Protected Attributes inherited from circt::FuncOpPartialLoweringPattern
FuncMapping & funcMap
Detailed Description
Iterate through the operations of a source function and instantiate components or primitives based on the type of the operations.
Definition at line 656 of file SCFToCalyx.cpp.
Member Function Documentation
assignAddressPorts()
void circt::BuildOpGroups::assignAddressPorts (PatternRewriter & rewriter, Location loc, calyx::GroupInterface group, CalyxMemoryInterface memoryInterface, Operation::operand_range addressValues) const inline private
Creates assignments within the provided group to the address ports of the memoryOp based on the provided addressValues.
Definition at line 784 of file SCFToCalyx.cpp.
buildLibraryOp() [1/2]
template<typename TGroupOp , typename TCalyxLibOp , typename TSrcOp > LogicalResult circt::BuildOpGroups::buildLibraryOp (PatternRewriter & rewriter, TSrcOp op) const inline private
buildLibraryOp which provides in- and output types based on the operands and results of the op argument.
Definition at line 767 of file SCFToCalyx.cpp.
buildLibraryOp() [2/2]
template<typename TGroupOp , typename TCalyxLibOp , typename TSrcOp > LogicalResult circt::BuildOpGroups::buildLibraryOp (PatternRewriter & rewriter, TSrcOp op, TypeRange srcTypes, TypeRange dstTypes) const inline private
buildLibraryOp will build a TCalyxLibOp inside a TGroupOp based on the source operation TSrcOp.
Create assignments to the inputs of the library op.
Replace the result values of the source operator with the new operator.
Definition at line 725 of file SCFToCalyx.cpp.
References circt::calyx::Input, and circt::esi::types.
buildOp() [1/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, AddIOp op) const private
Definition at line 1018 of file SCFToCalyx.cpp.
buildOp() [2/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, AndIOp op) const private
Definition at line 1038 of file SCFToCalyx.cpp.
buildOp() [3/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, arith::ConstantOp constOp) const private
Move constant operations to the compOp body as hw::ConstantOp's.
Definition at line 1007 of file SCFToCalyx.cpp.
References circt::matchConstantOp().
buildOp() [4/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, BranchOpInterface brOp) const private
Branch argument passing group creation Branch operands are passed through registers. In BuildBBRegs we created registers for all branch arguments of each block. We now create groups for assigning values to these registers.
Register the group as a block argument group, to be executed when entering the successor block from this block (srcBlock).
Definition at line 954 of file SCFToCalyx.cpp.
References circt::buildAssignmentsForRegisterWrite(), and seq::reg().
buildOp() [5/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, CmpIOp op) const private
Definition at line 1051 of file SCFToCalyx.cpp.
buildOp() [6/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, ExtUIOp op) const private
Definition at line 1082 of file SCFToCalyx.cpp.
buildOp() [7/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, IndexCastOp op) const private
Drop the index cast and replace uses of the target value with the source value.
pad/slice the source operand.
Definition at line 1088 of file SCFToCalyx.cpp.
References circt::convIndexType().
buildOp() [8/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, memref::AllocaOp op) const private
Definition at line 934 of file SCFToCalyx.cpp.
References circt::buildAllocOp().
buildOp() [9/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, memref::AllocOp op) const private
Definition at line 929 of file SCFToCalyx.cpp.
References circt::buildAllocOp().
buildOp() [10/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, memref::LoadOp op) const private
Definition at line 800 of file SCFToCalyx.cpp.
References circt::buildAssignmentsForRegisterWrite(), circt::createReg(), circt::noStoresToMemory(), seq::reg(), and circt::singleLoadFromMemory().
buildOp() [11/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, memref::StoreOp op) const private
Definition at line 849 of file SCFToCalyx.cpp.
buildOp() [12/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, MulIOp op) const private
Definition at line 870 of file SCFToCalyx.cpp.
References circt::createReg(), and seq::reg().
buildOp() [13/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, OrIOp op) const private
Definition at line 1042 of file SCFToCalyx.cpp.
buildOp() [14/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, ReturnOp op) const private
For each return statement, we create a new group for assigning to the previously created return value registers.
Schedule group for execution for when executing the return op block.
Definition at line 988 of file SCFToCalyx.cpp.
References circt::buildAssignmentsForRegisterWrite(), and seq::reg().
buildOp() [15/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, scf::YieldOp yieldOp) const private
Op builder specializations.
Definition at line 939 of file SCFToCalyx.cpp.
References circt::buildWhileIterArgAssignments().
buildOp() [16/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, ShLIOp op) const private
Definition at line 1034 of file SCFToCalyx.cpp.
buildOp() [17/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, ShRSIOp op) const private
Definition at line 1030 of file SCFToCalyx.cpp.
buildOp() [18/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, ShRUIOp op) const private
Definition at line 1026 of file SCFToCalyx.cpp.
buildOp() [19/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, SubIOp op) const private
Definition at line 1022 of file SCFToCalyx.cpp.
buildOp() [20/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, TruncIOp op) const private
Definition at line 1077 of file SCFToCalyx.cpp.
buildOp() [21/21]
LogicalResult circt::BuildOpGroups::buildOp (PatternRewriter & rewriter, XOrIOp op) const private
Definition at line 1046 of file SCFToCalyx.cpp.
createGroupForOp()
template<typename TGroupOp > TGroupOp circt::BuildOpGroups::createGroupForOp (PatternRewriter & rewriter, Operation * op) const inline private
Creates a group named by the basic block which the input op resides in.
Definition at line 774 of file SCFToCalyx.cpp.
FuncOpPartialLoweringPattern()
circt::FuncOpPartialLoweringPattern::FuncOpPartialLoweringPattern inline private
Definition at line 599 of file SCFToCalyx.cpp.
PartiallyLowerFuncToComp()
LogicalResult circt::BuildOpGroups::PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter & rewriter) const inline override private virtual
Partial lowering implementation.
We walk the operations of the funcOp to ensure that all def's have been visited before their uses.
SCF
memref
standard arithmetic
Skip: these special cases will be handled separately.
Implements circt::FuncOpPartialLoweringPattern.
Definition at line 660 of file SCFToCalyx.cpp.
The documentation for this class was generated from the following file:
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp