CIRCT: circt::firrtl::BundleType Class Reference
circt::firrtl::BundleType Class Reference
BundleType is an aggregate of named elements.
#include <FIRRTLTypes.h>
Classes
struct BundleElement
Public Member Functions
ArrayRef< BundleElement > getElements ()
size_t getNumElements ()
llvm::Optional< unsigned > getElementIndex (StringRef name)
Look up an element's index by name. This returns None on failure.
StringRef getElementName (size_t index)
Look up an element's name by index. This asserts if index is invalid.
llvm::Optional< BundleElement > getElement (StringRef name)
Look up an element by name. This returns None on failure.
BundleElement getElement (size_t index)
Look up an element by index. This asserts if index is invalid.
FIRRTLType getElementType (StringRef name)
Look up an element type by name.
FIRRTLType getElementType (size_t index)
Look up an element type by index.
RecursiveTypeProperties getRecursiveTypeProperties ()
Return the recursive properties of the type.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
unsigned getFieldID (unsigned index)
Get an integer ID for the field.
unsigned getIndexForFieldID (unsigned fieldID)
Find the element index corresponding to the desired fieldID.
FIRRTLType getSubTypeByFieldID (unsigned fieldID)
unsigned getMaxFieldID ()
Get the maximum field ID in this bundle.
std::pair< unsigned, bool > rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Static Public Member Functions
static FIRRTLType get (ArrayRef< BundleElement > elements, MLIRContext *context)
Detailed Description
BundleType is an aggregate of named elements.
This is effectively a struct for FIRRTL.
Definition at line 276 of file FIRRTLTypes.h.
Member Function Documentation
get()
FIRRTLType BundleType::get (ArrayRef< BundleElement > elements, MLIRContext * context) static
Definition at line 748 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by getPassiveType(), and updateType().
getElement() [1/2]
BundleType::BundleElement BundleType::getElement (size_t index)
Look up an element by index. This asserts if index is invalid.
Look up an element by index.
Definition at line 813 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElement() [2/2]
auto BundleType::getElement (StringRef name)
Look up an element by name. This returns None on failure.
Look up an element by name. This returns a BundleElement.
Definition at line 806 of file FIRRTLTypes.cpp.
References None.
Referenced by cloneMemWithNewType(), getElementType(), and verifyMemOp().
getElementIndex()
llvm::Optional< unsigned > BundleType::getElementIndex (StringRef name)
Look up an element's index by name. This returns None on failure.
Definition at line 789 of file FIRRTLTypes.cpp.
References getElements(), circt::firrtl::BundleType::BundleElement::name, and None.
getElementName()
StringRef BundleType::getElementName (size_t index)
Look up an element's name by index. This asserts if index is invalid.
Definition at line 799 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElements()
auto BundleType::getElements ()
Definition at line 753 of file FIRRTLTypes.cpp.
Referenced by createWiresForMemoryPorts(), createWrapperModule(), circt::firrtl::getBitWidth(), getBlackBoxPortsForMemOp(), getElement(), getElementIndex(), getElementName(), getElementType(), getIndexForFieldID(), getNumElements(), and verifyHWStructCastOp().
getElementType() [1/2]
FIRRTLType BundleType::getElementType (size_t index)
Look up an element type by index.
Definition at line 824 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElementType() [2/2]
FIRRTLType BundleType::getElementType (StringRef name)
Look up an element type by name.
Definition at line 819 of file FIRRTLTypes.cpp.
References getElement(), and circt::firrtl::BundleType::BundleElement::type.
Referenced by getHandshakeBundleDataType(), and getSubTypeByFieldID().
getFieldID()
unsigned BundleType::getFieldID (unsigned index)
Get an integer ID for the field.
Field IDs start at 1, and are assigned to each field in a bundle in a recursive pre-order walk of all fields, visiting all nested bundle fields. A field ID of 0 is used to reference the bundle itself. The ID can be used to uniquely identify any specific field in this bundle.
Definition at line 830 of file FIRRTLTypes.cpp.
Referenced by cloneMemWithNewType(), circt::firrtl::getFieldRefFromValue(), and rootChildFieldID().
getIndexForFieldID()
unsigned BundleType::getIndexForFieldID (unsigned fieldID)
Find the element index corresponding to the desired fieldID.
If the fieldID corresponds to a field in a nested bundle, it will return the index of the parent field.
Definition at line 834 of file FIRRTLTypes.cpp.
References getElements(), and size().
Referenced by cloneMemWithNewType().
getMaxFieldID()
unsigned BundleType::getMaxFieldID ()
Get the maximum field ID in this bundle.
This is helpful for constructing field IDs when this BundleType is nested in another aggregate type.
Definition at line 851 of file FIRRTLTypes.cpp.
Referenced by rootChildFieldID().
getNumElements()
size_t circt::firrtl::BundleType::getNumElements () inline
Definition at line 300 of file FIRRTLTypes.h.
References getElements().
Referenced by getElement(), getElementName(), getElementType(), rootChildFieldID(), and verifySubfieldOp().
getPassiveType()
FIRRTLType BundleType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 764 of file FIRRTLTypes.cpp.
References get(), and IsPassiveBitMask.
getRecursiveTypeProperties()
RecursiveTypeProperties BundleType::getRecursiveTypeProperties ()
Return the recursive properties of the type.
Return a pair with the 'isPassive' and 'containsAnalog' bits.
Definition at line 758 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::fromFlags().
getSubTypeByFieldID()
FIRRTLType BundleType::getSubTypeByFieldID (unsigned fieldID)
Definition at line 842 of file FIRRTLTypes.cpp.
References getElementType().
rootChildFieldID()
std::pair< unsigned, bool > BundleType::rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Essentially maps a fieldID to a fieldID after a subfield op. Returns the new id and whether the id is in the given child.
Definition at line 853 of file FIRRTLTypes.cpp.
References getFieldID(), getMaxFieldID(), and getNumElements().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp