CIRCT: lib/Dialect/Comb/CombFolds.cpp File Reference
CombFolds.cpp File Reference
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/KnownBits.h"
Functions
static Value createGenericOp (Location loc, OperationName name, ArrayRef< Value > operands, OpBuilder &builder)
Create a new instance of a generic operation that only has value operands, and has a single result value whose type matches the first operand.
static Attribute getIntAttr (const APInt &value, MLIRContext *context)
static void getConcatOperands (Value v, SmallVectorImpl< Value > &result)
Flatten concat and mux operands into a vector.
static ConstantIntMatcher m_RConstant (APInt &value)
template<typename SubType >
static ComplementMatcher< SubType > m_Complement (const SubType &subExpr)
static bool tryFlatteningOperands (Operation *op, PatternRewriter &rewriter)
Flattens a single input in op if hasOneUse is true and it can be defined as an Op.
static std::pair< size_t, size_t > getLowestBitAndHighestBitRequired (Operation *op, bool narrowTrailingBits, size_t originalOpWidth)
static bool narrowOperationWidth (Operation *narrowingCandidate, ValueRange inputs, bool narrowTrailingBits, PatternRewriter &rewriter, function_ref< Value(ArrayRef< Value >)> createOp)
template<class Op >
static bool narrowOperationWidth (Op op, ValueRange inputs, bool narrowTrailingBits, PatternRewriter &rewriter)
static Attribute constFoldBinaryOp (ArrayRef< Attribute > operands, hw::PEO paramOpcode)
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
static LogicalResult extractConcatToConcatExtract (ExtractOp op, ConcatOp innerCat, PatternRewriter &rewriter)
static bool extractFromReplicate (ExtractOp op, ReplicateOp replicate, PatternRewriter &rewriter)
static bool narrowExtractWidth (ExtractOp outerExtractOp, PatternRewriter &rewriter)
static Attribute constFoldAssociativeOp (ArrayRef< Attribute > operands, hw::PEO paramOpcode)
static bool canonicalizeLogicalCstWithConcat (Operation *logicalOp, size_t concatIdx, const APInt &cst, PatternRewriter &rewriter)
When we find a logical operation (and, or, xor) with a constant e.g.
static bool canonicalizeOrOfConcatsWithCstOperands (OrOp op, size_t concatIdx1, size_t concatIdx2, PatternRewriter &rewriter)
Simplify concat ops in an or op when a constant operand is present in either concat.
static void canonicalizeXorIcmpTrue (XorOp op, unsigned icmpOperand, PatternRewriter &rewriter)
template<class Op , bool isSigned>
static OpFoldResult foldDiv (Op op, ArrayRef< Attribute > constants)
template<class Op , bool isSigned>
static OpFoldResult foldMod (Op op, ArrayRef< Attribute > constants)
static bool getMuxChainCondConstant (Value cond, Value indexValue, bool isInverted, std::function< void(hw::ConstantOp)> constantFn)
Check to see if the condition to the specified mux is an equality comparison indexValue and one or more constants.
static bool foldMuxChain (MuxOp rootMux, bool isFalseSide, PatternRewriter &rewriter)
Given a mux, check to see if the "on true" value (or "on false" value if isFalseSide=true) is a mux tree with the same condition.
static Value extractOperandFromFullyAssociative (Operation *fullyAssoc, size_t operandNo, PatternRewriter &rewriter)
Given a fully associative variadic operation like (a+b+c+d), break the expression into two parts, one without the specified operand (e.g.
static bool foldCommonMuxValue (MuxOp op, bool isTrueOperand, PatternRewriter &rewriter)
Fold things like mux(cond, x|y|z|a, a) -> (x|y|z)&replicate(cond)|a and mux(cond, a, x|y|z|a) ->(x|y|z)&replicate(~cond) | a` (when isTrueOperand is true.
static bool foldCommonMuxOperation (MuxOp mux, Operation *trueOp, Operation *falseOp, PatternRewriter &rewriter)
This function is invoke when we find a mux with true/false operations that have the same opcode.
static bool applyCmpPredicate (ICmpPredicate predicate, const APInt &lhs, const APInt &rhs)
static bool applyCmpPredicateToEqualOperands (ICmpPredicate predicate)
template<typename Range >
static size_t computeCommonPrefixLength (const Range &a, const Range &b)
static size_t getTotalWidth (ArrayRef< Value > operands)
static LogicalResult matchAndRewriteCompareConcat (ICmpOp op, Operation *lhs, Operation *rhs, PatternRewriter &rewriter)
Reduce the strength icmp(concat(...), concat(...)) by doing a element-wise comparison on common prefix and suffixes.
static void combineEqualityICmpWithKnownBitsAndConstant (ICmpOp cmpOp, const KnownBits &bitAnalysis, const APInt &rhsCst, PatternRewriter &rewriter)
Given an equality comparison with a constant value and some operand that has known bits, simplify the comparison to check only the unknown bits of the input.
static void combineEqualityICmpWithXorOfConstant (ICmpOp cmpOp, XorOp xorOp, const APInt &rhs, PatternRewriter &rewriter)
Function Documentation
applyCmpPredicate()
static bool applyCmpPredicate (ICmpPredicate predicate, const APInt & lhs, const APInt & rhs) static
Definition at line 2259 of file CombFolds.cpp.
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (ICmpPredicate predicate) static
Definition at line 2288 of file CombFolds.cpp.
Referenced by matchAndRewriteCompareConcat().
canonicalizeLogicalCstWithConcat()
static bool canonicalizeLogicalCstWithConcat (Operation * logicalOp, size_t concatIdx, const APInt & cst, PatternRewriter & rewriter) static
When we find a logical operation (and, or, xor) with a constant e.g.
X & 42, we want to push the constant into the computation of X if it leads to simplification.
This function handles the case where the logical operation has a concat operand. We check to see if we can simplify the concat, e.g. when it has constant operands.
This returns true when a simplification happens.
Definition at line 742 of file CombFolds.cpp.
References createGenericOp().
canonicalizeOrOfConcatsWithCstOperands()
static bool canonicalizeOrOfConcatsWithCstOperands (OrOp op, size_t concatIdx1, size_t concatIdx2, PatternRewriter & rewriter) static
Simplify concat ops in an or op when a constant operand is present in either concat.
This will invert an or(concat, concat) into concat(or, or, ...), which can often be further simplified due to the smaller or ops being easier to fold.
For example:
or(..., concat(x, 0), concat(0, y)) ==> or(..., concat(x, 0, y)), when x and y don't overlap.
or(..., concat(x: i2, cst1: i4), concat(cst2: i5, y: i1)) ==> or(..., concat(or(x: i2, extract(cst2, 4..3)), or(extract(cst1, 3..1), extract(cst2, 2..0)), or(extract(cst1, 0..0), y: i1))
Definition at line 1034 of file CombFolds.cpp.
References circt::firrtl::getBitWidth().
canonicalizeXorIcmpTrue()
static void canonicalizeXorIcmpTrue (XorOp op, unsigned icmpOperand, PatternRewriter & rewriter) static
Definition at line 1205 of file CombFolds.cpp.
combineEqualityICmpWithKnownBitsAndConstant()
static void combineEqualityICmpWithKnownBitsAndConstant (ICmpOp cmpOp, const KnownBits & bitAnalysis, const APInt & rhsCst, PatternRewriter & rewriter) static
Given an equality comparison with a constant value and some operand that has known bits, simplify the comparison to check only the unknown bits of the input.
One simple example of this is that concat(0, stuff) == 0 can be simplified to stuff == 0, or and(x, 3) == 0 can be simplified to extract x[1:0] == 0
Definition at line 2452 of file CombFolds.cpp.
combineEqualityICmpWithXorOfConstant()
static void combineEqualityICmpWithXorOfConstant (ICmpOp cmpOp, XorOp xorOp, const APInt & rhs, PatternRewriter & rewriter) static
Definition at line 2533 of file CombFolds.cpp.
computeCommonPrefixLength()
template<typename Range > static size_t computeCommonPrefixLength (const Range & a, const Range & b) static
Definition at line 2327 of file CombFolds.cpp.
Referenced by matchAndRewriteCompareConcat().
constFoldAssociativeOp()
static Attribute constFoldAssociativeOp (ArrayRef< Attribute > operands, hw::PEO paramOpcode) static
Definition at line 718 of file CombFolds.cpp.
References circt::calyx::direction::get().
constFoldBinaryOp()
static Attribute constFoldBinaryOp (ArrayRef< Attribute > operands, hw::PEO paramOpcode) static
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
Definition at line 312 of file CombFolds.cpp.
References circt::calyx::direction::get().
Referenced by foldDiv(), and foldMod().
createGenericOp()
static Value createGenericOp (Location loc, OperationName name, ArrayRef< Value > operands, OpBuilder & builder) static
Create a new instance of a generic operation that only has value operands, and has a single result value whose type matches the first operand.
This should not be used to create instances of ops with attributes or with more complicated type signatures.
Definition at line 27 of file CombFolds.cpp.
Referenced by canonicalizeLogicalCstWithConcat(), extractOperandFromFullyAssociative(), and tryFlatteningOperands().
extractConcatToConcatExtract()
static LogicalResult extractConcatToConcatExtract (ExtractOp op, ConcatOp innerCat, PatternRewriter & rewriter) static
Definition at line 451 of file CombFolds.cpp.
References circt::calyx::direction::get().
extractFromReplicate()
static bool extractFromReplicate (ExtractOp op, ReplicateOp replicate, PatternRewriter & rewriter) static
Definition at line 532 of file CombFolds.cpp.
extractOperandFromFullyAssociative()
static Value extractOperandFromFullyAssociative (Operation * fullyAssoc, size_t operandNo, PatternRewriter & rewriter) static
Given a fully associative variadic operation like (a+b+c+d), break the expression into two parts, one without the specified operand (e.g.
tmp = a+b+d) and one that combines that into the full expression (e.g. tmp+c), and return the inner expression.
NOTE: This mutates the operation in place if it only has a single user, which assumes that user will be removed.
Definition at line 1856 of file CombFolds.cpp.
References createGenericOp().
Referenced by foldCommonMuxValue().
foldCommonMuxOperation()
static bool foldCommonMuxOperation (MuxOp mux, Operation * trueOp, Operation * falseOp, PatternRewriter & rewriter) static
This function is invoke when we find a mux with true/false operations that have the same opcode.
Check to see if we can strength reduce the mux by applying it to less data by applying this transformation: mux(cond, op(a, b), op(a, c)) -> op(a, mux(cond, b, c))
Definition at line 1990 of file CombFolds.cpp.
References getConcatOperands().
foldCommonMuxValue()
static bool foldCommonMuxValue (MuxOp op, bool isTrueOperand, PatternRewriter & rewriter) static
Fold things like mux(cond, x|y|z|a, a) -> (x|y|z)&replicate(cond)|a and mux(cond, a, x|y|z|a) ->(x|y|z)&replicate(~cond) | a` (when isTrueOperand is true.
Return true on successful transformation, false if not.
These are various forms of "predicated ops" that can be handled with a replicate/and combination.
Definition at line 1896 of file CombFolds.cpp.
References extractOperandFromFullyAssociative().
foldDiv()
template<class Op , bool isSigned> static OpFoldResult foldDiv (Op op, ArrayRef< Attribute > constants) static
Definition at line 1482 of file CombFolds.cpp.
References constFoldBinaryOp().
foldMod()
template<class Op , bool isSigned> static OpFoldResult foldMod (Op op, ArrayRef< Attribute > constants) static
Definition at line 1505 of file CombFolds.cpp.
References constFoldBinaryOp(), and getIntAttr().
foldMuxChain()
static bool foldMuxChain (MuxOp rootMux, bool isFalseSide, PatternRewriter & rewriter) static
Given a mux, check to see if the "on true" value (or "on false" value if isFalseSide=true) is a mux tree with the same condition.
This allows us to turn things like mux(VAL == 0, A, (mux (VAL == 1), B, C)) into array_get (array_create(A, B, C), VAL) which is far more compact and allows synthesis tools to do more interesting optimizations.
This returns false if we cannot form the mux tree (or do not want to) and returns true if the mux was replaced.
Extract constants and values into valuesFound and return true if this is part of the mux tree, otherwise return false.
Definition at line 1749 of file CombFolds.cpp.
References getMuxChainCondConstant().
getConcatOperands()
static void getConcatOperands (Value v, SmallVectorImpl< Value > & result) static
Flatten concat and mux operands into a vector.
Definition at line 41 of file CombFolds.cpp.
References concat().
Referenced by foldCommonMuxOperation(), and matchAndRewriteCompareConcat().
getIntAttr()
static Attribute getIntAttr (const APInt & value, MLIRContext * context) static
Definition at line 35 of file CombFolds.cpp.
References circt::calyx::direction::get().
Referenced by foldMod().
getLowestBitAndHighestBitRequired()
static std::pair<size_t, size_t> getLowestBitAndHighestBitRequired (Operation * op, bool narrowTrailingBits, size_t originalOpWidth) static
Definition at line 138 of file CombFolds.cpp.
Referenced by narrowOperationWidth().
getMuxChainCondConstant()
static bool getMuxChainCondConstant (Value cond, Value indexValue, bool isInverted, std::function< void(hw::ConstantOp)> constantFn) static
Check to see if the condition to the specified mux is an equality comparison indexValue and one or more constants.
If so, put the constants in the constants vector and return true, otherwise return false.
This is part of foldMuxChain.
Definition at line 1702 of file CombFolds.cpp.
Referenced by foldMuxChain().
getTotalWidth()
static size_t getTotalWidth (ArrayRef< Value > operands) static
Definition at line 2341 of file CombFolds.cpp.
Referenced by matchAndRewriteCompareConcat().
m_Complement()
template<typename SubType > static ComplementMatcher<SubType> m_Complement (const SubType & subExpr) inline static
Definition at line 84 of file CombFolds.cpp.
m_RConstant()
static ConstantIntMatcher m_RConstant (APInt & value) inline static
Definition at line 67 of file CombFolds.cpp.
matchAndRewriteCompareConcat()
static LogicalResult matchAndRewriteCompareConcat (ICmpOp op, Operation * lhs, Operation * rhs, PatternRewriter & rewriter) static
Reduce the strength icmp(concat(...), concat(...)) by doing a element-wise comparison on common prefix and suffixes.
Returns success() if a rewriting happens. This handles both concat and replicate.
Definition at line 2356 of file CombFolds.cpp.
References applyCmpPredicateToEqualOperands(), computeCommonPrefixLength(), getConcatOperands(), and getTotalWidth().
narrowExtractWidth()
static bool narrowExtractWidth (ExtractOp outerExtractOp, PatternRewriter & rewriter) static
Definition at line 567 of file CombFolds.cpp.
References narrowOperationWidth().
narrowOperationWidth() [1/2]
template<class Op > static bool narrowOperationWidth (Op op, ValueRange inputs, bool narrowTrailingBits, PatternRewriter & rewriter) static
Definition at line 255 of file CombFolds.cpp.
References narrowOperationWidth().
narrowOperationWidth() [2/2]
static bool narrowOperationWidth (Operation * narrowingCandidate, ValueRange inputs, bool narrowTrailingBits, PatternRewriter & rewriter, function_ref< Value(ArrayRef< Value >)> createOp) static
Definition at line 179 of file CombFolds.cpp.
References getLowestBitAndHighestBitRequired().
Referenced by narrowExtractWidth(), and narrowOperationWidth().
tryFlatteningOperands()
static bool tryFlatteningOperands (Operation * op, PatternRewriter & rewriter) static
Flattens a single input in op if hasOneUse is true and it can be defined as an Op.
Returns true if successful, and false otherwise.
Example: op(1, 2, op(3, 4), 5) -> op(1, 2, 3, 4, 5) // returns true
Definition at line 93 of file CombFolds.cpp.
References createGenericOp(), and size().