CIRCT: lib/Dialect/Calyx/Transforms/CompileControl.cpp File Reference
CompileControl.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/Calyx/CalyxOps.h"
#include "circt/Dialect/Calyx/CalyxPasses.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/TypeSwitch.h"
Classes
class CompileControlVisitor
Functions
static hw::ConstantOp createConstant (OpBuilder &builder, Location loc, size_t bitWidth, size_t value)
A helper function to create constants in the HW dialect.
static size_t getNecessaryBitWidth (size_t numStates)
Given some number of states, returns the necessary bit width TODO(Calyx): Probably a better built-in operation?
static RegisterOp createRegister (OpBuilder &builder, ComponentOp &component, size_t width, StringRef name)
Creates a RegisterOp, with input and output port bit widths defined by width.
Function Documentation
createConstant()
static hw::ConstantOp createConstant (OpBuilder & builder, Location loc, size_t bitWidth, size_t value) static
A helper function to create constants in the HW dialect.
Definition at line 27 of file CompileControl.cpp.
Referenced by CompileControlVisitor::visit().
createRegister()
static RegisterOp createRegister (OpBuilder & builder, ComponentOp & component, size_t width, StringRef name) static
Creates a RegisterOp, with input and output port bit widths defined by width.
Definition at line 43 of file CompileControl.cpp.
Referenced by CompileControlVisitor::visit().
getNecessaryBitWidth()
static size_t getNecessaryBitWidth (size_t numStates) static
Given some number of states, returns the necessary bit width TODO(Calyx): Probably a better built-in operation?
Definition at line 35 of file CompileControl.cpp.
Referenced by CompileControlVisitor::visit().