CIRCT: lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp File Reference
CreateSiFiveMetadata.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/InstanceGraph.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/JSON.h"
Functions
static LogicalResult removeAnnotationWithFilename (Operation *op, StringRef annoClass, StringRef &filename)
This will search for a target annotation and remove it from the operation.
Variables
static const char dutAnnoClass [] = "sifive.enterprise.firrtl.MarkDUTAnnotation"
static const char metadataDirectoryAnnoClass []
Attribute that indicates where some json files should be dumped.
Function Documentation
removeAnnotationWithFilename()
static LogicalResult removeAnnotationWithFilename (Operation * op, StringRef annoClass, StringRef & filename) static
This will search for a target annotation and remove it from the operation.
If the annotation has a filename, it will be returned in the output argument. If the annotation is missing the filename member, or if more than one matching annotation is attached, it will print an error and return failure.
Definition at line 229 of file CreateSiFiveMetadata.cpp.
References circt::firrtl::Annotation::getMember(), if(), and circt::firrtl::Annotation::isClass().
Variable Documentation
dutAnnoClass
const char dutAnnoClass[] = "sifive.enterprise.firrtl.MarkDUTAnnotation" static
Definition at line 28 of file CreateSiFiveMetadata.cpp.
metadataDirectoryAnnoClass
const char metadataDirectoryAnnoClass[] static
Initial value:
=
    "sifive.enterprise.firrtl.MetadataDirAnnotation"
Attribute that indicates where some json files should be dumped.
Definition at line 30 of file CreateSiFiveMetadata.cpp.