CIRCT: lib/CAPI/Dialect/ESI.cpp File Reference
ESI.cpp File Reference
#include "circt-c/Dialect/ESI.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Parser.h"
#include "mlir/Support/FileUtilities.h"
Functions
void registerESIPasses ()
MlirLogicalResult circtESIExportCosimSchema (MlirModule module, MlirStringCallback callback, void *userData)
bool circtESITypeIsAChannelType (MlirType type)
MlirType circtESIChannelTypeGet (MlirType inner)
MlirType circtESIChannelGetInner (MlirType channelType)
MlirOperation circtESIWrapModule (MlirOperation cModOp, long numPorts, const MlirStringRef *ports)
void circtESIAppendMlirFile (MlirModule cMod, MlirStringRef filename)
MlirOperation circtESILookup (MlirModule mod, MlirStringRef symbol)
Function Documentation
circtESIAppendMlirFile()
void circtESIAppendMlirFile (MlirModule cMod, MlirStringRef filename)
Definition at line 56 of file ESI.cpp.
Referenced by System::loadMlir().
circtESIChannelGetInner()
MlirType circtESIChannelGetInner (MlirType channelType)
Definition at line 39 of file ESI.cpp.
circtESIChannelTypeGet()
MlirType circtESIChannelTypeGet (MlirType inner)
Definition at line 34 of file ESI.cpp.
References circt::calyx::direction::get().
circtESIExportCosimSchema()
MlirLogicalResult circtESIExportCosimSchema (MlirModule module, MlirStringCallback callback, void * userData)
Definition at line 23 of file ESI.cpp.
References circt::esi::exportCosimSchema().
Referenced by System::printCapnpSchema().
circtESILookup()
MlirOperation circtESILookup (MlirModule mod, MlirStringRef symbol)
Definition at line 68 of file ESI.cpp.
Referenced by System::lookup().
circtESITypeIsAChannelType()
bool circtESITypeIsAChannelType (MlirType type)
Definition at line 30 of file ESI.cpp.
circtESIWrapModule()
MlirOperation circtESIWrapModule (MlirOperation cModOp, long numPorts, const MlirStringRef * ports)
Definition at line 43 of file ESI.cpp.
References circt::esi::buildESIWrapper(), and circt::esi::resolvePortNames().
registerESIPasses()
void registerESIPasses ()
Definition at line 21 of file ESI.cpp.
References circt::esi::registerESIPasses(), and registerPasses().
Referenced by circt::registerAllPasses(), and registerESIPasses().