CIRCT: lib/Dialect/ESI/ESIOps.cpp File Reference
ESIOps.cpp File Reference
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/SV/SVTypes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/SymbolTable.h"
#include "circt/Dialect/ESI/ESI.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static ParseResult parseChannelBuffer (OpAsmParser &parser, OperationState &result)
static void printChannelBuffer (OpAsmPrinter &p, ChannelBuffer &op)
static ParseResult parsePipelineStage (OpAsmParser &parser, OperationState &result)
static void printPipelineStage (OpAsmPrinter &p, PipelineStage &op)
static ParseResult parseWrapValidReady (OpAsmParser &parser, OperationState &result)
void printWrapValidReady (OpAsmPrinter &p, WrapValidReady &op)
static ParseResult parseUnwrapValidReady (OpAsmParser &parser, OperationState &result)
static void printUnwrapValidReady (OpAsmPrinter &p, UnwrapValidReady &op)
static Type getEsiDataType (circt::sv::InterfaceOp iface)
If 'iface' looks like an ESI interface, return the inner data type.
static LogicalResult verifySVInterface (Operation *op, circt::sv::ModportType modportType, ChannelPort chanType)
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
static LogicalResult verifyWrapSVInterface (WrapSVInterface &op)
static LogicalResult verifyUnwrapSVInterface (UnwrapSVInterface &op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 219 of file ESIOps.cpp.
Function Documentation
getEsiDataType()
static Type getEsiDataType (circt::sv::InterfaceOp iface) static
If 'iface' looks like an ESI interface, return the inner data type.
Definition at line 170 of file ESIOps.cpp.
Referenced by verifySVInterface().
parseChannelBuffer()
static ParseResult parseChannelBuffer (OpAsmParser & parser, OperationState & result) static
Definition at line 29 of file ESIOps.cpp.
References circt::calyx::direction::get().
parsePipelineStage()
static ParseResult parsePipelineStage (OpAsmParser & parser, OperationState & result) static
Definition at line 70 of file ESIOps.cpp.
References circt::calyx::direction::get().
parseUnwrapValidReady()
static ParseResult parseUnwrapValidReady (OpAsmParser & parser, OperationState & result) static
Definition at line 134 of file ESIOps.cpp.
References circt::calyx::direction::get().
parseWrapValidReady()
static ParseResult parseWrapValidReady (OpAsmParser & parser, OperationState & result) static
Definition at line 101 of file ESIOps.cpp.
References circt::calyx::direction::get().
printChannelBuffer()
static void printChannelBuffer (OpAsmPrinter & p, ChannelBuffer & op) static
Definition at line 59 of file ESIOps.cpp.
printPipelineStage()
static void printPipelineStage (OpAsmPrinter & p, PipelineStage & op) static
Definition at line 91 of file ESIOps.cpp.
printUnwrapValidReady()
static void printUnwrapValidReady (OpAsmPrinter & p, UnwrapValidReady & op) static
Definition at line 157 of file ESIOps.cpp.
printWrapValidReady()
void printWrapValidReady (OpAsmPrinter & p, WrapValidReady & op)
Definition at line 122 of file ESIOps.cpp.
verifySVInterface()
static LogicalResult verifySVInterface (Operation * op, circt::sv::ModportType modportType, ChannelPort chanType) static
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
Definition at line 185 of file ESIOps.cpp.
References getEsiDataType().
Referenced by verifyUnwrapSVInterface(), and verifyWrapSVInterface().
verifyUnwrapSVInterface()
static LogicalResult verifyUnwrapSVInterface (UnwrapSVInterface & op) static
Definition at line 212 of file ESIOps.cpp.
References verifySVInterface().
verifyWrapSVInterface()
static LogicalResult verifyWrapSVInterface (WrapSVInterface & op) static
Definition at line 205 of file ESIOps.cpp.
References verifySVInterface().