CIRCT: lib/Dialect/MSFT/ExportQuartusTcl.cpp File Reference
ExportQuartusTcl.cpp File Reference
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/MSFT/DeviceDB.h"
#include "circt/Dialect/MSFT/ExportTcl.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/Builders.h"
#include "mlir/Translation.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
Functions
void emitInnerRefPart (TclOutputState &s, Operation *op)
void emitPath (TclOutputState &s, PlacementDB::PlacedInstance inst, SymbolCache &symCache)
static void emit (TclOutputState &s, PlacementDB::PlacedInstance inst, PhysLocationAttr pla, SymbolCache &symCache)
Emit tcl in the form of: "set_location_assignment MPDSP_X34_Y285_N0 -to $parent|fooInst|entityName".
static void emit (TclOutputState &s, PlacementDB::PlacedInstance inst, PhysicalRegionRefAttr regionRef, SymbolCache &symCache)
Emit tcl in the form of: set_instance_assignment -name PLACE_REGION "X1 Y1 X20 Y20" -to $parent|a|b|c set_instance_assignment -name RESERVE_PLACE_REGION OFF -to $parent|a|b|c set_instance_assignment -name CORE_ONLY_PLACE_REGION ON -to $parent|a|b|c set_instance_assignment -name REGION_NAME test_region -to $parent|a|b|c.
Function Documentation
emit() [1/2]
static void emit (TclOutputState & s, PlacementDB::PlacedInstance inst, PhysicalRegionRefAttr regionRef, SymbolCache & symCache) static
Emit tcl in the form of: set_instance_assignment -name PLACE_REGION "X1 Y1 X20 Y20" -to $parent|a|b|c set_instance_assignment -name RESERVE_PLACE_REGION OFF -to $parent|a|b|c set_instance_assignment -name CORE_ONLY_PLACE_REGION ON -to $parent|a|b|c set_instance_assignment -name REGION_NAME test_region -to $parent|a|b|c.
Definition at line 133 of file ExportQuartusTcl.cpp.
References emitPath().
emit() [2/2]
static void emit (TclOutputState & s, PlacementDB::PlacedInstance inst, PhysLocationAttr pla, SymbolCache & symCache) static
Emit tcl in the form of: "set_location_assignment MPDSP_X34_Y285_N0 -to $parent|fooInst|entityName".
Definition at line 99 of file ExportQuartusTcl.cpp.
References emitPath().
emitInnerRefPart()
void emitInnerRefPart (TclOutputState & s, Operation * op)
Definition at line 50 of file ExportQuartusTcl.cpp.
References circt::calyx::direction::get().
Referenced by emitPath().
emitPath()
void emitPath (TclOutputState & s, PlacementDB::PlacedInstance inst, SymbolCache & symCache)
Definition at line 72 of file ExportQuartusTcl.cpp.
References emitInnerRefPart().
Referenced by emit().