CIRCT: lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp File Reference
FIRAnnotations.cpp File Reference
#include "FIRAnnotations.h"
#include "AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRParser.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/JSON.h"
Functions
static std::pair< StringRef, llvm::Optional< ArrayAttr > > splitTarget (StringRef target, MLIRContext *context)
Split a target into a base target (including a reference if one exists) and an optional array of subfield/subindex tokens.
static SmallVector< std::tuple< std::string, StringRef, StringRef > > expandNonLocal (StringRef target)
Split out non-local paths.
static FlatSymbolRefAttr buildNLA (CircuitOp circuit, size_t nlaSuffix, SmallVectorImpl< std::tuple< std::string, StringRef, StringRef >> &nlas)
Make an anchor for a non-local annotation.
static void appendTarget (NamedAttrList &annotation, ArrayAttr target)
Append the argument target to the annotation using the key "target".
static std::pair< StringRef, llvm::Optional< ArrayAttr > > splitAndAppendTarget (NamedAttrList &annotation, StringRef target, MLIRContext *context)
Mutably update a prototype Annotation (stored as a NamedAttrList) with subfield/subindex information from a Target string.
static llvm::Optional< std::string > canonicalizeTarget (StringRef target)
Return an input target string in canonical form.
template<typename A >
static A tryGetAs (DictionaryAttr &dict, const Attribute &root, StringRef key, Location loc, Twine className, Twine path=Twine())
Implements the same behavior as DictionaryAttr::getAs<A> to return the value of a specific type associated with a key in a dictionary.
static Attribute convertJSONToAttribute (MLIRContext *context, json::Value &value, json::Path p)
Convert arbitrary JSON to an MLIR Attribute.
static std::string addNLATargets (MLIRContext *context, StringRef targetStrRef, CircuitOp circuit, size_t &nlaNumber, NamedAttrList &metadata, llvm::StringMap< llvm::SmallVector< Attribute >> &mutableAnnotationMap)
static Optional< DictionaryAttr > parseAugmentedType (MLIRContext *context, DictionaryAttr augmentedType, DictionaryAttr root, llvm::StringMap< llvm::SmallVector< Attribute >> &newAnnotations, StringRef companion, StringAttr name, StringAttr defName, Optional< IntegerAttr > id, Optional< StringAttr >(description), Location loc, unsigned &annotationID, Twine clazz, Twine path={})
Recursively walk a sifive.enterprise.grandcentral.AugmentedType to extract any annotations it may contain.
static Optional< Attribute > scatterOMIR (Attribute original, unsigned &annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> &newAnnotations, CircuitOp circuit, size_t &nlaNumber)
Recursively walk Object Model IR and convert FIRRTL targets to identifiers while scattering trackers into the newAnnotations argument.
static Optional< std::pair< StringRef, DictionaryAttr > > scatterOMField (Attribute original, const Attribute root, unsigned &annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> &newAnnotations, CircuitOp circuit, size_t &nlaNumber, Location loc, unsigned index)
Convert an Object Model Field into an optional pair of a string key and a dictionary attribute.
static Optional< DictionaryAttr > scatterOMNode (Attribute original, const Attribute root, unsigned &annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> &newAnnotations, CircuitOp circuit, size_t &nlaNumber, Location loc)
Convert an Object Model Node to an optional dictionary, convert source locator strings to location attributes, and scatter FIRRTL targets into the circuit.
static Optional< Attribute > scatterOMIRAnnotation (DictionaryAttr dict, unsigned &annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> &newAnnotations, CircuitOp circuit, size_t &nlaNumber, Location loc)
Main entry point to handle scattering of an OMIRAnnotation.
Function Documentation
addNLATargets()
static std::string addNLATargets (MLIRContext * context, StringRef targetStrRef, CircuitOp circuit, size_t & nlaNumber, NamedAttrList & metadata, llvm::StringMap< llvm::SmallVector< Attribute >> & mutableAnnotationMap) static
Definition at line 313 of file FIRAnnotations.cpp.
References buildNLA(), expandNonLocal(), circt::calyx::direction::get(), and splitAndAppendTarget().
Referenced by scatterOMIR().
appendTarget()
static void appendTarget (NamedAttrList & annotation, ArrayAttr target) inline static
Append the argument target to the annotation using the key "target".
Definition at line 153 of file FIRAnnotations.cpp.
Referenced by splitAndAppendTarget().
buildNLA()
static FlatSymbolRefAttr buildNLA (CircuitOp circuit, size_t nlaSuffix, SmallVectorImpl< std::tuple< std::string, StringRef, StringRef >> & nlas) static
Make an anchor for a non-local annotation.
Use the expanded path to build the module and name list in the anchor.
Definition at line 135 of file FIRAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addNLATargets(), and circt::firrtl::scatterCustomAnnotations().
canonicalizeTarget()
static llvm::Optional<std::string> canonicalizeTarget (StringRef target) static
Return an input target string in canonical form.
This converts a Legacy Annotation (e.g., A.B.C) into a modern annotation (e.g., ~A|B>C). Trailing subfield/subindex references are preserved.
Definition at line 177 of file FIRAnnotations.cpp.
Referenced by circt::firrtl::scatterCustomAnnotations(), and scatterOMIR().
convertJSONToAttribute()
static Attribute convertJSONToAttribute (MLIRContext * context, json::Value & value, json::Path p) static
Convert arbitrary JSON to an MLIR Attribute.
Definition at line 259 of file FIRAnnotations.cpp.
References circt::calyx::direction::get().
expandNonLocal()
static SmallVector<std::tuple<std::string, StringRef, StringRef> > expandNonLocal (StringRef target) static
Split out non-local paths.
This will return a set of target strings for each named entity along the path. c|c:ai/Am:bi/Bm>d.agg[3] -> c|c>ai, c|Am>bi, c|Bm>d.agg[2]
Definition at line 105 of file FIRAnnotations.cpp.
Referenced by addNLATargets(), and circt::firrtl::scatterCustomAnnotations().
parseAugmentedType()
static Optional<DictionaryAttr> parseAugmentedType (MLIRContext * context, DictionaryAttr augmentedType, DictionaryAttr root, llvm::StringMap< llvm::SmallVector< Attribute >> & newAnnotations, StringRef companion, StringAttr name, StringAttr defName, Optional< IntegerAttr > id, Optional< StringAttr > description, Location loc, unsigned & annotationID, Twine clazz, Twine path = {}) static
Recursively walk a sifive.enterprise.grandcentral.AugmentedType to extract any annotations it may contain.
This is going to generate two types of annotations: 1) Annotations necessary to build interfaces and store them at "~" 2) Scattered annotations for how components bind to interfaces
Return a new identifier that can be used to link scattered annotations together. This mutates the by-reference parameter annotationID.
Optionally unpack a ReferenceTarget encoded as a DictionaryAttr. Return either a pair containing the Target string (up to the reference) and an array of components or none if the input is malformed. The input DicionaryAttr encoding is a JSON object of a serialized ReferenceTarget Scala class. By example, this is converting: ~Foo|Foo>a.b[0] To: {"~Foo|Foo>a", {".b", "[0]"}} The format of a ReferenceTarget object like: circuit: String module: String path: Seq[(Instance, OfModule)] ref: String component: Seq[TargetToken]
Definition at line 580 of file FIRAnnotations.cpp.
Referenced by circt::firrtl::scatterCustomAnnotations().
scatterOMField()
static Optional<std::pair<StringRef, DictionaryAttr> > scatterOMField (Attribute original, const Attribute root, unsigned & annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> & newAnnotations, CircuitOp circuit, size_t & nlaNumber, Location loc, unsigned index) static
Convert an Object Model Field into an optional pair of a string key and a dictionary attribute.
Expand internal source locator strings to location attributes. Scatter any FIRRTL targets into the circuit. If this is an illegal Object Model Field return None.
Each Object Model Field consists of three mandatory members with the following names and types:
"info": Source Locator String
"name": String
"value": Object Model IR
The key is the "name" and the dictionary consists of the "info" and "value" members. Each value is recursively traversed to scatter any FIRRTL targets that may be used inside it.
This conversion from an object (dictionary) to key–value pair is safe because each Object Model Field in an Object Model Node must have a unique "name". Anything else is illegal Object Model.
Definition at line 1057 of file FIRAnnotations.cpp.
References circt::calyx::direction::get(), circt::firrtl::maybeStringToLocation(), None, circt::firrtl::omirAnnoClass, and scatterOMIR().
Referenced by scatterOMNode().
scatterOMIR()
static Optional<Attribute> scatterOMIR (Attribute original, unsigned & annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> & newAnnotations, CircuitOp circuit, size_t & nlaNumber) static
Recursively walk Object Model IR and convert FIRRTL targets to identifiers while scattering trackers into the newAnnotations argument.
Object Model IR consists of a type hierarchy built around recursive arrays and dictionaries whose leaves are "string-encoded types". This is an Object Model-specific construct that puts type information alongside a value. Concretely, these look like:
'OM' type ':' value
This function is only concerned with unpacking types whose values are FIRRTL targets. This is because these need to be kept up-to-date with modifications made to the circuit whereas other types are just passing through CIRCT.
At a later time this understanding may be expanded or Object Model IR may become its own Dialect. At this time, this function is trying to do as minimal work as possible to just validate that the OMIR looks okay without doing lots of unnecessary unpacking/repacking of string-encoded types.
Definition at line 906 of file FIRAnnotations.cpp.
References addNLATargets(), canonicalizeTarget(), circt::calyx::direction::get(), circt::firrtl::isOMIRStringEncodedPassthrough(), None, and circt::firrtl::omirTrackerAnnoClass.
Referenced by scatterOMField().
scatterOMIRAnnotation()
static Optional<Attribute> scatterOMIRAnnotation (DictionaryAttr dict, unsigned & annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> & newAnnotations, CircuitOp circuit, size_t & nlaNumber, Location loc) static
Main entry point to handle scattering of an OMIRAnnotation.
Return the modified optional attribute on success and None on failure. Any scattered annotations will be added to the reference argument newAnnotations.
Definition at line 1198 of file FIRAnnotations.cpp.
References circt::calyx::direction::get(), None, circt::firrtl::omirAnnoClass, and scatterOMNode().
Referenced by circt::firrtl::scatterCustomAnnotations().
scatterOMNode()
static Optional<DictionaryAttr> scatterOMNode (Attribute original, const Attribute root, unsigned & annotationID, llvm::StringMap< llvm::SmallVector< Attribute >> & newAnnotations, CircuitOp circuit, size_t & nlaNumber, Location loc) static
Convert an Object Model Node to an optional dictionary, convert source locator strings to location attributes, and scatter FIRRTL targets into the circuit.
If this is an illegal Object Model Node, then return None.
An Object Model Node is expected to look like:
"info": Source Locator String
"id": String-encoded integer ('OMID' ':' Integer)
"fields": Array<Object>
The "fields" member may be absent. If so, then construct an empty array.
The input attribute must be a dictionary.
Definition at line 1125 of file FIRAnnotations.cpp.
References circt::calyx::direction::get(), circt::firrtl::maybeStringToLocation(), None, circt::firrtl::omirAnnoClass, and scatterOMField().
Referenced by scatterOMIRAnnotation().
splitAndAppendTarget()
static std::pair<StringRef, llvm::Optional<ArrayAttr> > splitAndAppendTarget (NamedAttrList & annotation, StringRef target, MLIRContext * context) static
Mutably update a prototype Annotation (stored as a NamedAttrList) with subfield/subindex information from a Target string.
Subfield/subindex information will be placed in the key "target" at the back of the Annotation. If no subfield/subindex information, the Annotation is unmodified. Return the split input target as a base target (include a reference if one exists) and an optional array containing subfield/subindex tokens.
Definition at line 165 of file FIRAnnotations.cpp.
References appendTarget(), and splitTarget().
Referenced by addNLATargets(), and circt::firrtl::scatterCustomAnnotations().
splitTarget()
static std::pair<StringRef, llvm::Optional<ArrayAttr> > splitTarget (StringRef target, MLIRContext * context) static
Split a target into a base target (including a reference if one exists) and an optional array of subfield/subindex tokens.
Definition at line 36 of file FIRAnnotations.cpp.
References circt::calyx::direction::get(), and None.
Referenced by splitAndAppendTarget().
tryGetAs()
template<typename A > static A tryGetAs (DictionaryAttr & dict, const Attribute & root, StringRef key, Location loc, Twine className, Twine path = Twine()) static
Implements the same behavior as DictionaryAttr::getAs<A> to return the value of a specific type associated with a key in a dictionary.
However, this is specialized to print a useful error message, specific to custom annotation process, on failure.
Definition at line 221 of file FIRAnnotations.cpp.