CIRCT: lib/Dialect/FIRRTL/FIRRTLTypes.cpp File Reference
FIRRTLTypes.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.cpp.inc"
Classes
struct circt::firrtl::detail::WidthTypeStorage
struct circt::firrtl::detail::BundleTypeStorage
struct circt::firrtl::detail::VectorTypeStorage
Namespaces
circt
circt::firrtl
circt::firrtl::detail
Macros
#define GET_TYPEDEF_CLASSES
Enumerations
enum { IsPassiveBitMask = 0x1, ContainsAnalogBitMask = 0x2, HasUninferredWidthBitMask = 0x4 }
Functions
static void printType (Type type, AsmPrinter &os)
Print a type defined by this dialect.
static LogicalResult customTypePrinter (Type type, AsmPrinter &os)
Print a type with a custom printer implementation.
static ParseResult parseFIRRTLType (FIRRTLType &result, AsmParser &parser)
Parse a FIRRTLType.
static OptionalParseResult customTypeParser (AsmParser &parser, StringRef name, Type &result)
Parse a type with a custom parser implementation.
static ParseResult parseType (Type &result, StringRef name, AsmParser &parser)
Parse a type defined by this dialect.
static ParseResult parseFIRRTLType (FIRRTLType &result, StringRef name, AsmParser &parser)
Parse a FIRRTLType with a name that has already been parsed.
static bool areBundleElementsEquivalent (BundleType::BundleElement destElement, BundleType::BundleElement srcElement)
Helper to implement the equivalence logic for a pair of bundle elements.
static Optional< int32_t > getWidthQualifiedTypeWidth (firrtl::detail::WidthTypeStorage *impl)
llvm::hash_code circt::firrtl::hash_value (const BundleType::BundleElement &arg)
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 31 of file FIRRTLTypes.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IsPassiveBitMask
Bit set if the type only contains passive elements.
ContainsAnalogBitMask
Bit set if the type contains an analog type.
HasUninferredWidthBitMask
Bit set fi the type has any uninferred bit widths.
Definition at line 288 of file FIRRTLTypes.cpp.
Function Documentation
areBundleElementsEquivalent()
static bool areBundleElementsEquivalent (BundleType::BundleElement destElement, BundleType::BundleElement srcElement) static
Helper to implement the equivalence logic for a pair of bundle elements.
Note that the FIRRTL spec requires bundle elements to have the same orientation, but this only compares their passive types. The FIRRTL dialect differs from the spec in how it uses flip types for module output ports and canonicalizes flips in bundles, so only passive types can be compared here.
Definition at line 494 of file FIRRTLTypes.cpp.
customTypeParser()
static OptionalParseResult customTypeParser (AsmParser & parser, StringRef name, Type & result) static
Parse a type with a custom parser implementation.
This only accepts a subset of all types in the dialect. Use parseType instead, which will call this function in turn, as appropriate.
Returns llvm::None if the type name is not covered by the custom parsers. Otherwise returns success or failure as appropriate. On success, result is set to the resulting type.
firrtl-type
  ::= clock
  ::= reset
  ::= asyncreset
  ::= sint ('<' int '>')?
  ::= uint ('<' int '>')?
  ::= analog ('<' int '>')?
  ::= bundle '<' (bundle-elt (',' bundle-elt)*)? '>'
  ::= vector '<' type ',' int '>'
bundle-elt ::= identifier ':' type
Definition at line 129 of file FIRRTLTypes.cpp.
customTypePrinter()
static LogicalResult customTypePrinter (Type type, AsmPrinter & os) static
Print a type with a custom printer implementation.
This only prints a subset of all types in the dialect. Use printType instead, which will call this function in turn, as appropriate.
Definition at line 44 of file FIRRTLTypes.cpp.
getWidthQualifiedTypeWidth()
static Optional<int32_t> getWidthQualifiedTypeWidth (firrtl::detail::WidthTypeStorage * impl) static
Definition at line 649 of file FIRRTLTypes.cpp.
References None, and circt::firrtl::detail::WidthTypeStorage::width.
Referenced by circt::firrtl::SIntType::getWidth(), circt::firrtl::UIntType::getWidth(), and circt::firrtl::AnalogType::getWidth().
parseFIRRTLType() [1/2]
static ParseResult parseFIRRTLType (FIRRTLType & result, AsmParser & parser) static
Parse a FIRRTLType.
Note that only a subset of types defined in the FIRRTL dialect inherit from FIRRTLType. Use parseType to parse any of the defined types.
Definition at line 259 of file FIRRTLTypes.cpp.
parseFIRRTLType() [2/2]
static ParseResult parseFIRRTLType (FIRRTLType & result, StringRef name, AsmParser & parser) static
Parse a FIRRTLType with a name that has already been parsed.
Note that only a subset of types defined in the FIRRTL dialect inherit from FIRRTLType. Use parseType to parse any of the defined types.
Definition at line 242 of file FIRRTLTypes.cpp.
parseType()
static ParseResult parseType (Type & result, StringRef name, AsmParser & parser) static
Parse a type defined by this dialect.
This will first try the generated type parsers and then resort to the custom parser implementation. Emits an error and returns failure if name does not refer to a type defined in this dialect.
Definition at line 219 of file FIRRTLTypes.cpp.
printType()
static void printType (Type type, AsmPrinter & os) static
Print a type defined by this dialect.
Definition at line 88 of file FIRRTLTypes.cpp.