CIRCT: lib/Dialect/FIRRTL/FIRRTLOps.cpp File Reference
FIRRTLOps.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "circt/Dialect/FIRRTL/FIRRTL.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
template<typename T >
static SmallVector< T > removeElementsAtIndices (ArrayRef< T > input, ArrayRef< unsigned > indicesToDrop)
Remove elements at the specified indices from the input array, returning the elements not mentioned.
static ParseResult parseCircuitOpAttrs (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printCircuitOpAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static LogicalResult verifyCircuitOp (CircuitOp circuit)
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations)
static bool printModulePorts (OpAsmPrinter &p, Block *block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms)
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
static ParseResult parseModulePorts (OpAsmParser &parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::OperandType > &entryArgs, SmallVectorImpl< Direction > &portDirections, SmallVectorImpl< Attribute > &portNames, SmallVectorImpl< Attribute > &portTypes, SmallVectorImpl< Attribute > &portAnnotations, SmallVectorImpl< Attribute > &portSyms)
Parse a list of module ports.
static void printFModuleLikeOp (OpAsmPrinter &p, FModuleLike op)
static void printFExtModuleOp (OpAsmPrinter &p, FExtModuleOp op)
static void printFModuleOp (OpAsmPrinter &p, FModuleOp op)
static ParseResult parseFModuleLikeOp (OpAsmParser &parser, OperationState &result, bool hasSSAIdentifiers)
static ParseResult parseFModuleOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseFExtModuleOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyFExtModuleOp (FExtModuleOp op)
static LogicalResult verifyInstanceOp (InstanceOp instance)
Verify the correctness of an InstanceOp.
static void printInstanceOp (OpAsmPrinter &p, InstanceOp &op)
static ParseResult parseInstanceOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyMemoryPortOp (MemoryPortOp memoryPort)
static LogicalResult verifyMemOp (MemOp mem)
Verify the correctness of a MemOp.
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type)
Return the kind of port this is given the port type from a 'mem' decl.
static LogicalResult verifyConnectOp (ConnectOp connect)
static LogicalResult verifyPartialConnectOp (PartialConnectOp partialConnect)
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name)
Get an attribute by name from a list of named attributes.
static void printConstantOp (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyConstantOp (ConstantOp constant)
static void printSpecialConstantOp (OpAsmPrinter &p, SpecialConstantOp &op)
static ParseResult parseSpecialConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifySubfieldOp (SubfieldOp op)
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t &lhsWidth, int32_t &rhsWidth, Optional< Location > loc)
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
static LogicalResult verifyHWStructCastOp (HWStructCastOp cast)
static LogicalResult verifyBitCastOp (BitCastOp cast)
static ParseResult parseElideAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
static void printElideAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseElidePortAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
static void printElidePortAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseMemoryPortOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemoryPortOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "direction" and elide "annotations" if it exists or if it is empty.
static ParseResult parseSeqMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printSeqMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
static ParseResult parseMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
static ParseResult parseElideEmptyName (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printElideEmptyName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parsePrintfAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printPrintfAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseStopAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printStopAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseVerifAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printVerifAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3019 of file FIRRTLOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations) static
Definition at line 509 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::direction::packAttribute().
getAttr()
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name) static
Get an attribute by name from a list of named attributes.
Same as above, but casts the attribute to a specific type.
Aborts if the attribute does not exist.
Definition at line 1901 of file FIRRTLOps.cpp.
getMemPortKindFromType()
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type) static
Return the kind of port this is given the port type from a 'mem' decl.
Definition at line 1593 of file FIRRTLOps.cpp.
isSameIntTypeKind()
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t & lhsWidth, int32_t & rhsWidth, Optional< Location > loc) static
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
If unknown, return -1 for the widths.
On failure, this reports and error and returns false. This function should not be used if you don't want an error reported.
Definition at line 2176 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::getWidthOrSentinel(), and circt::firrtl::IntType::isSigned().
Referenced by circt::firrtl::impl::inferAddSubResult(), circt::firrtl::impl::inferBitwiseResult(), and circt::firrtl::impl::verifySameOperandsIntTypeKind().
parseCircuitOpAttrs()
static ParseResult parseCircuitOpAttrs (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 204 of file FIRRTLOps.cpp.
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1932 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::getWidthOrSentinel(), circt::firrtl::IntType::hasWidth(), and circt::firrtl::IntType::isSigned().
parseElideAnnotations()
static ParseResult parseElideAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
Definition at line 2794 of file FIRRTLOps.cpp.
Referenced by parseElidePortAnnotations(), parseImplicitSSAName(), and parseMemoryPortOp().
parseElideEmptyName()
static ParseResult parseElideEmptyName (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 2966 of file FIRRTLOps.cpp.
Referenced by parsePrintfAttrs(), parseStopAttrs(), and parseVerifAttrs().
parseElidePortAnnotations()
static ParseResult parseElidePortAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
Definition at line 2816 of file FIRRTLOps.cpp.
References parseElideAnnotations().
Referenced by parseMemOp().
parseFExtModuleOp()
static ParseResult parseFExtModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 876 of file FIRRTLOps.cpp.
References parseFModuleLikeOp().
parseFModuleLikeOp()
static ParseResult parseFModuleLikeOp (OpAsmParser & parser, OperationState & result, bool hasSSAIdentifiers) static
Definition at line 782 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::direction::packAttribute(), and parseModulePorts().
Referenced by parseFExtModuleOp(), and parseFModuleOp().
parseFModuleOp()
static ParseResult parseFModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 872 of file FIRRTLOps.cpp.
References parseFModuleLikeOp().
parseImplicitSSAName()
static ParseResult parseImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 2845 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), isdigit, and parseElideAnnotations().
Referenced by parseSeqMemOp().
parseInstanceOp()
static ParseResult parseInstanceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1226 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::hw::InnerName::getInnerNameAttrName(), circt::firrtl::direction::packAttribute(), and parseModulePorts().
parseMemOp()
static ParseResult parseMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 2952 of file FIRRTLOps.cpp.
References parseElidePortAnnotations().
parseMemoryPortOp()
static ParseResult parseMemoryPortOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 2901 of file FIRRTLOps.cpp.
References parseElideAnnotations().
parseModulePorts()
static ParseResult parseModulePorts (OpAsmParser & parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::OperandType > & entryArgs, SmallVectorImpl< Direction > & portDirections, SmallVectorImpl< Attribute > & portNames, SmallVectorImpl< Attribute > & portTypes, SmallVectorImpl< Attribute > & portAnnotations, SmallVectorImpl< Attribute > & portSyms) static
Parse a list of module ports.
If port names are SSA identifiers, then this will populate entryArgs.
Definition at line 662 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::In, isdigit, and circt::firrtl::Out.
Referenced by parseFModuleLikeOp(), and parseInstanceOp().
parsePrintfAttrs()
static ParseResult parsePrintfAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 2986 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseSeqMemOp()
static ParseResult parseSeqMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 2918 of file FIRRTLOps.cpp.
References parseImplicitSSAName().
parseSpecialConstantOp()
static ParseResult parseSpecialConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2024 of file FIRRTLOps.cpp.
parseStopAttrs()
static ParseResult parseStopAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 2996 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseVerifAttrs()
static ParseResult parseVerifAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 3005 of file FIRRTLOps.cpp.
References parseElideEmptyName().
printCircuitOpAttrs()
static void printCircuitOpAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 213 of file FIRRTLOps.cpp.
printConstantOp()
static void printConstantOp (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 1924 of file FIRRTLOps.cpp.
printElideAnnotations()
static void printElideAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 2803 of file FIRRTLOps.cpp.
Referenced by printMemoryPortOp().
printElideEmptyName()
static void printElideEmptyName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 2975 of file FIRRTLOps.cpp.
Referenced by printPrintfAttrs(), printStopAttrs(), and printVerifAttrs().
printElidePortAnnotations()
static void printElidePortAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 2830 of file FIRRTLOps.cpp.
Referenced by printMemOp().
printFExtModuleOp()
static void printFExtModuleOp (OpAsmPrinter & p, FExtModuleOp op) static
Definition at line 766 of file FIRRTLOps.cpp.
References printFModuleLikeOp().
printFModuleLikeOp()
static void printFModuleLikeOp (OpAsmPrinter & p, FModuleLike op) static
Definition at line 734 of file FIRRTLOps.cpp.
References printModulePorts(), and circt::firrtl::direction::unpackAttribute().
Referenced by printFExtModuleOp(), and printFModuleOp().
printFModuleOp()
static void printFModuleOp (OpAsmPrinter & p, FModuleOp op) static
Definition at line 770 of file FIRRTLOps.cpp.
References printFModuleLikeOp().
printImplicitSSAName()
static void printImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 2865 of file FIRRTLOps.cpp.
Referenced by printSeqMemOp().
printInstanceOp()
static void printInstanceOp (OpAsmPrinter & p, InstanceOp & op) static
Definition at line 1191 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), printModulePorts(), and circt::firrtl::direction::unpackAttribute().
printMemOp()
static void printMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Definition at line 2957 of file FIRRTLOps.cpp.
References printElidePortAnnotations().
printMemoryPortOp()
static void printMemoryPortOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "direction" and elide "annotations" if it exists or if it is empty.
Definition at line 2908 of file FIRRTLOps.cpp.
References printElideAnnotations().
printModulePorts()
static bool printModulePorts (OpAsmPrinter & p, Block * block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms) static
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
When there is no block specified, the port names print as MLIR identifiers, wrapping in quotes if not legal to print as-is. When there is no block specified, this function always return false, indicating that there was no issue printing port names.
If there is a block specified, then port names will be printed as SSA values. If there is a reason the printed SSA values can't match the true port name, then this function will return true. When this happens, the caller should print the port names as a part of the attr-dict.
Definition at line 594 of file FIRRTLOps.cpp.
Referenced by printFModuleLikeOp(), and printInstanceOp().
printPrintfAttrs()
static void printPrintfAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 2991 of file FIRRTLOps.cpp.
References printElideEmptyName().
printSeqMemOp()
static void printSeqMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Definition at line 2924 of file FIRRTLOps.cpp.
References printImplicitSSAName().
printSpecialConstantOp()
static void printSpecialConstantOp (OpAsmPrinter & p, SpecialConstantOp & op) static
Definition at line 2015 of file FIRRTLOps.cpp.
printStopAttrs()
static void printStopAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 3000 of file FIRRTLOps.cpp.
References printElideEmptyName().
printVerifAttrs()
static void printVerifAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 3009 of file FIRRTLOps.cpp.
References printElideEmptyName().
removeElementsAtIndices()
template<typename T > static SmallVector<T> removeElementsAtIndices (ArrayRef< T > input, ArrayRef< unsigned > indicesToDrop) static
Remove elements at the specified indices from the input array, returning the elements not mentioned.
The indices array is expected to be sorted and unique.
Definition at line 46 of file FIRRTLOps.cpp.
verifyBitCastOp()
static LogicalResult verifyBitCastOp (BitCastOp cast) static
Definition at line 2768 of file FIRRTLOps.cpp.
References circt::firrtl::getBitWidth().
verifyCircuitOp()
static LogicalResult verifyCircuitOp (CircuitOp circuit) static
Definition at line 225 of file FIRRTLOps.cpp.
References circt::firrtl::FIRRTLType::getWidthlessType().
verifyConnectOp()
static LogicalResult verifyConnectOp (ConnectOp connect) static
Definition at line 1761 of file FIRRTLOps.cpp.
References circt::firrtl::areTypesEquivalent(), circt.support::connect(), circt::firrtl::foldFlow(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), circt::firrtl::getDeclarationKind(), circt::firrtl::FIRRTLType::getPassiveType(), circt::firrtl::Instance, circt::firrtl::Port, circt::firrtl::Sink, and circt::firrtl::Source.
verifyConstantOp()
static LogicalResult verifyConstantOp (ConstantOp constant) static
Definition at line 1974 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::getWidthOrSentinel().
verifyFExtModuleOp()
static LogicalResult verifyFExtModuleOp (FExtModuleOp op) static
Definition at line 881 of file FIRRTLOps.cpp.
verifyHWStructCastOp()
static LogicalResult verifyHWStructCastOp (HWStructCastOp cast) static
Definition at line 2730 of file FIRRTLOps.cpp.
References circt::hw::getBitWidth(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), and circt::firrtl::BundleType::getElements().
verifyInstanceOp()
static LogicalResult verifyInstanceOp (InstanceOp instance) static
Verify the correctness of an InstanceOp.
Definition at line 1179 of file FIRRTLOps.cpp.
verifyMemOp()
static LogicalResult verifyMemOp (MemOp mem) static
Verify the correctness of a MemOp.
Definition at line 1393 of file FIRRTLOps.cpp.
References circt::firrtl::FIRRTLType::containsAnalog(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), circt::firrtl::BundleType::getElement(), circt::firrtl::FIRRTLType::isGround(), and circt::firrtl::FIRRTLType::isPassive().
verifyMemoryPortOp()
static LogicalResult verifyMemoryPortOp (MemoryPortOp memoryPort) static
Definition at line 1312 of file FIRRTLOps.cpp.
verifyPartialConnectOp()
static LogicalResult verifyPartialConnectOp (PartialConnectOp partialConnect) static
Definition at line 1815 of file FIRRTLOps.cpp.
References circt::firrtl::areTypesWeaklyEquivalent(), circt::firrtl::foldFlow(), circt::firrtl::getDeclarationKind(), circt::firrtl::Instance, circt::firrtl::Port, circt::firrtl::Sink, and circt::firrtl::Source.
verifySubfieldOp()
static LogicalResult verifySubfieldOp (SubfieldOp op) static
Definition at line 2051 of file FIRRTLOps.cpp.
References circt::firrtl::BundleType::getNumElements().