CIRCT: lib/Dialect/FSM/FSMOps.cpp File Reference
FSMOps.cpp File Reference
#include "circt/Dialect/FSM/FSMOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "circt/Dialect/FSM/FSM.cpp.inc"
#include "circt/Dialect/FSM/FSMDialect.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static ParseResult parseMachineOp (OpAsmParser &parser, OperationState &result)
static void print (MachineOp op, OpAsmPrinter &p)
static LogicalResult compareTypes (TypeRange rangeA, TypeRange rangeB)
static LogicalResult verifyMachineOp (MachineOp op)
static LogicalResult verifyInstanceOp (InstanceOp op)
template<typename OpType >
static LogicalResult verifyCallerTypes (OpType op)
static LogicalResult verifyTriggerOp (TriggerOp op)
static LogicalResult verifyHWInstanceOp (HWInstanceOp op)
static LogicalResult verifyOutputOp (OutputOp op)
static LogicalResult verifyTransitionOp (TransitionOp op)
static LogicalResult verifyUpdateOp (UpdateOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 347 of file FSMOps.cpp.
Function Documentation
compareTypes()
static LogicalResult compareTypes (TypeRange rangeA, TypeRange rangeB) static
Definition at line 87 of file FSMOps.cpp.
Referenced by verifyCallerTypes(), verifyMachineOp(), and verifyOutputOp().
parseMachineOp()
static ParseResult parseMachineOp (OpAsmParser & parser, OperationState & result) static
Definition at line 70 of file FSMOps.cpp.
print()
static void print (MachineOp op, OpAsmPrinter & p) static
Definition at line 81 of file FSMOps.cpp.
Referenced by setup.CMakeBuild::run().
verifyCallerTypes()
template<typename OpType > static LogicalResult verifyCallerTypes (OpType op) static
Definition at line 153 of file FSMOps.cpp.
References compareTypes().
Referenced by verifyHWInstanceOp(), and verifyTriggerOp().
verifyHWInstanceOp()
static LogicalResult verifyHWInstanceOp (HWInstanceOp op) static
Definition at line 202 of file FSMOps.cpp.
References verifyCallerTypes().
verifyInstanceOp()
static LogicalResult verifyInstanceOp (InstanceOp op) static
Definition at line 134 of file FSMOps.cpp.
verifyMachineOp()
static LogicalResult verifyMachineOp (MachineOp op) static
Definition at line 101 of file FSMOps.cpp.
References compareTypes().
verifyOutputOp()
static LogicalResult verifyOutputOp (OutputOp op) static
Definition at line 231 of file FSMOps.cpp.
References compareTypes().
verifyTransitionOp()
static LogicalResult verifyTransitionOp (TransitionOp op) static
Definition at line 297 of file FSMOps.cpp.
verifyTriggerOp()
static LogicalResult verifyTriggerOp (TriggerOp op) static
Definition at line 188 of file FSMOps.cpp.
References verifyCallerTypes().
verifyUpdateOp()
static LogicalResult verifyUpdateOp (UpdateOp op) static
Definition at line 331 of file FSMOps.cpp.