CIRCT: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp File Reference
GrandCentralTaps.cpp File Reference
#include "../AnnotationDetails.h"
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/InstanceGraph.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
Classes
struct llvm::PointerLikeTypeTraits< InstanceOp >
struct Port
A tapped port, described as the module/extmodule operation and the port number.
class GrandCentralTapsPass
Namespaces
llvm
Macros
#define DEBUG_TYPE "gct"
Typedefs
using Key = std::pair< Attribute, Attribute >
A reference data tap key, identified by the annotation id and port id.
Functions
static InstancePath stripCommonPrefix (InstancePath path, InstancePath other)
Return a version of path that skips all front instances it has in common with other.
template<typename T >
static T & operator<< (T &os, Key key)
static bool isReferenceDataTapOfType (Annotation anno, StringRef type)
Check if an annotation is a ReferenceDataTapKey, and that it has a type field with a given content.
static bool isReferenceDataTapSource (Annotation anno)
Check if an annotation is a ReferenceDataTapKey with source type.
static bool isReferenceDataTapPortName (Annotation anno)
Check if an annotation is a ReferenceDataTapKey with portName type.
static Key getKey (Annotation anno)
Map an annotation to a Key.
static FailureOr< Literal > parseIntegerLiteral (MLIRContext *context, StringRef literal, Location loc)
Parse a FIRRTL UInt/SInt literal.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gct"
Definition at line 33 of file GrandCentralTaps.cpp.
Typedef Documentation
Key
using Key = std::pair<Attribute, Attribute>
A reference data tap key, identified by the annotation id and port id.
Definition at line 123 of file GrandCentralTaps.cpp.
Function Documentation
getKey()
static Key getKey (Annotation anno) static
Map an annotation to a Key.
Definition at line 160 of file GrandCentralTaps.cpp.
References circt::firrtl::Annotation::getMember().
Referenced by GrandCentralTapsPass::gatherTap(), and GrandCentralTapsPass::processAnnotation().
isReferenceDataTapOfType()
static bool isReferenceDataTapOfType (Annotation anno, StringRef type) static
Check if an annotation is a ReferenceDataTapKey, and that it has a type field with a given content.
Definition at line 140 of file GrandCentralTaps.cpp.
References circt::firrtl::Annotation::getMember(), circt::firrtl::Annotation::isClass(), and circt::firrtl::referenceKeyClass.
Referenced by isReferenceDataTapPortName(), and isReferenceDataTapSource().
isReferenceDataTapPortName()
static bool isReferenceDataTapPortName (Annotation anno) static
Check if an annotation is a ReferenceDataTapKey with portName type.
Definition at line 155 of file GrandCentralTaps.cpp.
References isReferenceDataTapOfType().
Referenced by GrandCentralTapsPass::runOnOperation().
isReferenceDataTapSource()
static bool isReferenceDataTapSource (Annotation anno) static
Check if an annotation is a ReferenceDataTapKey with source type.
Definition at line 150 of file GrandCentralTaps.cpp.
References isReferenceDataTapOfType().
Referenced by GrandCentralTapsPass::gatherAnnotations().
operator<<()
template<typename T > static T& operator<< (T & os, Key key) static
Definition at line 134 of file GrandCentralTaps.cpp.
parseIntegerLiteral()
static FailureOr<Literal> parseIntegerLiteral (MLIRContext * context, StringRef literal, Location loc) static
Parse a FIRRTL UInt/SInt literal.
Definition at line 167 of file GrandCentralTaps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::IntType::get().
Referenced by GrandCentralTapsPass::processAnnotation().
stripCommonPrefix()
static InstancePath stripCommonPrefix (InstancePath path, InstancePath other) static
Return a version of path that skips all front instances it has in common with other.
Definition at line 114 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::runOnOperation().