CIRCT: lib/Dialect/Handshake/HandshakeOps.cpp File Reference
HandshakeOps.cpp File Reference
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Value.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include <set>
#include "circt/Dialect/Handshake/HandshakeCanonicalization.h.inc"
#include "circt/Dialect/Handshake/Handshake.cpp.inc"
Namespaces
circt
circt::handshake
sost
Macros
#define GET_OP_CLASSES
Functions
static std::string defaultOperandName (unsigned int idx)
void sost::addAttributes (OperationState &result, int size, Type dataType, bool alwaysControl=false)
static ParseResult sost::parseIntInSquareBrackets (OpAsmParser &parser, int &v)
static ParseResult sost::parseOperation (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operands, OperationState &result, int &size, Type &type, bool explicitSize, bool alwaysControl=false)
static void sost::printOp (OpAsmPrinter &p, Operation *op, bool explicitSize)
static ParseResult parseForkOp (OpAsmParser &parser, OperationState &result)
static void printForkOp (OpAsmPrinter &p, ForkOp op)
static ParseResult parseLazyForkOp (OpAsmParser &parser, OperationState &result)
static void printLazyForkOp (OpAsmPrinter &p, LazyForkOp op)
static ParseResult parseMergeOp (OpAsmParser &parser, OperationState &result)
void printMergeOp (OpAsmPrinter &p, MergeOp op)
static ParseResult parseMuxOp (OpAsmParser &parser, OperationState &result)
static void printMuxOp (OpAsmPrinter &p, MuxOp op)
static LogicalResult verify (MuxOp op)
static ParseResult parseControlMergeOp (OpAsmParser &parser, OperationState &result)
void printControlMergeOp (OpAsmPrinter &p, ControlMergeOp op)
static ParseResult verifyFuncOp (handshake::FuncOp op)
static ParseResult parseFuncOpArgs (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &entryArgs, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< Attribute > &argNames, SmallVectorImpl< NamedAttrList > &argAttrs, SmallVectorImpl< Type > &resTypes, SmallVectorImpl< NamedAttrList > &resAttrs)
Parses a FuncOp signature using mlir::function_like_impl::parseFunctionSignature while getting access to the parsed SSA names to store as attributes.
static SmallVector< Attribute > getFuncOpNames (Builder &builder, TypeRange types, StringRef prefix)
Generates names for a handshake.func input and output arguments, based on the number of args as well as a prefix.
static void addStringToStringArrayAttr (Builder &builder, Operation *op, StringRef attrName, StringAttr str)
Helper function for appending a string to an array attribute, and rewriting the attribute back to the operation.
static ParseResult parseFuncOp (OpAsmParser &parser, OperationState &result)
static void printFuncOp (OpAsmPrinter &p, handshake::FuncOp op)
static ParseResult parseBranchOp (OpAsmParser &parser, OperationState &result)
static void printBranchOp (OpAsmPrinter &p, BranchOp op)
static ParseResult parseConditionalBranchOp (OpAsmParser &parser, OperationState &result)
static void printConditionalBranchOp (OpAsmPrinter &p, ConditionalBranchOp op)
static ParseResult parseSinkOp (OpAsmParser &parser, OperationState &result)
static void printSinkOp (OpAsmPrinter &p, SinkOp op)
static ParseResult parseBufferOp (OpAsmParser &parser, OperationState &result)
static void printBufferOp (OpAsmPrinter &p, BufferOp op)
static std::string getMemoryOperandName (unsigned nStores, unsigned idx)
static std::string getMemoryResultName (unsigned nLoads, unsigned nStores, unsigned idx)
static LogicalResult verifyMemoryOp (handshake::MemoryOp op)
static ParseResult parseMemoryAccessOp (OpAsmParser &parser, OperationState &result)
template<typename MemOp >
static void printMemoryAccessOp (OpAsmPrinter &p, MemOp op)
static ParseResult parseLoadOp (OpAsmParser &parser, OperationState &result)
void printLoadOp (OpAsmPrinter &p, LoadOp op)
template<typename TMemoryOp >
static LogicalResult verifyMemoryAccessOp (TMemoryOp op)
static LogicalResult verifyLoadOp (handshake::LoadOp op)
static LogicalResult verifyStoreOp (handshake::StoreOp op)
static ParseResult parseStoreOp (OpAsmParser &parser, OperationState &result)
static void printStoreOp (OpAsmPrinter &p, StoreOp &op)
static ParseResult parseJoinOp (OpAsmParser &parser, OperationState &result)
void printJoinOp (OpAsmPrinter &p, JoinOp op)
static LogicalResult verifyInstanceOp (handshake::InstanceOp op)
static LogicalResult verify (handshake::ReturnOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1235 of file HandshakeOps.cpp.
Function Documentation
addStringToStringArrayAttr()
static void addStringToStringArrayAttr (Builder & builder, Operation * op, StringRef attrName, StringAttr str) static
Helper function for appending a string to an array attribute, and rewriting the attribute back to the operation.
Definition at line 486 of file HandshakeOps.cpp.
defaultOperandName()
static std::string defaultOperandName (unsigned int idx) static
Definition at line 41 of file HandshakeOps.cpp.
getFuncOpNames()
static SmallVector<Attribute> getFuncOpNames (Builder & builder, TypeRange types, StringRef prefix) static
Generates names for a handshake.func input and output arguments, based on the number of args as well as a prefix.
Definition at line 449 of file HandshakeOps.cpp.
References circt::esi::types.
Referenced by parseFuncOp().
getMemoryOperandName()
static std::string getMemoryOperandName (unsigned nStores, unsigned idx) static
Definition at line 820 of file HandshakeOps.cpp.
getMemoryResultName()
static std::string getMemoryResultName (unsigned nLoads, unsigned nStores, unsigned idx) static
Definition at line 837 of file HandshakeOps.cpp.
parseBranchOp()
static ParseResult parseBranchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 636 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseBufferOp()
static ParseResult parseBufferOp (OpAsmParser & parser, OperationState & result) static
Definition at line 800 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseConditionalBranchOp()
static ParseResult parseConditionalBranchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 659 of file HandshakeOps.cpp.
References circt::calyx::direction::get().
parseControlMergeOp()
static ParseResult parseControlMergeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 350 of file HandshakeOps.cpp.
References circt::calyx::direction::get(), sost::parseOperation(), and size().
parseForkOp()
static ParseResult parseForkOp (OpAsmParser & parser, OperationState & result) static
Definition at line 117 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
Referenced by parseLazyForkOp().
parseFuncOp()
static ParseResult parseFuncOp (OpAsmParser & parser, OperationState & result) static
Definition at line 520 of file HandshakeOps.cpp.
References circt::calyx::direction::get(), getFuncOpNames(), and parseFuncOpArgs().
parseFuncOpArgs()
static ParseResult parseFuncOpArgs (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & entryArgs, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< Attribute > & argNames, SmallVectorImpl< NamedAttrList > & argAttrs, SmallVectorImpl< Type > & resTypes, SmallVectorImpl< NamedAttrList > & resAttrs) static
Parses a FuncOp signature using mlir::function_like_impl::parseFunctionSignature while getting access to the parsed SSA names to store as attributes.
Definition at line 426 of file HandshakeOps.cpp.
References circt::calyx::direction::get().
Referenced by parseFuncOp().
parseJoinOp()
static ParseResult parseJoinOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1177 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseLazyForkOp()
static ParseResult parseLazyForkOp (OpAsmParser & parser, OperationState & result) static
Definition at line 199 of file HandshakeOps.cpp.
References parseForkOp().
parseLoadOp()
static ParseResult parseLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1101 of file HandshakeOps.cpp.
References parseMemoryAccessOp().
parseMemoryAccessOp()
static ParseResult parseMemoryAccessOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1064 of file HandshakeOps.cpp.
References circt::calyx::direction::get().
Referenced by parseLoadOp(), and parseStoreOp().
parseMergeOp()
static ParseResult parseMergeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 218 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseMuxOp()
static ParseResult parseMuxOp (OpAsmParser & parser, OperationState & result) static
Definition at line 262 of file HandshakeOps.cpp.
References sost::addAttributes(), and size().
parseSinkOp()
static ParseResult parseSinkOp (OpAsmParser & parser, OperationState & result) static
Definition at line 745 of file HandshakeOps.cpp.
References sost::parseOperation(), and size().
parseStoreOp()
static ParseResult parseStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1160 of file HandshakeOps.cpp.
References parseMemoryAccessOp().
printBranchOp()
static void printBranchOp (OpAsmPrinter & p, BranchOp op) static
Definition at line 655 of file HandshakeOps.cpp.
References sost::printOp().
printBufferOp()
static void printBufferOp (OpAsmPrinter & p, BufferOp op) static
Definition at line 816 of file HandshakeOps.cpp.
References sost::printOp().
printConditionalBranchOp()
static void printConditionalBranchOp (OpAsmPrinter & p, ConditionalBranchOp op) static
Definition at line 687 of file HandshakeOps.cpp.
printControlMergeOp()
void printControlMergeOp (OpAsmPrinter & p, ControlMergeOp op)
Definition at line 372 of file HandshakeOps.cpp.
References sost::printOp().
printForkOp()
static void printForkOp (OpAsmPrinter & p, ForkOp op) static
Definition at line 136 of file HandshakeOps.cpp.
References sost::printOp().
printFuncOp()
static void printFuncOp (OpAsmPrinter & p, handshake::FuncOp op) static
Definition at line 560 of file HandshakeOps.cpp.
printJoinOp()
void printJoinOp (OpAsmPrinter & p, JoinOp op)
Definition at line 1195 of file HandshakeOps.cpp.
References sost::printOp().
printLazyForkOp()
static void printLazyForkOp (OpAsmPrinter & p, LazyForkOp op) static
Definition at line 204 of file HandshakeOps.cpp.
References sost::printOp().
printLoadOp()
void printLoadOp (OpAsmPrinter & p, LoadOp op)
Definition at line 1105 of file HandshakeOps.cpp.
References printMemoryAccessOp().
printMemoryAccessOp()
template<typename MemOp > static void printMemoryAccessOp (OpAsmPrinter & p, MemOp op) static
Definition at line 1093 of file HandshakeOps.cpp.
Referenced by printLoadOp(), and printStoreOp().
printMergeOp()
void printMergeOp (OpAsmPrinter & p, MergeOp op)
Definition at line 237 of file HandshakeOps.cpp.
References sost::printOp().
printMuxOp()
static void printMuxOp (OpAsmPrinter & p, MuxOp op) static
Definition at line 289 of file HandshakeOps.cpp.
printSinkOp()
static void printSinkOp (OpAsmPrinter & p, SinkOp op) static
Definition at line 760 of file HandshakeOps.cpp.
References sost::printOp().
printStoreOp()
static void printStoreOp (OpAsmPrinter & p, StoreOp & op) static
Definition at line 1164 of file HandshakeOps.cpp.
References printMemoryAccessOp().
verify() [1/2]
static LogicalResult verify (handshake::ReturnOp op) static
Definition at line 1212 of file HandshakeOps.cpp.
verify() [2/2]
static LogicalResult verify (MuxOp op) static
Definition at line 301 of file HandshakeOps.cpp.
verifyFuncOp()
static ParseResult verifyFuncOp (handshake::FuncOp op) static
Definition at line 376 of file HandshakeOps.cpp.
verifyInstanceOp()
static LogicalResult verifyInstanceOp (handshake::InstanceOp op) static
Definition at line 1197 of file HandshakeOps.cpp.
verifyLoadOp()
static LogicalResult verifyLoadOp (handshake::LoadOp op) static
Definition at line 1127 of file HandshakeOps.cpp.
References verifyMemoryAccessOp().
verifyMemoryAccessOp()
template<typename TMemoryOp > static LogicalResult verifyMemoryAccessOp (TMemoryOp op) static
Definition at line 1120 of file HandshakeOps.cpp.
Referenced by verifyLoadOp(), and verifyStoreOp().
verifyMemoryOp()
static LogicalResult verifyMemoryOp (handshake::MemoryOp op) static
Definition at line 853 of file HandshakeOps.cpp.
verifyStoreOp()
static LogicalResult verifyStoreOp (handshake::StoreOp op) static
Definition at line 1156 of file HandshakeOps.cpp.
References verifyMemoryAccessOp().