CIRCT: lib/Dialect/Handshake/HandshakeExecutableOps.cpp File Reference
HandshakeExecutableOps.cpp File Reference
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "mlir/IR/Value.h"
#include "llvm/ADT/Any.h"
#include "llvm/Support/Debug.h"
Namespaces
circt
circt::handshake
Macros
#define INDEX_WIDTH 32
Functions
static std::vector< mlir::Value > toVector (mlir::ValueRange range)
static bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static std::vector< llvm::Any > fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static void storeValues (std::vector< llvm::Any > &values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > &timeMap, double latency)
static bool tryToExecute (Operation *op, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< mlir::Value > &scheduleList, double latency)
template<typename TMemOp >
static bool circt::handshake::executeMemoryOperation (TMemOp op, unsigned buffer, int opIndex, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< unsigned, unsigned > &memoryMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< std::vector< llvm::Any >> &store, std::vector< mlir::Value > &scheduleList)
Macro Definition Documentation
INDEX_WIDTH
#define INDEX_WIDTH 32
Definition at line 22 of file HandshakeExecutableOps.cpp.
Function Documentation
fetchValues()
static std::vector<llvm::Any> fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 46 of file HandshakeExecutableOps.cpp.
Referenced by tryToExecute().
isReadyToExecute()
static bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 30 of file HandshakeExecutableOps.cpp.
Referenced by tryToExecute().
storeValues()
static void storeValues (std::vector< llvm::Any > & values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 58 of file HandshakeExecutableOps.cpp.
Referenced by tryToExecute().
toVector()
static std::vector<mlir::Value> toVector (mlir::ValueRange range) static
Definition at line 25 of file HandshakeExecutableOps.cpp.
Referenced by GrandCentralTapsPass::processAnnotation(), GrandCentralTapsPass::runOnOperation(), and tryToExecute().
tryToExecute()
static bool tryToExecute (Operation * op, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap, llvm::DenseMap< mlir::Value, double > & timeMap, std::vector< mlir::Value > & scheduleList, double latency) static
Definition at line 78 of file HandshakeExecutableOps.cpp.
References fetchValues(), isReadyToExecute(), storeValues(), toVector(), and updateTime().
updateTime()
static void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > & timeMap, double latency) static
Definition at line 67 of file HandshakeExecutableOps.cpp.
Referenced by tryToExecute().