CIRCT: lib/Dialect/HW/HWAttributes.cpp File Reference
HWAttributes.cpp File Reference
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWDialect.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "circt/Dialect/HW/HWAttributes.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_LIST
Functions
static Attribute parseParamExprWithOpcode (StringRef opcodeStr, DialectAsmParser &p, Type type)
Internal method used for .mlir file parsing when parsing the "#hw.param.expr.mul" form of the attribute.
static std::string canonicalizeFilename (const Twine &directory, const Twine &filename)
static Attribute foldBinaryOp (ArrayRef< Attribute > operands, llvm::function_ref< APInt(const APInt &, const APInt &)> calculate)
Given a binary function, if the two operands are known constant integers, use the specified fold function to compute the result.
static ParamExprAttr dyn_castPE (PEO opcode, Attribute value)
If the specified attribute is a ParamExprAttr with the specified opcode, return it.
static bool paramExprOperandSortPredicate (Attribute lhs, Attribute rhs)
This implements a < comparison for two operands to an associative operation imposing an ordering upon them.
static Attribute simplifyAssocOp (PEO opcode, SmallVector< Attribute, 4 > &operands, llvm::function_ref< APInt(const APInt &, const APInt &)> calculateFn, llvm::function_ref< bool(const APInt &)> identityConstantFn, llvm::function_ref< bool(const APInt &)> destructiveConstantFn={})
Given a fully associative variadic integer operation, constant fold any constant operands and move them to the right.
static std::pair< Attribute, Attribute > decomposeAddend (Attribute operand)
Analyze an operand to an add.
static Attribute getOneOfType (Type type)
static Attribute simplifyAdd (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyMul (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyAnd (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyOr (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyXor (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyShl (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyShrU (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyShrS (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyDivU (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyDivS (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyModU (SmallVector< Attribute, 4 > &operands)
static Attribute simplifyModS (SmallVector< Attribute, 4 > &operands)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 31 of file HWAttributes.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
Function Documentation
canonicalizeFilename()
static std::string canonicalizeFilename (const Twine & directory, const Twine & filename) static
Definition at line 71 of file HWAttributes.cpp.
decomposeAddend()
static std::pair<Attribute, Attribute> decomposeAddend (Attribute operand) static
Analyze an operand to an add.
If it is a multiplication by a constant (e.g. (a*b*42) then split it into the non-constant and the constant portions (e.g. a*b and 42). Otherwise return the operand as the first value and null as the second (standin for "multiplication by 1").
Definition at line 412 of file HWAttributes.cpp.
References dyn_castPE(), and circt::calyx::direction::get().
Referenced by simplifyAdd().
dyn_castPE()
static ParamExprAttr dyn_castPE (PEO opcode, Attribute value) static
If the specified attribute is a ParamExprAttr with the specified opcode, return it.
Otherwise return null.
Definition at line 275 of file HWAttributes.cpp.
Referenced by decomposeAddend(), and simplifyMul().
foldBinaryOp()
static Attribute foldBinaryOp (ArrayRef< Attribute > operands, llvm::function_ref< APInt(const APInt &, const APInt &)> calculate) static
Given a binary function, if the two operands are known constant integers, use the specified fold function to compute the result.
Definition at line 262 of file HWAttributes.cpp.
References circt::calyx::direction::get().
Referenced by simplifyDivS(), simplifyDivU(), simplifyModS(), simplifyModU(), simplifyShrS(), and simplifyShrU().
getOneOfType()
static Attribute getOneOfType (Type type) static
Definition at line 421 of file HWAttributes.cpp.
References circt::calyx::direction::get().
Referenced by simplifyAdd().
paramExprOperandSortPredicate()
static bool paramExprOperandSortPredicate (Attribute lhs, Attribute rhs) static
This implements a < comparison for two operands to an associative operation imposing an ordering upon them.
The ordering provided puts more complex things to the start of the list, from left to right: expressions :: verbatims :: decl.refs :: constant
Definition at line 289 of file HWAttributes.cpp.
parseParamExprWithOpcode()
static Attribute parseParamExprWithOpcode (StringRef opcode, DialectAsmParser & p, Type type) static
Internal method used for .mlir file parsing when parsing the "#hw.param.expr.mul" form of the attribute.
Definition at line 647 of file HWAttributes.cpp.
simplifyAdd()
static Attribute simplifyAdd (SmallVector< Attribute, 4 > & operands) static
Definition at line 425 of file HWAttributes.cpp.
References decomposeAddend(), circt::calyx::direction::get(), getOneOfType(), and simplifyAssocOp().
simplifyAnd()
static Attribute simplifyAnd (SmallVector< Attribute, 4 > & operands) static
Definition at line 504 of file HWAttributes.cpp.
References simplifyAssocOp().
simplifyAssocOp()
static Attribute simplifyAssocOp (PEO opcode, SmallVector< Attribute, 4 > & operands, llvm::function_ref< APInt(const APInt &, const APInt &)> calculateFn, llvm::function_ref< bool(const APInt &)> identityConstantFn, llvm::function_ref< bool(const APInt &)> destructiveConstantFn = {}) static
Given a fully associative variadic integer operation, constant fold any constant operands and move them to the right.
If the whole expression is constant, then return that, otherwise update the operands list.
Definition at line 354 of file HWAttributes.cpp.
Referenced by simplifyAdd(), simplifyAnd(), simplifyMul(), simplifyOr(), and simplifyXor().
simplifyDivS()
static Attribute simplifyDivS (SmallVector< Attribute, 4 > & operands) static
Definition at line 561 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyDivU()
static Attribute simplifyDivU (SmallVector< Attribute, 4 > & operands) static
Definition at line 555 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyModS()
static Attribute simplifyModS (SmallVector< Attribute, 4 > & operands) static
Definition at line 573 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyModU()
static Attribute simplifyModU (SmallVector< Attribute, 4 > & operands) static
Definition at line 567 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyMul()
static Attribute simplifyMul (SmallVector< Attribute, 4 > & operands) static
Definition at line 474 of file HWAttributes.cpp.
References dyn_castPE(), circt::calyx::direction::get(), and simplifyAssocOp().
simplifyOr()
static Attribute simplifyOr (SmallVector< Attribute, 4 > & operands) static
Definition at line 511 of file HWAttributes.cpp.
References simplifyAssocOp().
simplifyShl()
static Attribute simplifyShl (SmallVector< Attribute, 4 > & operands) static
Definition at line 524 of file HWAttributes.cpp.
References circt::calyx::direction::get(), and circt::hw::isHWIntegerType().
simplifyShrS()
static Attribute simplifyShrS (SmallVector< Attribute, 4 > & operands) static
Definition at line 549 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyShrU()
static Attribute simplifyShrU (SmallVector< Attribute, 4 > & operands) static
Definition at line 543 of file HWAttributes.cpp.
References foldBinaryOp(), and circt::hw::isHWIntegerType().
simplifyXor()
static Attribute simplifyXor (SmallVector< Attribute, 4 > & operands) static
Definition at line 518 of file HWAttributes.cpp.
References simplifyAssocOp().