CIRCT: lib/Dialect/LLHD/IR/LLHDOps.cpp File Reference
LLHDOps.cpp File Reference
#include "circt/Dialect/LLHD/IR/LLHDOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/LLHD/IR/LLHDDialect.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Region.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "circt/Dialect/LLHD/IR/LLHDEnums.cpp.inc"
#include "circt/Dialect/LLHD/IR/LLHD.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT)>>
static Attribute constFoldUnaryOp (ArrayRef< Attribute > operands, const CalculationT &calculate)
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref< ElementValueT(ElementValueT, ElementValueT, ElementValueT)>>
static Attribute constFoldTernaryOp (ArrayRef< Attribute > operands, const CalculationT &calculate)
static bool sameKindArbitraryWidth (Type lhsType, Type rhsType)
template<class Op >
static OpFoldResult foldSigPtrExtractOp (Op op, ArrayRef< Attribute > operands)
template<class Op >
static OpFoldResult foldSigPtrArraySliceOp (Op op, ArrayRef< Attribute > operands)
template<class Op >
static LogicalResult canonicalizeSigPtrArraySliceOp (Op op, PatternRewriter &rewriter)
template<class Op >
static LogicalResult canonicalizeSigPtrArrayGetOp (Op op, PatternRewriter &rewriter)
template<class SigPtrType >
static LogicalResult inferReturnTypesOfStructExtractOp (MLIRContext *context, Optional< Location > loc, ValueRange operands, DictionaryAttr attrs, mlir::RegionRange regions, SmallVectorImpl< Type > &results)
static ParseResult parseArgumentList (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &args, SmallVectorImpl< Type > &argTypes)
Parse an argument list of an entity operation.
static ParseResult parseEntitySignature (OpAsmParser &parser, OperationState &result, SmallVectorImpl< OpAsmParser::OperandType > &args, SmallVectorImpl< Type > &argTypes)
parse an entity signature with syntax: (arg0 : T0, arg1 : T1, <...>) -> (out0 : T0, out1 : T1, <...>)
static ParseResult parseEntityOp (OpAsmParser &parser, OperationState &result)
static void printArgumentList (OpAsmPrinter &printer, std::vector< BlockArgument > args)
static void printEntityOp (OpAsmPrinter &printer, llhd::EntityOp op)
static LogicalResult verify (llhd::EntityOp op)
static LogicalResult verify (llhd::ProcOp op)
static ParseResult parseProcArgumentList (OpAsmParser &parser, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< OpAsmParser::OperandType > &argNames)
static ParseResult parseProcOp (OpAsmParser &parser, OperationState &result)
static void printProcArguments (OpAsmPrinter &p, Operation *op, ArrayRef< Type > types, uint64_t numIns)
Print the signature of the proc unit.
static void printProcOp (OpAsmPrinter &printer, llhd::ProcOp op)
static LogicalResult verify (llhd::InstOp op)
static ParseResult parseRegOp (OpAsmParser &parser, OperationState &result)
static void printRegOp (OpAsmPrinter &printer, llhd::RegOp op)
static LogicalResult verify (llhd::RegOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1077 of file LLHDOps.cpp.
Function Documentation
canonicalizeSigPtrArrayGetOp()
template<class Op > static LogicalResult canonicalizeSigPtrArrayGetOp (Op op, PatternRewriter & rewriter) static
Definition at line 343 of file LLHDOps.cpp.
canonicalizeSigPtrArraySliceOp()
template<class Op > static LogicalResult canonicalizeSigPtrArraySliceOp (Op op, PatternRewriter & rewriter) static
Definition at line 284 of file LLHDOps.cpp.
constFoldTernaryOp()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref< ElementValueT(ElementValueT, ElementValueT, ElementValueT)>> static Attribute constFoldTernaryOp (ArrayRef< Attribute > operands, const CalculationT & calculate) static
Definition at line 68 of file LLHDOps.cpp.
References circt::calyx::direction::get().
constFoldUnaryOp()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT)>> static Attribute constFoldUnaryOp (ArrayRef< Attribute > operands, const CalculationT & calculate) static
Definition at line 37 of file LLHDOps.cpp.
References circt::calyx::direction::get().
foldSigPtrArraySliceOp()
template<class Op > static OpFoldResult foldSigPtrArraySliceOp (Op op, ArrayRef< Attribute > operands) static
Definition at line 262 of file LLHDOps.cpp.
foldSigPtrExtractOp()
template<class Op > static OpFoldResult foldSigPtrExtractOp (Op op, ArrayRef< Attribute > operands) static
Definition at line 236 of file LLHDOps.cpp.
inferReturnTypesOfStructExtractOp()
template<class SigPtrType > static LogicalResult inferReturnTypesOfStructExtractOp (MLIRContext * context, Optional< Location > loc, ValueRange operands, DictionaryAttr attrs, mlir::RegionRange regions, SmallVectorImpl< Type > & results) static
Definition at line 400 of file LLHDOps.cpp.
References circt::calyx::direction::get().
parseArgumentList()
static ParseResult parseArgumentList (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & args, SmallVectorImpl< Type > & argTypes) static
Parse an argument list of an entity operation.
The argument list and argument types are returned in args and argTypes respectively.
Definition at line 488 of file LLHDOps.cpp.
Referenced by parseEntitySignature().
parseEntityOp()
static ParseResult parseEntityOp (OpAsmParser & parser, OperationState & result) static
Definition at line 524 of file LLHDOps.cpp.
References circt::calyx::direction::get(), and parseEntitySignature().
parseEntitySignature()
static ParseResult parseEntitySignature (OpAsmParser & parser, OperationState & result, SmallVectorImpl< OpAsmParser::OperandType > & args, SmallVectorImpl< Type > & argTypes) static
parse an entity signature with syntax: (arg0 : T0, arg1 : T1, <...>) -> (out0 : T0, out1 : T1, <...>)
Definition at line 510 of file LLHDOps.cpp.
References parseArgumentList().
Referenced by parseEntityOp().
parseProcArgumentList()
static ParseResult parseProcArgumentList (OpAsmParser & parser, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< OpAsmParser::OperandType > & argNames) static
Definition at line 694 of file LLHDOps.cpp.
Referenced by parseProcOp().
parseProcOp()
static ParseResult parseProcOp (OpAsmParser & parser, OperationState & result) static
Definition at line 748 of file LLHDOps.cpp.
References circt::calyx::direction::get(), and parseProcArgumentList().
parseRegOp()
static ParseResult parseRegOp (OpAsmParser & parser, OperationState & result) static
Definition at line 892 of file LLHDOps.cpp.
References circt::calyx::direction::get().
printArgumentList()
static void printArgumentList (OpAsmPrinter & printer, std::vector< BlockArgument > args) static
Definition at line 551 of file LLHDOps.cpp.
Referenced by printEntityOp().
printEntityOp()
static void printEntityOp (OpAsmPrinter & printer, llhd::EntityOp op) static
Definition at line 560 of file LLHDOps.cpp.
References printArgumentList(), and size().
printProcArguments()
static void printProcArguments (OpAsmPrinter & p, Operation * op, ArrayRef< Type > types, uint64_t numIns) static
Print the signature of the proc unit.
Assumes that it passed the verification.
Definition at line 781 of file LLHDOps.cpp.
References circt::esi::types.
Referenced by printProcOp().
printProcOp()
static void printProcOp (OpAsmPrinter & printer, llhd::ProcOp op) static
Definition at line 801 of file LLHDOps.cpp.
References printProcArguments().
printRegOp()
static void printRegOp (OpAsmPrinter & printer, llhd::RegOp op) static
Definition at line 983 of file LLHDOps.cpp.
sameKindArbitraryWidth()
static bool sameKindArbitraryWidth (Type lhsType, Type rhsType) static
Definition at line 157 of file LLHDOps.cpp.
verify() [1/4]
static LogicalResult verify (llhd::EntityOp op) static
Definition at line 588 of file LLHDOps.cpp.
verify() [2/4]
static LogicalResult verify (llhd::InstOp op) static
Definition at line 822 of file LLHDOps.cpp.
verify() [3/4]
static LogicalResult verify (llhd::ProcOp op) static
Definition at line 680 of file LLHDOps.cpp.
verify() [4/4]
static LogicalResult verify (llhd::RegOp op) static
Definition at line 1004 of file LLHDOps.cpp.