CIRCT: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp File Reference
LowerTypes.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/APSInt.h"
Functions
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > &fields)
Peel one layer of an aggregate type into its components.
static bool isNotSubAccess (Operation *op)
Return if something is not a normal subaccess.
static SmallVector< Operation * > getSAWritePath (Operation *op)
Look through and collect subfields leading to a subaccess.
static bool isAnnotationSensitiveToFieldID (Annotation anno)
Returns whether the given annotation requires precise tracking of the field ID as it gets replicated across lowered operations.
static Attribute updateAnnotationFieldID (MLIRContext *ctxt, Attribute attr, unsigned fieldID)
If an annotation on one operation is replicated across multiple IR operations as a result of type lowering, the replicated annotations may want to track which field ID they were applied to.
static ArrayAttr filterAnnotations (MLIRContext *ctxt, ArrayAttr annotations, FIRRTLType srcType, FlatBundleFieldEntry field)
Copy annotations from annotations to loweredAttrs, except annotations with "target" key, that do not match the field suffix.
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder *b, MemOp op, FlatBundleFieldEntry field)
static Value cloneAccess (ImplicitLocOpBuilder *builder, Operation *op, Value rhs)
static bool flattenType (FIRRTLType type, SmallVectorImpl< IntType > &results)
Function Documentation
cloneAccess()
static Value cloneAccess (ImplicitLocOpBuilder * builder, Operation * op, Value rhs) static
Definition at line 489 of file LowerTypes.cpp.
cloneMemWithNewType()
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder * b, MemOp op, FlatBundleFieldEntry field) static
Definition at line 194 of file LowerTypes.cpp.
References circt::calyx::direction::get(), circt::firrtl::BundleType::getElement(), circt::firrtl::BundleType::getFieldID(), and circt::firrtl::BundleType::getIndexForFieldID().
filterAnnotations()
static ArrayAttr filterAnnotations (MLIRContext * ctxt, ArrayAttr annotations, FIRRTLType srcType, FlatBundleFieldEntry field) static
Copy annotations from annotations to loweredAttrs, except annotations with "target" key, that do not match the field suffix.
Definition at line 159 of file LowerTypes.cpp.
References circt::calyx::direction::get(), and updateAnnotationFieldID().
flattenType()
static bool flattenType (FIRRTLType type, SmallVectorImpl< IntType > & results) static
Definition at line 653 of file LowerTypes.cpp.
getSAWritePath()
static SmallVector<Operation *> getSAWritePath (Operation * op) static
Look through and collect subfields leading to a subaccess.
Definition at line 113 of file LowerTypes.cpp.
References isNotSubAccess().
isAnnotationSensitiveToFieldID()
static bool isAnnotationSensitiveToFieldID (Annotation anno) static
Returns whether the given annotation requires precise tracking of the field ID as it gets replicated across lowered operations.
Definition at line 128 of file LowerTypes.cpp.
References circt::firrtl::Annotation::isClass().
Referenced by updateAnnotationFieldID().
isNotSubAccess()
static bool isNotSubAccess (Operation * op) static
Return if something is not a normal subaccess.
Non-normal includes zero-length vectors and constant indexes (which are really subindexes).
Definition at line 102 of file LowerTypes.cpp.
References circt::firrtl::FVectorType::getNumElements().
Referenced by getSAWritePath().
peelType()
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > & fields) static
Peel one layer of an aggregate type into its components.
Type may be complex, but empty, in which case fields is empty, but the return is true.
Definition at line 73 of file LowerTypes.cpp.
updateAnnotationFieldID()
static Attribute updateAnnotationFieldID (MLIRContext * ctxt, Attribute attr, unsigned fieldID) static
If an annotation on one operation is replicated across multiple IR operations as a result of type lowering, the replicated annotations may want to track which field ID they were applied to.
This function adds a fieldID to such a replicated operation, if the annotation in question requires it.
Definition at line 136 of file LowerTypes.cpp.
References circt::calyx::direction::get(), circt::firrtl::Annotation::getMember(), and isAnnotationSensitiveToFieldID().
Referenced by filterAnnotations().