CIRCT: include/circt-c/Dialect/MSFT.h File Reference
MSFT.h File Reference
#include "circt/Dialect/MSFT/MSFTDialect.h"
#include "mlir-c/IR.h"
#include "mlir-c/Pass.h"
#include "mlir-c/Registration.h"
Classes
struct CirctMSFTSwitchInstanceCase
struct CirctMSFTPrimitiveDB
struct CirctMSFTPlacementDB
struct CirctMSFTPlacedInstance
Typedefs
typedef int32_t CirctMSFTPrimitiveType
typedef void(* CirctMSFTPlacementCallback) (MlirAttribute loc, CirctMSFTPlacedInstance, void *userData)
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (MSFT, msft)
MLIR_CAPI_EXPORTED void mlirMSFTRegisterPasses ()
MLIR_CAPI_EXPORTED void mlirMSFTAddPhysLocationAttr (MlirOperation op, const char *entityName, CirctMSFTPrimitiveType type, long x, long y, long num)
Add a physical location attribute with the given entity name, device type, x and y coordinates, and number.
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext, CirctMSFTPrimitiveType, uint64_t x, uint64_t y, uint64_t num)
MLIR_CAPI_EXPORTED CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute)
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute)
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute)
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute)
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsARootedInstancePathAttribute (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTRootedInstancePathAttrGet (MlirContext, MlirAttribute rootSym, MlirAttribute *pathStringAttrs, size_t num)
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsASwitchInstanceAttribute (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTSwitchInstanceAttrGet (MlirContext, CirctMSFTSwitchInstanceCase *listOfCases, size_t numCases)
MLIR_CAPI_EXPORTED size_t circtMSFTSwitchInstanceAttrGetNumCases (MlirAttribute)
MLIR_CAPI_EXPORTED void circtMSFTSwitchInstanceAttrGetCases (MlirAttribute, CirctMSFTSwitchInstanceCase *dstArray, size_t space)
MLIR_CAPI_EXPORTED MlirOperation circtMSFTGetInstance (MlirOperation root, MlirAttribute path)
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext, uint64_t, uint64_t, uint64_t, uint64_t)
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysicalRegionRefAttr (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysicalRegionRefAttrGet (MlirContext, MlirStringRef)
MLIR_CAPI_EXPORTED CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext)
MLIR_CAPI_EXPORTED void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
MLIR_CAPI_EXPORTED MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB, MlirAttribute locAndPrim)
MLIR_CAPI_EXPORTED bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB, MlirAttribute locAndPrim)
MLIR_CAPI_EXPORTED CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirOperation top, CirctMSFTPrimitiveDB seed)
MLIR_CAPI_EXPORTED void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
MLIR_CAPI_EXPORTED size_t circtMSFTPlacementDBAddDesignPlacements (CirctMSFTPlacementDB)
MLIR_CAPI_EXPORTED MlirLogicalResult circtMSFTPlacementDBAddPlacement (CirctMSFTPlacementDB, MlirAttribute loc, CirctMSFTPlacedInstance inst)
MLIR_CAPI_EXPORTED bool circtMSFTPlacementDBTryGetInstanceAt (CirctMSFTPlacementDB, MlirAttribute loc, CirctMSFTPlacedInstance *out)
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB, CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
MLIR_CAPI_EXPORTED void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB, CirctMSFTPlacementCallback, int64_t bounds[4], CirctMSFTPrimitiveType primTypeFilter, void *userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
Typedef Documentation
CirctMSFTPlacementCallback
typedef void(* CirctMSFTPlacementCallback) (MlirAttribute loc, CirctMSFTPlacedInstance, void *userData)
Definition at line 128 of file MSFT.h.
CirctMSFTPrimitiveType
typedef int32_t CirctMSFTPrimitiveType
Definition at line 28 of file MSFT.h.
Function Documentation
circtMSFTAttributeIsAPhysicalBoundsAttr()
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute)
Definition at line 223 of file MSFT.cpp.
circtMSFTAttributeIsAPhysicalRegionRefAttr()
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysicalRegionRefAttr (MlirAttribute)
Definition at line 234 of file MSFT.cpp.
circtMSFTAttributeIsAPhysLocationAttribute()
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute)
Definition at line 144 of file MSFT.cpp.
circtMSFTAttributeIsARootedInstancePathAttribute()
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsARootedInstancePathAttribute (MlirAttribute)
Definition at line 173 of file MSFT.cpp.
circtMSFTAttributeIsASwitchInstanceAttribute()
MLIR_CAPI_EXPORTED bool circtMSFTAttributeIsASwitchInstanceAttribute (MlirAttribute)
Definition at line 188 of file MSFT.cpp.
circtMSFTCreatePlacementDB()
MLIR_CAPI_EXPORTED CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirOperation top, CirctMSFTPrimitiveDB seed)
Definition at line 55 of file MSFT.cpp.
Referenced by PlacementDB::PlacementDB().
circtMSFTCreatePrimitiveDB()
MLIR_CAPI_EXPORTED CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext)
Definition at line 32 of file MSFT.cpp.
Referenced by PrimitiveDB::PrimitiveDB().
circtMSFTDeletePlacementDB()
MLIR_CAPI_EXPORTED void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
Definition at line 61 of file MSFT.cpp.
Referenced by PlacementDB::~PlacementDB().
circtMSFTDeletePrimitiveDB()
MLIR_CAPI_EXPORTED void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
Definition at line 35 of file MSFT.cpp.
Referenced by PrimitiveDB::~PrimitiveDB().
circtMSFTGetInstance()
MLIR_CAPI_EXPORTED MlirOperation circtMSFTGetInstance (MlirOperation root, MlirAttribute path)
Definition at line 246 of file MSFT.cpp.
References circt::msft::getInstance().
circtMSFTPhysicalBoundsAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext , uint64_t , uint64_t , uint64_t , uint64_t)
Definition at line 227 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysicalRegionRefAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysicalRegionRefAttrGet (MlirContext , MlirStringRef)
Definition at line 238 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext , CirctMSFTPrimitiveType , uint64_t x, uint64_t y, uint64_t num)
Definition at line 147 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGetNum()
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute)
Definition at line 169 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetPrimitiveType()
MLIR_CAPI_EXPORTED CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute)
Definition at line 157 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetX()
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute)
Definition at line 163 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetY()
MLIR_CAPI_EXPORTED uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute)
Definition at line 166 of file MSFT.cpp.
circtMSFTPlacementDBAddDesignPlacements()
MLIR_CAPI_EXPORTED size_t circtMSFTPlacementDBAddDesignPlacements (CirctMSFTPlacementDB)
Definition at line 64 of file MSFT.cpp.
Referenced by PlacementDB::addDesignPlacements().
circtMSFTPlacementDBAddPlacement()
MLIR_CAPI_EXPORTED MlirLogicalResult circtMSFTPlacementDBAddPlacement (CirctMSFTPlacementDB , MlirAttribute loc, CirctMSFTPlacedInstance inst)
Definition at line 68 of file MSFT.cpp.
References circt::calyx::direction::get(), CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
Referenced by PlacementDB::addPlacement().
circtMSFTPlacementDBGetNearestFreeInColumn()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB , CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
Definition at line 101 of file MSFT.cpp.
Referenced by PlacementDB::getNearestFreeInColumn().
circtMSFTPlacementDBTryGetInstanceAt()
MLIR_CAPI_EXPORTED bool circtMSFTPlacementDBTryGetInstanceAt (CirctMSFTPlacementDB , MlirAttribute loc, CirctMSFTPlacedInstance * out)
Definition at line 85 of file MSFT.cpp.
References CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
Referenced by PlacementDB::getInstanceAt().
circtMSFTPlacementDBWalkPlacements()
MLIR_CAPI_EXPORTED void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB , CirctMSFTPlacementCallback , int64_t bounds[4], CirctMSFTPrimitiveType primTypeFilter, void * userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
Definition at line 109 of file MSFT.cpp.
References CirctMSFTPlacedInstance::subpath, and circt::msft::PlacementDB::walkPlacements().
Referenced by PlacementDB::walkPlacements().
circtMSFTPrimitiveDBAddPrimitive()
MLIR_CAPI_EXPORTED MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB , MlirAttribute locAndPrim)
Definition at line 38 of file MSFT.cpp.
Referenced by PrimitiveDB::addPrimitive().
circtMSFTPrimitiveDBIsValidLocation()
MLIR_CAPI_EXPORTED bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB , MlirAttribute locAndPrim)
Definition at line 43 of file MSFT.cpp.
Referenced by PrimitiveDB::isValidLocation().
circtMSFTRootedInstancePathAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTRootedInstancePathAttrGet (MlirContext , MlirAttribute rootSym, MlirAttribute * pathStringAttrs, size_t num)
Definition at line 177 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTSwitchInstanceAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtMSFTSwitchInstanceAttrGet (MlirContext , CirctMSFTSwitchInstanceCase * listOfCases, size_t numCases)
Definition at line 192 of file MSFT.cpp.
References CirctMSFTSwitchInstanceCase::attr, circt::calyx::direction::get(), and CirctMSFTSwitchInstanceCase::instance.
circtMSFTSwitchInstanceAttrGetCases()
MLIR_CAPI_EXPORTED void circtMSFTSwitchInstanceAttrGetCases (MlirAttribute , CirctMSFTSwitchInstanceCase * dstArray, size_t space)
Definition at line 211 of file MSFT.cpp.
circtMSFTSwitchInstanceAttrGetNumCases()
MLIR_CAPI_EXPORTED size_t circtMSFTSwitchInstanceAttrGetNumCases (MlirAttribute)
Definition at line 208 of file MSFT.cpp.
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (MSFT , msft)
mlirMSFTAddPhysLocationAttr()
MLIR_CAPI_EXPORTED void mlirMSFTAddPhysLocationAttr (MlirOperation op, const char * entityName, CirctMSFTPrimitiveType type, long x, long y, long num)
Add a physical location attribute with the given entity name, device type, x and y coordinates, and number.
mlirMSFTRegisterPasses()
MLIR_CAPI_EXPORTED void mlirMSFTRegisterPasses ()
Definition at line 24 of file MSFT.cpp.
References circt::msft::registerMSFTPasses().