CIRCT: lib/Dialect/MSFT/MSFTOps.cpp File Reference
MSFTOps.cpp File Reference
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/ModuleImplementation.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/FunctionSupport.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/MSFT/MSFT.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs)
static ParseResult parseMSFTModuleOp (OpAsmParser &parser, OperationState &result)
static void printMSFTModuleOp (OpAsmPrinter &p, MSFTModuleOp mod)
static ParseResult parseParameterList (OpAsmParser &parser, SmallVector< Attribute > &parameters)
Parse an parameter list if present.
static ParseResult parseParameterList (OpAsmParser &parser, ArrayAttr &parameters)
Shim to also use this for the InstanceOp custom parser.
static void printParameterList (OpAsmPrinter &p, Operation *op, ArrayAttr parameters)
Print a parameter list for a module or instance. Same format as HW dialect.
static LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
static ParseResult parseMSFTModuleExternOp (OpAsmParser &parser, OperationState &result)
static void printMSFTModuleExternOp (OpAsmPrinter &p, MSFTModuleExternOp op)
static LogicalResult verifyMSFTModuleExternOp (MSFTModuleExternOp module)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 549 of file MSFTOps.cpp.
Function Documentation
checkParameterInContext()
static LogicalResult checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs) static
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated. Same format as HW dialect.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 302 of file MSFTOps.cpp.
Referenced by verifyMSFTModuleExternOp().
hasAttribute()
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs) static
Definition at line 111 of file MSFTOps.cpp.
Referenced by parseMSFTModuleExternOp(), and parseMSFTModuleOp().
parseMSFTModuleExternOp()
static ParseResult parseMSFTModuleExternOp (OpAsmParser & parser, OperationState & result) static
Definition at line 365 of file MSFTOps.cpp.
References circt::calyx::direction::get(), circt::hw::module_like_impl::getPortNameAttr(), hasAttribute(), circt::hw::module_like_impl::parseModuleFunctionSignature(), and parseParameterList().
parseMSFTModuleOp()
static ParseResult parseMSFTModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 118 of file MSFTOps.cpp.
References circt::calyx::direction::get(), circt::hw::module_like_impl::getPortNameAttr(), hasAttribute(), and circt::hw::module_like_impl::parseModuleFunctionSignature().
parseParameterList() [1/2]
static ParseResult parseParameterList (OpAsmParser & parser, ArrayAttr & parameters) static
Shim to also use this for the InstanceOp custom parser.
Definition at line 267 of file MSFTOps.cpp.
References circt::calyx::direction::get(), and parseParameterList().
parseParameterList() [2/2]
static ParseResult parseParameterList (OpAsmParser & parser, SmallVector< Attribute > & parameters) static
Parse an parameter list if present.
Same format as HW dialect. module-parameter-list ::= < parameter-decl (, parameter-decl)* > parameter-decl ::= identifier : type parameter-decl ::= identifier : type = attribute
Definition at line 240 of file MSFTOps.cpp.
References circt::calyx::direction::get().
Referenced by parseMSFTModuleExternOp(), and parseParameterList().
printMSFTModuleExternOp()
static void printMSFTModuleExternOp (OpAsmPrinter & p, MSFTModuleExternOp op) static
Definition at line 442 of file MSFTOps.cpp.
References circt::hw::module_like_impl::printModuleSignature(), and printParameterList().
printMSFTModuleOp()
static void printMSFTModuleOp (OpAsmPrinter & p, MSFTModuleOp mod) static
Definition at line 199 of file MSFTOps.cpp.
References circt::hw::module_like_impl::printModuleSignature().
printParameterList()
static void printParameterList (OpAsmPrinter & p, Operation * op, ArrayAttr parameters) static
Print a parameter list for a module or instance. Same format as HW dialect.
Definition at line 279 of file MSFTOps.cpp.
Referenced by printMSFTModuleExternOp().
verifyMSFTModuleExternOp()
static LogicalResult verifyMSFTModuleExternOp (MSFTModuleExternOp module) static
Definition at line 471 of file MSFTOps.cpp.
References checkParameterInContext().