CIRCT: lib/CAPI/Dialect/MSFT.cpp File Reference
MSFT.cpp File Reference
#include "circt-c/Dialect/MSFT.h"
#include "circt/Dialect/MSFT/DeviceDB.h"
#include "circt/Dialect/MSFT/ExportTcl.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "circt/Dialect/MSFT/MSFTDialect.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/raw_ostream.h"
Functions
void mlirMSFTRegisterPasses ()
CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext ctxt)
void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirOperation top, CirctMSFTPrimitiveDB seed)
void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
size_t circtMSFTPlacementDBAddDesignPlacements (CirctMSFTPlacementDB self)
MlirLogicalResult circtMSFTPlacementDBAddPlacement (CirctMSFTPlacementDB self, MlirAttribute cLoc, CirctMSFTPlacedInstance cInst)
bool circtMSFTPlacementDBTryGetInstanceAt (CirctMSFTPlacementDB self, MlirAttribute cLoc, CirctMSFTPlacedInstance *out)
MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB cdb, CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB cdb, CirctMSFTPlacementCallback ccb, int64_t bounds[4], CirctMSFTPrimitiveType cPrimTypeFilter, void *userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
void mlirMSFTAddPhysLocationAttr (MlirOperation cOp, const char *entityName, PrimitiveType type, long x, long y, long num)
bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute attr)
MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext cCtxt, CirctMSFTPrimitiveType devType, uint64_t x, uint64_t y, uint64_t num)
CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute attr)
uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute attr)
bool circtMSFTAttributeIsARootedInstancePathAttribute (MlirAttribute cAttr)
MlirAttribute circtMSFTRootedInstancePathAttrGet (MlirContext cCtxt, MlirAttribute cRootSym, MlirAttribute *cPathStringAttrs, size_t num)
bool circtMSFTAttributeIsASwitchInstanceAttribute (MlirAttribute attr)
MlirAttribute circtMSFTSwitchInstanceAttrGet (MlirContext cCtxt, CirctMSFTSwitchInstanceCase *listOfCases, size_t numCases)
size_t circtMSFTSwitchInstanceAttrGetNumCases (MlirAttribute attr)
void circtMSFTSwitchInstanceAttrGetCases (MlirAttribute attr, CirctMSFTSwitchInstanceCase *dstArray, size_t space)
bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute attr)
MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext cContext, uint64_t xMin, uint64_t xMax, uint64_t yMin, uint64_t yMax)
bool circtMSFTAttributeIsAPhysicalRegionRefAttr (MlirAttribute attr)
MlirAttribute circtMSFTPhysicalRegionRefAttrGet (MlirContext cContext, MlirStringRef cName)
MlirOperation circtMSFTGetInstance (MlirOperation cRoot, MlirAttribute cPath)
Function Documentation
circtMSFTAttributeIsAPhysicalBoundsAttr()
bool circtMSFTAttributeIsAPhysicalBoundsAttr (MlirAttribute attr)
Definition at line 223 of file MSFT.cpp.
circtMSFTAttributeIsAPhysicalRegionRefAttr()
bool circtMSFTAttributeIsAPhysicalRegionRefAttr (MlirAttribute attr)
Definition at line 234 of file MSFT.cpp.
circtMSFTAttributeIsAPhysLocationAttribute()
bool circtMSFTAttributeIsAPhysLocationAttribute (MlirAttribute attr)
Definition at line 144 of file MSFT.cpp.
circtMSFTAttributeIsARootedInstancePathAttribute()
bool circtMSFTAttributeIsARootedInstancePathAttribute (MlirAttribute cAttr)
Definition at line 173 of file MSFT.cpp.
circtMSFTAttributeIsASwitchInstanceAttribute()
bool circtMSFTAttributeIsASwitchInstanceAttribute (MlirAttribute attr)
Definition at line 188 of file MSFT.cpp.
circtMSFTCreatePlacementDB()
CirctMSFTPlacementDB circtMSFTCreatePlacementDB (MlirOperation top, CirctMSFTPrimitiveDB seed)
Definition at line 55 of file MSFT.cpp.
Referenced by PlacementDB::PlacementDB().
circtMSFTCreatePrimitiveDB()
CirctMSFTPrimitiveDB circtMSFTCreatePrimitiveDB (MlirContext ctxt)
Definition at line 32 of file MSFT.cpp.
Referenced by PrimitiveDB::PrimitiveDB().
circtMSFTDeletePlacementDB()
void circtMSFTDeletePlacementDB (CirctMSFTPlacementDB self)
Definition at line 61 of file MSFT.cpp.
Referenced by PlacementDB::~PlacementDB().
circtMSFTDeletePrimitiveDB()
void circtMSFTDeletePrimitiveDB (CirctMSFTPrimitiveDB self)
Definition at line 35 of file MSFT.cpp.
Referenced by PrimitiveDB::~PrimitiveDB().
circtMSFTGetInstance()
MlirOperation circtMSFTGetInstance (MlirOperation cRoot, MlirAttribute cPath)
Definition at line 246 of file MSFT.cpp.
References circt::msft::getInstance().
circtMSFTPhysicalBoundsAttrGet()
MlirAttribute circtMSFTPhysicalBoundsAttrGet (MlirContext cContext, uint64_t xMin, uint64_t xMax, uint64_t yMin, uint64_t yMax)
Definition at line 227 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysicalRegionRefAttrGet()
MlirAttribute circtMSFTPhysicalRegionRefAttrGet (MlirContext cContext, MlirStringRef cName)
Definition at line 238 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGet()
MlirAttribute circtMSFTPhysLocationAttrGet (MlirContext cCtxt, CirctMSFTPrimitiveType devType, uint64_t x, uint64_t y, uint64_t num)
Definition at line 147 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTPhysLocationAttrGetNum()
uint64_t circtMSFTPhysLocationAttrGetNum (MlirAttribute attr)
Definition at line 169 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetPrimitiveType()
CirctMSFTPrimitiveType circtMSFTPhysLocationAttrGetPrimitiveType (MlirAttribute attr)
Definition at line 157 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetX()
uint64_t circtMSFTPhysLocationAttrGetX (MlirAttribute attr)
Definition at line 163 of file MSFT.cpp.
circtMSFTPhysLocationAttrGetY()
uint64_t circtMSFTPhysLocationAttrGetY (MlirAttribute attr)
Definition at line 166 of file MSFT.cpp.
circtMSFTPlacementDBAddDesignPlacements()
size_t circtMSFTPlacementDBAddDesignPlacements (CirctMSFTPlacementDB self)
Definition at line 64 of file MSFT.cpp.
Referenced by PlacementDB::addDesignPlacements().
circtMSFTPlacementDBAddPlacement()
MlirLogicalResult circtMSFTPlacementDBAddPlacement (CirctMSFTPlacementDB self, MlirAttribute cLoc, CirctMSFTPlacedInstance cInst)
Definition at line 68 of file MSFT.cpp.
References circt::calyx::direction::get(), CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
Referenced by PlacementDB::addPlacement().
circtMSFTPlacementDBGetNearestFreeInColumn()
MlirAttribute circtMSFTPlacementDBGetNearestFreeInColumn (CirctMSFTPlacementDB cdb, CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
Definition at line 101 of file MSFT.cpp.
Referenced by PlacementDB::getNearestFreeInColumn().
circtMSFTPlacementDBTryGetInstanceAt()
bool circtMSFTPlacementDBTryGetInstanceAt (CirctMSFTPlacementDB self, MlirAttribute cLoc, CirctMSFTPlacedInstance * out)
Definition at line 85 of file MSFT.cpp.
References CirctMSFTPlacedInstance::op, CirctMSFTPlacedInstance::path, CirctMSFTPlacedInstance::subpath, and CirctMSFTPlacedInstance::subpathLength.
Referenced by PlacementDB::getInstanceAt().
circtMSFTPlacementDBWalkPlacements()
void circtMSFTPlacementDBWalkPlacements (CirctMSFTPlacementDB cdb, CirctMSFTPlacementCallback ccb, int64_t bounds[4], CirctMSFTPrimitiveType cPrimTypeFilter, void * userData)
Walk all the placements within 'bounds' ([xmin, xmax, ymin, ymax], inclusive on all sides), with -1 meaning unbounded.
Definition at line 109 of file MSFT.cpp.
References CirctMSFTPlacedInstance::subpath, and circt::msft::PlacementDB::walkPlacements().
Referenced by PlacementDB::walkPlacements().
circtMSFTPrimitiveDBAddPrimitive()
MlirLogicalResult circtMSFTPrimitiveDBAddPrimitive (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
Definition at line 38 of file MSFT.cpp.
Referenced by PrimitiveDB::addPrimitive().
circtMSFTPrimitiveDBIsValidLocation()
bool circtMSFTPrimitiveDBIsValidLocation (CirctMSFTPrimitiveDB self, MlirAttribute cLoc)
Definition at line 43 of file MSFT.cpp.
Referenced by PrimitiveDB::isValidLocation().
circtMSFTRootedInstancePathAttrGet()
MlirAttribute circtMSFTRootedInstancePathAttrGet (MlirContext cCtxt, MlirAttribute cRootSym, MlirAttribute * cPathStringAttrs, size_t num)
Definition at line 177 of file MSFT.cpp.
References circt::calyx::direction::get().
circtMSFTSwitchInstanceAttrGet()
MlirAttribute circtMSFTSwitchInstanceAttrGet (MlirContext cCtxt, CirctMSFTSwitchInstanceCase * listOfCases, size_t numCases)
Definition at line 192 of file MSFT.cpp.
References CirctMSFTSwitchInstanceCase::attr, circt::calyx::direction::get(), and CirctMSFTSwitchInstanceCase::instance.
circtMSFTSwitchInstanceAttrGetCases()
void circtMSFTSwitchInstanceAttrGetCases (MlirAttribute attr, CirctMSFTSwitchInstanceCase * dstArray, size_t space)
Definition at line 211 of file MSFT.cpp.
circtMSFTSwitchInstanceAttrGetNumCases()
size_t circtMSFTSwitchInstanceAttrGetNumCases (MlirAttribute attr)
Definition at line 208 of file MSFT.cpp.
mlirMSFTAddPhysLocationAttr()
void mlirMSFTAddPhysLocationAttr (MlirOperation cOp, const char * entityName, PrimitiveType type, long x, long y, long num)
Definition at line 133 of file MSFT.cpp.
References circt::calyx::direction::get().
mlirMSFTRegisterPasses()
void mlirMSFTRegisterPasses ()
Definition at line 24 of file MSFT.cpp.
References circt::msft::registerMSFTPasses().