CIRCT: circt::scheduling Namespace Reference
circt::scheduling Namespace Reference
Namespaces
detail
Classes
class CyclicProblem
This class models a cyclic scheduling problem.
class ModuloProblem
This class models the modulo scheduling problem as the composition of the cyclic problem and the resource-constrained problem with fully-pipelined shared operators.
class Problem
This class models the most basic scheduling problem.
class SharedOperatorsProblem
This class models a resource-constrained scheduling problem.
Functions
LogicalResult scheduleASAP (Problem &prob)
This is a simple list scheduler for solving the basic scheduling problem.
LogicalResult scheduleSimplex (Problem &prob, Operation *lastOp)
Solve the basic problem using linear programming and a handwritten implementation of the simplex algorithm.
LogicalResult scheduleSimplex (CyclicProblem &prob, Operation *lastOp)
Solve the resource-free cyclic problem using linear programming and a handwritten implementation of the simplex algorithm.
LogicalResult scheduleSimplex (SharedOperatorsProblem &prob, Operation *lastOp)
Solve the acyclic problem with shared operators using a linear programming-based heuristic.
Function Documentation
scheduleASAP()
LogicalResult circt::scheduling::scheduleASAP (Problem & prob)
This is a simple list scheduler for solving the basic scheduling problem.
Its objective is to assign each operation its earliest possible start time, or in other words, to schedule each operation as soon as possible (hence the name). Fails if the dependence graph contains cycles.
Definition at line 20 of file ASAPScheduler.cpp.
References circt::scheduling::Problem::getContainingOp(), circt::scheduling::Problem::getDependences(), circt::scheduling::Problem::getLatency(), circt::scheduling::Problem::getLinkedOperatorType(), circt::scheduling::Problem::getOperations(), circt::scheduling::Problem::getStartTime(), and circt::scheduling::Problem::setStartTime().
scheduleSimplex() [1/3]
LogicalResult circt::scheduling::scheduleSimplex (CyclicProblem & prob, Operation * lastOp)
Solve the resource-free cyclic problem using linear programming and a handwritten implementation of the simplex algorithm.
The objectives are to determine the smallest feasible initiation interval, and to minimize the start time of the given lastOp. Fails if the dependence graph contains cycles that do not include at least one edge with a non-zero distance.
Definition at line 766 of file SimplexSchedulers.cpp.
scheduleSimplex() [2/3]
LogicalResult circt::scheduling::scheduleSimplex (Problem & prob, Operation * lastOp)
Solve the basic problem using linear programming and a handwritten implementation of the simplex algorithm.
The objective is to minimize the start time of the given lastOp. Fails if the dependence graph contains cycles.
Definition at line 761 of file SimplexSchedulers.cpp.
scheduleSimplex() [3/3]
LogicalResult circt::scheduling::scheduleSimplex (SharedOperatorsProblem & prob, Operation * lastOp)
Solve the acyclic problem with shared operators using a linear programming-based heuristic.
The approach tries to minimize the start time of the given lastOp, but optimality is not guaranteed. Fails if the dependence graph contains cycles.
Definition at line 772 of file SimplexSchedulers.cpp.