CIRCT: circt::msft Namespace Reference
circt::msft Namespace Reference
Classes
class PlacementDB
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
class PrimitiveDB
A data structure to contain locations of the primitives on the device.
Functions
mlir::LogicalResult exportQuartusTcl (MSFTModuleOp module, hw::SymbolCache &, llvm::StringRef outputFile="")
Export TCL for a specific hw module.
void populateSymbolCache (mlir::ModuleOp mod, hw::SymbolCache &)
Populate a SymbolCache to use during Tcl export.
void registerMSFTPasses ()
InstanceOp getInstance (MSFTModuleOp root, SymbolRefAttr path)
Find the instance in the instance hierarchy as specified by the instance names in 'path'.
std::unique_ptr< Pass > createLowerToHWPass ()
Function Documentation
createLowerToHWPass()
std::unique_ptr<Pass> circt::msft::createLowerToHWPass ()
Definition at line 244 of file MSFTPasses.cpp.
exportQuartusTcl()
mlir::LogicalResult circt::msft::exportQuartusTcl (MSFTModuleOp module, hw::SymbolCache & , llvm::StringRef outputFile = "")
Export TCL for a specific hw module.
getInstance()
msft::InstanceOp circt::msft::getInstance (MSFTModuleOp root, SymbolRefAttr path)
Find the instance in the instance hierarchy as specified by the instance names in 'path'.
Definition at line 102 of file MSFTDialect.cpp.
References getInstance().
Referenced by circtMSFTGetInstance(), and getInstance().
populateSymbolCache()
void circt::msft::populateSymbolCache (mlir::ModuleOp mod, hw::SymbolCache &)
Populate a SymbolCache to use during Tcl export.
registerMSFTPasses()
void circt::msft::registerMSFTPasses ()
Definition at line 255 of file MSFTPasses.cpp.
References registerPasses().
Referenced by mlirMSFTRegisterPasses(), and circt::registerAllPasses().