CIRCT: circt::hw Namespace Reference
circt::hw Namespace Reference
Namespaces
detail
module_like_impl
Classes
struct InnerName
struct ModulePortInfo
This holds a decoded list of input/inout and output ports for a module or instance.
struct PortInfo
This holds the name, type, direction of a module's ports.
class StmtVisitor
This helps visit TypeOp nodes.
class SymbolCache
This stores lookup tables to make manipulating and working with the IR more efficient.
class TypeAliasOr
class TypeOpVisitor
This helps visit TypeOp nodes.
Enumerations
enum PortDirection { INPUT = 1, OUTPUT = 2, INOUT = 3 }
A HW module ports direction.
Functions
ModulePortInfo getModulePortInfo (Operation *op)
TODO: Move all these functions to a hw::ModuleLike interface.
SmallVector< PortInfo > getAllModulePortInfos (Operation *op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
PortInfo getModuleInOrInoutPort (Operation *op, size_t idx)
Return the PortInfo for the specified input or inout port.
PortInfo getModuleOutputPort (Operation *op, size_t idx)
Return the PortInfo for the specified output port.
bool isAnyModule (Operation *module)
Return true if this is an hw.module, external module, generated module etc.
bool isAnyModuleOrInstance (Operation *module)
Return true if isAnyModule or instance.
FunctionType getModuleType (Operation *module)
Return the signature for the specified module as a function type.
unsigned getModuleNumInputs (Operation *moduleOrInstance)
Return the number of inputs for the specified module/instance.
unsigned getModuleNumOutputs (Operation *moduleOrInstance)
Return the number of outputs for the specified module/instance.
StringAttr getVerilogModuleNameAttr (Operation *module)
Returns the verilog module name attribute or symbol name of any module-like operations.
StringRef getVerilogModuleName (Operation *module)
StringAttr getModuleArgumentNameAttr (Operation *module, size_t argNo)
Return the port name for the specified argument or result.
StringAttr getModuleResultNameAttr (Operation *module, size_t argNo)
static StringRef getModuleArgumentName (Operation *module, size_t argNo)
static StringRef getModuleResultName (Operation *module, size_t resultNo)
void setModuleArgumentNames (Operation *module, ArrayRef< Attribute > names)
void setModuleResultNames (Operation *module, ArrayRef< Attribute > names)
bool isCombinational (Operation *op)
Return true if the specified operation is a combinational logic op.
bool isValidParameterExpression (Attribute attr, Operation *module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs=false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
bool isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
bool isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
int64_t getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
bool hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
template<typename BaseTy >
bool type_isa (Type type)
template<typename BaseTy >
BaseTy type_cast (Type type)
template<typename BaseTy >
BaseTy type_dyn_cast (Type type)
Enumeration Type Documentation
PortDirection
enum circt::hw::PortDirection
A HW module ports direction.
Enumerator
INPUT
OUTPUT
INOUT
Definition at line 31 of file HWOps.h.
Function Documentation
checkParameterInContext()
LogicalResult circt::hw::checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs = false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success.
If disallowParamRefs is true, then parameter references are not allowed.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 48 of file HWOps.cpp.
Referenced by isValidParameterExpression(), verifyLocalParamOp(), and verifyParamValueOp().
getAllModulePortInfos()
SmallVector< PortInfo > circt::hw::getAllModulePortInfos (Operation * op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 483 of file HWOps.cpp.
References getModuleType(), INOUT, INPUT, isAnyModuleOrInstance(), and OUTPUT.
Referenced by circt::esi::buildESIWrapper(), circt::esi::findValidReadySignals(), circt::ExportVerilog::GlobalNameResolver::legalizeModuleNames(), and circt::esi::resolvePortNames().
getBitWidth()
int64_t circt::hw::getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
Does not reflect any encoding, padding, or storage scheme, just the bit (and wire width) of a statically-size type. Reflects the number of wires needed to transmit a value of this type. Returns -1 if the type is not known or cannot be statically computed.
Definition at line 93 of file HWTypes.cpp.
Referenced by hwGetBitWidth(), and verifyHWStructCastOp().
getModuleArgumentName()
static StringRef circt::hw::getModuleArgumentName (Operation * module, size_t argNo) inline static
Definition at line 136 of file HWOps.h.
References getModuleArgumentNameAttr().
Referenced by circt::hw::module_like_impl::printModuleSignature().
getModuleArgumentNameAttr()
StringAttr circt::hw::getModuleArgumentNameAttr (Operation * module, size_t argNo)
Return the port name for the specified argument or result.
These can only return a null StringAttr when the IR is invalid.
Definition at line 268 of file HWOps.cpp.
Referenced by getModuleArgumentName().
getModuleInOrInoutPort()
PortInfo circt::hw::getModuleInOrInoutPort (Operation * op, size_t idx)
Return the PortInfo for the specified input or inout port.
Definition at line 513 of file HWOps.cpp.
References getModuleType(), INOUT, and INPUT.
getModuleNumInputs()
unsigned circt::hw::getModuleNumInputs (Operation * moduleOrInstance) inline
Return the number of inputs for the specified module/instance.
Definition at line 111 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
Referenced by circt::ExportVerilog::GlobalNameTable::getPortVerilogName().
getModuleNumOutputs()
unsigned circt::hw::getModuleNumOutputs (Operation * moduleOrInstance) inline
Return the number of outputs for the specified module/instance.
Definition at line 118 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
getModuleOutputPort()
PortInfo circt::hw::getModuleOutputPort (Operation * op, size_t idx)
Return the PortInfo for the specified output port.
Definition at line 530 of file HWOps.cpp.
References getModuleType(), and OUTPUT.
getModulePortInfo()
ModulePortInfo circt::hw::getModulePortInfo (Operation * op)
TODO: Move all these functions to a hw::ModuleLike interface.
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 450 of file HWOps.cpp.
References getModuleType(), INOUT, INPUT, isAnyModuleOrInstance(), and OUTPUT.
Referenced by lowerBoundInstance(), lowerInstanceResults(), and printInstanceOp().
getModuleResultName()
static StringRef circt::hw::getModuleResultName (Operation * module, size_t resultNo) inline static
Definition at line 140 of file HWOps.h.
References getModuleResultNameAttr().
getModuleResultNameAttr()
StringAttr circt::hw::getModuleResultNameAttr (Operation * module, size_t argNo)
Definition at line 276 of file HWOps.cpp.
Referenced by getModuleResultName(), and circt::hw::module_like_impl::printModuleSignature().
getModuleType()
FunctionType circt::hw::getModuleType (Operation * module)
Return the signature for the specified module as a function type.
Return the signature for a module as a function type from the module itself or from an hw::InstanceOp.
Definition at line 242 of file HWOps.cpp.
References circt::calyx::direction::get(), and isAnyModule().
Referenced by circt::esi::buildESIWrapper(), getAllModulePortInfos(), getModuleInOrInoutPort(), getModuleOutputPort(), getModulePortInfo(), setModuleArgumentNames(), setModuleResultNames(), and verifyOutputOp().
getVerilogModuleName()
StringRef circt::hw::getVerilogModuleName (Operation * module) inline
Definition at line 127 of file HWOps.h.
References getVerilogModuleNameAttr().
Referenced by extractHierarchyFromTop(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), getSymOpName(), and printHierarchy().
getVerilogModuleNameAttr()
StringAttr circt::hw::getVerilogModuleNameAttr (Operation * module)
Returns the verilog module name attribute or symbol name of any module-like operations.
Return the name to use for the Verilog module that we're referencing here.
This is typically the symbol, but can be overridden with the verilogName attribute.
Definition at line 259 of file HWOps.cpp.
Referenced by createModuleForCut(), getSymOpName(), getVerilogModuleName(), and circt::ExportVerilog::GlobalNameResolver::GlobalNameResolver().
hasHWInOutType()
bool circt::hw::hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
Unlike isHWValueType, this is not conservative, it only returns false on known InOut types, rather than any unknown types.
isAnyModule()
bool circt::hw::isAnyModule (Operation * module)
Return true if this is an hw.module, external module, generated module etc.
Definition at line 230 of file HWOps.cpp.
Referenced by getModuleType(), isAnyModuleOrInstance(), setModuleArgumentNames(), and setModuleResultNames().
isAnyModuleOrInstance()
bool circt::hw::isAnyModuleOrInstance (Operation * module)
Return true if isAnyModule or instance.
Definition at line 236 of file HWOps.cpp.
References isAnyModule().
Referenced by getAllModulePortInfos(), getModuleNumInputs(), getModuleNumOutputs(), and getModulePortInfo().
isCombinational()
bool circt::hw::isCombinational (Operation * op)
Return true if the specified operation is a combinational logic op.
Definition at line 26 of file HWOps.cpp.
References circt::hw::TypeOpVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchTypeOpVisitor().
isHWIntegerType()
bool circt::hw::isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
This checks that it is a signless standard dialect type and that it isn't zero bits.
This checks that it is a signless standard dialect type, that it isn't zero bits.
Definition at line 44 of file HWTypes.cpp.
Referenced by simplifyDivS(), simplifyDivU(), simplifyModS(), simplifyModU(), simplifyShl(), simplifyShrS(), and simplifyShrU().
isHWValueType()
bool circt::hw::isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
Referenced by hwTypeIsAValueType().
isValidParameterExpression()
bool circt::hw::isValidParameterExpression (Attribute attr, Operation * module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
Definition at line 113 of file HWOps.cpp.
References checkParameterInContext().
setModuleArgumentNames()
void circt::hw::setModuleArgumentNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 284 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
setModuleResultNames()
void circt::hw::setModuleResultNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 291 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
type_cast()
template<typename BaseTy > BaseTy circt::hw::type_cast (Type type)
Definition at line 80 of file HWTypes.h.
type_dyn_cast()
template<typename BaseTy > BaseTy circt::hw::type_dyn_cast (Type type)
Definition at line 92 of file HWTypes.h.
type_isa()
template<typename BaseTy > bool circt::hw::type_isa (Type type)
Definition at line 67 of file HWTypes.h.