CIRCT: circt::calyx Namespace Reference
circt::calyx Namespace Reference
Namespaces
direction
Classes
class Combinational
Signals that the following operation is combinational.
class ControlLike
Signals that the following operation is "control-like.".
struct PortInfo
This holds information about the port for either a Component or Cell.
Enumerations
enum Direction { Input = 0, Output = 1 }
The direction of a Component or Cell port.
Functions
hw::HWModuleExternOp getExternHWModule (OpBuilder &builder, ComponentOp op)
Returns a hw.module.extern operation describing the Verilog module which a ComponentOp eventually results in.
mlir::LogicalResult exportCalyx (mlir::ModuleOp module, llvm::raw_ostream &os)
void registerToCalyxTranslation ()
LogicalResult verifyControlLikeOp (Operation *op)
A helper function to verify each control-like operation has a valid parent and, if applicable, body.
LogicalResult verifyCombinationalOp (Operation *op)
A helper function to verify a combinational operation.
LogicalResult verifyCell (Operation *op)
A helper function to verify each operation with the Cell trait.
LogicalResult verifyGroupInterface (Operation *op)
A helper function to verify each operation with the Group Interface trait.
PortInfo getPortInfo (BlockArgument arg)
Returns port information for the block argument provided.
std::unique_ptr< mlir::Pass > createCompileControlPass ()
std::unique_ptr< mlir::Pass > createGoInsertionPass ()
std::unique_ptr< mlir::Pass > createRemoveGroupsPass ()
template<typename Op >
static void updateGroupAssignmentGuards (OpBuilder &builder, GroupOp &group, Op &op)
Updates the guard of each assignment within a group with op.
Enumeration Type Documentation
Direction
enum circt::calyx::Direction
The direction of a Component or Cell port.
this is similar to the implementation found in the FIRRTL dialect.
Enumerator
Input
Output
Definition at line 63 of file CalyxOps.h.
Function Documentation
createCompileControlPass()
std::unique_ptr< mlir::Pass > circt::calyx::createCompileControlPass ()
Definition at line 209 of file CompileControl.cpp.
createGoInsertionPass()
std::unique_ptr< mlir::Pass > circt::calyx::createGoInsertionPass ()
Definition at line 50 of file GoInsertion.cpp.
createRemoveGroupsPass()
std::unique_ptr< mlir::Pass > circt::calyx::createRemoveGroupsPass ()
Definition at line 120 of file RemoveGroups.cpp.
exportCalyx()
mlir::LogicalResult circt::calyx::exportCalyx (mlir::ModuleOp module, llvm::raw_ostream & os)
Definition at line 637 of file CalyxEmitter.cpp.
Referenced by registerToCalyxTranslation().
getExternHWModule()
hw::HWModuleExternOp circt::calyx::getExternHWModule (OpBuilder & builder, ComponentOp op)
Returns a hw.module.extern operation describing the Verilog module which a ComponentOp eventually results in.
Definition at line 26 of file CalyxToHW.cpp.
References circt::hw::PortInfo::argNum, circt::hw::PortInfo::direction, circt::hw::INPUT, circt::hw::PortInfo::name, circt::hw::OUTPUT, and circt::hw::PortInfo::type.
getPortInfo()
PortInfo circt::calyx::getPortInfo (BlockArgument arg)
Returns port information for the block argument provided.
Gets the port for a given BlockArgument.
Definition at line 102 of file CalyxOps.cpp.
Referenced by verifyPortDirection().
registerToCalyxTranslation()
void circt::calyx::registerToCalyxTranslation ()
Definition at line 649 of file CalyxEmitter.cpp.
References exportCalyx().
Referenced by circt::registerAllTranslations().
updateGroupAssignmentGuards()
template<typename Op > static void circt::calyx::updateGroupAssignmentGuards (OpBuilder & builder, GroupOp & group, Op & op) static
Updates the guard of each assignment within a group with op.
Definition at line 31 of file PassDetails.h.
Referenced by modifyGroupOperations().
verifyCell()
LogicalResult circt::calyx::verifyCell (Operation * op)
A helper function to verify each operation with the Cell trait.
Definition at line 149 of file CalyxOps.cpp.
verifyCombinationalOp()
LogicalResult circt::calyx::verifyCombinationalOp (Operation * op)
A helper function to verify a combinational operation.
verifyControlLikeOp()
LogicalResult circt::calyx::verifyControlLikeOp (Operation * op)
A helper function to verify each control-like operation has a valid parent and, if applicable, body.
Definition at line 160 of file CalyxOps.cpp.
References hasControlRegion(), and verifyControlBody().
Referenced by circt::calyx::ControlLike< ConcreteType >::verifyTrait().
verifyGroupInterface()
LogicalResult circt::calyx::verifyGroupInterface (Operation * op)
A helper function to verify each operation with the Group Interface trait.
Definition at line 960 of file CalyxOps.cpp.
References verifyPrimitivePortDriving().