CIRCT: circt::handshake Namespace Reference
circt::handshake Namespace Reference
Classes
class HandshakeVisitor
HandshakeVisitor is a visitor for handshake nodes.
Typedefs
using InstanceGraph = std::map< std::string, std::set< std::string > >
Iterates over the handshake::FuncOp's in the program to build an instance graph.
Functions
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createHandshakeDotPrintPass ()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createHandshakeOpCountPass ()
std::unique_ptr< mlir::Pass > createHandshakeMaterializeForksSinksPass ()
std::unique_ptr< mlir::Pass > createHandshakeRemoveBuffersPass ()
LogicalResult resolveInstanceGraph (ModuleOp moduleOp, InstanceGraph &instanceGraph, std::string &topLevel, SmallVectorImpl< std::string > &sortedFuncs)
Iterates over the handshake::FuncOp's in the program to build an instance graph.
LogicalResult verifyAllValuesHasOneUse (handshake::FuncOp op)
LogicalResult addSinkOps (handshake::FuncOp f, OpBuilder &rewriter)
LogicalResult addForkOps (handshake::FuncOp f, OpBuilder &rewriter)
void insertFork (Value result, bool isLazy, OpBuilder &rewriter)
bool simulate (llvm::StringRef toplevelFunction, llvm::ArrayRef< std::string > inputArgs, mlir::OwningModuleRef &module, mlir::MLIRContext &context)
template<typename TMemOp >
static bool executeMemoryOperation (TMemOp op, unsigned buffer, int opIndex, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< unsigned, unsigned > &memoryMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< std::vector< llvm::Any >> &store, std::vector< mlir::Value > &scheduleList)
Typedef Documentation
InstanceGraph
using circt::handshake::InstanceGraph = typedef std::map<std::string, std::set<std::string> >
Iterates over the handshake::FuncOp's in the program to build an instance graph.
In doing so, we detect whether there are any cycles in this graph, as well as infer a top function for the design by performing a topological sort of the instance graph. The result of this sort is placed in sortedFuncs.
Definition at line 36 of file HandshakePasses.h.
Function Documentation
addForkOps()
LogicalResult circt::handshake::addForkOps (handshake::FuncOp f, OpBuilder & rewriter)
Definition at line 70 of file Materialization.cpp.
References insertFork().
Referenced by lowerFuncOp().
addSinkOps()
LogicalResult circt::handshake::addSinkOps (handshake::FuncOp f, OpBuilder & rewriter)
Definition at line 90 of file Materialization.cpp.
Referenced by lowerFuncOp().
createHandshakeDotPrintPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > circt::handshake::createHandshakeDotPrintPass ()
Definition at line 510 of file Analysis.cpp.
createHandshakeMaterializeForksSinksPass()
std::unique_ptr< mlir::Pass > circt::handshake::createHandshakeMaterializeForksSinksPass ()
Definition at line 137 of file Materialization.cpp.
createHandshakeOpCountPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > circt::handshake::createHandshakeOpCountPass ()
Definition at line 515 of file Analysis.cpp.
createHandshakeRemoveBuffersPass()
std::unique_ptr< mlir::Pass > circt::handshake::createHandshakeRemoveBuffersPass ()
Definition at line 53 of file Buffers.cpp.
executeMemoryOperation()
template<typename TMemOp > static bool circt::handshake::executeMemoryOperation (TMemOp op, unsigned buffer, int opIndex, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap, llvm::DenseMap< unsigned, unsigned > & memoryMap, llvm::DenseMap< mlir::Value, double > & timeMap, std::vector< std::vector< llvm::Any >> & store, std::vector< mlir::Value > & scheduleList) static
Definition at line 298 of file HandshakeExecutableOps.cpp.
insertFork()
void circt::handshake::insertFork (Value result, bool isLazy, OpBuilder & rewriter)
Definition at line 45 of file Materialization.cpp.
References replaceFirstUse().
Referenced by addForkOps(), addLazyForks(), addMemOpForks(), and HandshakeCanonicalizePattern::rewrite().
resolveInstanceGraph()
LogicalResult circt::handshake::resolveInstanceGraph (ModuleOp moduleOp, InstanceGraph & instanceGraph, std::string & topLevel, SmallVectorImpl< std::string > & sortedFuncs)
Iterates over the handshake::FuncOp's in the program to build an instance graph.
In doing so, we detect whether there are any cycles in this graph, as well as infer a top module for the design by performing a topological sort of the instance graph. The result of this sort is placed in sortedFuncs.
Definition at line 35 of file PassHelpers.cpp.
simulate()
bool circt::handshake::simulate (llvm::StringRef toplevelFunction, llvm::ArrayRef< std::string > inputArgs, mlir::OwningModuleRef & module, mlir::MLIRContext & context)
verifyAllValuesHasOneUse()
LogicalResult circt::handshake::verifyAllValuesHasOneUse (handshake::FuncOp op)
Definition at line 107 of file PassHelpers.cpp.