CIRCT: circt::firrtl Namespace Reference
circt::firrtl Namespace Reference
Namespaces
detail
direction
impl
patterns
Classes
class AnalogType
class Annotation
This class provides a read-only projection of an annotation.
class AnnotationSet
This class provides a read-only projection over the MLIR attributes that represent a set of annotations.
class AnnotationSetIterator
class AsyncResetType
firrtl.AsyncReset.
class BundleType
BundleType is an aggregate of named elements.
struct CircuitNamespace
The namespace of a CircuitOp, generally inhabited by modules.
class ClockType
firrtl.Clock describe wires and ports meant for carrying clock signals.
class DeclVisitor
ExprVisitor is a visitor for FIRRTL declaration nodes.
class ExprVisitor
ExprVisitor is a visitor for FIRRTL expression nodes.
class FIRLexer
This implements a lexer for .fir files.
class FIRLexerCursor
This is the state captured for a lexer cursor.
struct FirMemory
struct FIRParserOptions
class FIRRTLType
class FIRRTLVisitor
FIRRTLVisitor allows you to visit all of the expr/stmt/decls with one class declaration.
class FIRToken
This represents a specific token for .fir files.
class FVectorType
VectorType is a fixed size collection of elements, like an array.
class InstanceGraph
This graph tracks modules and where they are instantiated.
class InstanceGraphNode
This is a Node in the InstanceGraph.
struct InstancePathCache
A data structure that caches and provides absolute paths to module instances in the IR.
class InstanceRecord
This is an edge in the InstanceGraph.
class IntType
This is the common base class between SIntType and UIntType.
struct ModuleNamespace
The namespace of a FModuleLike operation, generally inhabited by its ports and declarations.
class NamespaceBase
A namespace that is used to store existing names and generate new names in some scope within the IR.
struct PortInfo
This holds the name and type that describes the module's ports.
struct RecursiveTypeProperties
A collection of bits indicating the recursive properties of a type.
class ResetType
firrtl.Reset.
class SameOperandsIntTypeKind
A binary operation where the operands have the same integer kind.
class SIntType
A signed integer type, whose width may not be known.
class StmtVisitor
ExprVisitor is a visitor for FIRRTL statement nodes.
class UIntType
An unsigned integer type, whose width may not be known.
class WidthQualifiedType
Typedefs
using InstancePath = ArrayRef< InstanceOp >
An absolute instance path.
Enumerations
enum Direction { Direction::In, Direction::Out }
This represents the direction of a single port.
enum Flow { Flow::Source, Flow::Sink, Flow::Duplex }
enum DeclKind { DeclKind::Port, DeclKind::Instance, DeclKind::Other }
enum ReadPortSubfield { ReadPortSubfield::addr, ReadPortSubfield::en, ReadPortSubfield::clk, ReadPortSubfield::data }
enum WritePortSubfield {
WritePortSubfield::addr, WritePortSubfield::en, WritePortSubfield::clk, WritePortSubfield::data,
WritePortSubfield::mask
}
enum ReadWritePortSubfield {
ReadWritePortSubfield::addr, ReadWritePortSubfield::en, ReadWritePortSubfield::clk, ReadWritePortSubfield::rdata,
ReadWritePortSubfield::wmode, ReadWritePortSubfield::wdata, ReadWritePortSubfield::wmask
}
Functions
mlir::LogicalResult exportFIRFile (mlir::ModuleOp module, llvm::raw_ostream &os)
void registerToFIRFileTranslation ()
mlir::OwningModuleRef importFIRFile (llvm::SourceMgr &sourceMgr, mlir::MLIRContext *context, FIRParserOptions options={})
std::pair< bool, llvm::Optional< mlir::LocationAttr > > maybeStringToLocation (llvm::StringRef spelling, bool skipParsing, mlir::StringAttr &locatorFilenameCache, FileLineColLoc &fileLineColLocCache, MLIRContext *context)
void registerFromFIRFileTranslation ()
StringRef getAnnotationAttrName ()
Return the name of the attribute used for annotations on FIRRTL ops.
StringRef getPortAnnotationAttrName ()
Return the name of the attribute used for port annotations on FIRRTL ops.
StringRef getDialectAnnotationAttrName ()
Return the name of the dialect-prefixed attribute used for annotations.
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const Direction &dir)
Prints the Direction to the stream as either "in" or "out".
FieldRef getFieldRefFromValue (Value value)
Get the FieldRef from a value.
std::string getFieldName (const FieldRef &fieldRef)
Get a string identifier representing the FieldRef.
std::string getFieldName (const FieldRef &fieldRef, bool &rootKnown)
LogicalResult verifyModuleLikeOpInterface (FModuleLike module)
Verification hook for verifying module like operations.
bool isExpression (Operation *op)
Return true if the specified operation is a firrtl expression.
size_t getNumPorts (Operation *op)
Return the number of ports in a module-like thing (modules, memories, etc)
bool isConstant (Operation *op)
Return true if the specified operation has a constant value.
bool isConstant (Value value)
Return true if the specified value is a constant.
bool isDuplexValue (Value val)
Returns true if the value results from an expression with duplex flow.
Flow swapFlow (Flow flow)
Get a flow's reverse.
Flow foldFlow (Value val, Flow accumulatedFlow=Flow::Source)
Compute the flow for a Value, val, as determined by the FIRRTL specification.
DeclKind getDeclarationKind (Value val)
MemDirAttr operator| (MemDirAttr lhs, MemDirAttr rhs)
Allow 'or'ing MemDirAttr.
MemDirAttr & operator|= (MemDirAttr &lhs, MemDirAttr rhs)
bool hasDontTouch (Value value)
Check whether a block argument ("port") or the operation defining a value has a DontTouch annotation, or a symbol that should prevent certain types of canonicalizations.
bool hasDontTouch (Operation *op)
Check whether an operation has a DontTouch annotation, or a symbol that should prevent certain types of canonicalizations.
bool areTypesEquivalent (FIRRTLType destType, FIRRTLType srcType)
Returns whether the two types are equivalent.
bool areTypesWeaklyEquivalent (FIRRTLType destType, FIRRTLType srcType, bool destFlip=false, bool srcFlip=false)
Returns true if two types are weakly equivalent.
mlir::Type getVectorElementType (mlir::Type array)
mlir::Type getPassiveType (mlir::Type anyFIRRTLType)
llvm::Optional< int32_t > getBitWidth (FIRRTLType type)
template<typename T >
static T & formatInstancePath (T &into, const InstancePath &path)
template<typename T >
static T & operator<< (T &os, const InstancePath &path)
std::unique_ptr< mlir::Pass > createLowerFIRRTLAnnotationsPass (bool ignoreUnhandledAnnotations=false, bool ignoreClasslessAnnotations=false)
This is the pass constructor.
std::unique_ptr< mlir::Pass > createLowerFIRRTLTypesPass (bool replSeqMem=false)
This is the pass constructor.
std::unique_ptr< mlir::Pass > createLowerBundleVectorTypesPass ()
std::unique_ptr< mlir::Pass > createLowerCHIRRTLPass ()
std::unique_ptr< mlir::Pass > createIMConstPropPass ()
std::unique_ptr< mlir::Pass > createInlinerPass ()
std::unique_ptr< mlir::Pass > createBlackBoxMemoryPass ()
std::unique_ptr< mlir::Pass > createCreateSiFiveMetadataPass (bool replSeqMem=false, StringRef replSeqMemCircuit="", StringRef replSeqMemFile="")
std::unique_ptr< mlir::Pass > createEmitOMIRPass (StringRef outputFilename="")
std::unique_ptr< mlir::Pass > createExpandWhensPass ()
std::unique_ptr< mlir::Pass > createInferWidthsPass ()
std::unique_ptr< mlir::Pass > createInferResetsPass ()
std::unique_ptr< mlir::Pass > createPrefixModulesPass ()
std::unique_ptr< mlir::Pass > createPrintInstanceGraphPass ()
std::unique_ptr< mlir::Pass > createBlackBoxReaderPass (llvm::Optional< StringRef > inputPrefix={}, llvm::Optional< StringRef > resourcePrefix={})
std::unique_ptr< mlir::Pass > createGrandCentralPass ()
std::unique_ptr< mlir::Pass > createGrandCentralTapsPass ()
std::unique_ptr< mlir::Pass > createGrandCentralSignalMappingsPass ()
std::unique_ptr< mlir::Pass > createCheckCombCyclesPass ()
bool isOMIRStringEncodedPassthrough (StringRef type)
Check if an OMIR type is a string-encoded value that the FIRRTL dialect simply passes through as a string without any decoding.
llvm::hash_code hash_value (const BundleType::BundleElement &arg)
bool fromJSON (llvm::json::Value &value, StringRef circuitTarget, llvm::StringMap< ArrayAttr > &annotationMap, llvm::json::Path path, CircuitOp circuit, size_t &nlaNumber)
bool fromOMIRJSON (llvm::json::Value &value, StringRef circuitTarget, llvm::StringMap< ArrayAttr > &annotationMap, llvm::json::Path path, MLIRContext *context)
Convert a JSON value containing OMIR JSON (an array of OMNodes), convert this to an OMIRAnnotation, and add it to a mutable annotationMap argument.
bool scatterCustomAnnotations (llvm::StringMap< ArrayAttr > &annotationMap, CircuitOp circuit, unsigned &annotationID, Location loc, size_t &nlaNumber)
Convert known custom FIRRTL Annotations with compound targets to multiple attributes that are attached to IR operations where they have semantic meaning.
bool fromJSONRaw (llvm::json::Value &value, StringRef circuitTarget, SmallVectorImpl< Attribute > &attrs, llvm::json::Path path, MLIRContext *context)
ParseResult foldWhenEncodedVerifOp (ImplicitLocOpBuilder &builder, WhenOp whenStmt)
Chisel has a tendency to emit complex assert/assume/cover statements encoded as print operations with special formatting and metadata embedded in the message literal.
Variables
constexpr const char * dontTouchAnnoClass
constexpr const char * omirAnnoClass
constexpr const char * omirFileAnnoClass
constexpr const char * omirTrackerAnnoClass
constexpr const char * dataTapsClass
constexpr const char * memTapClass
constexpr const char * deletedKeyClass
constexpr const char * literalKeyClass
constexpr const char * referenceKeyClass
constexpr const char * internalKeyClass
constexpr const char * extractGrandCentralClass
Typedef Documentation
InstancePath
using circt::firrtl::InstancePath = typedef ArrayRef<InstanceOp>
An absolute instance path.
Definition at line 202 of file InstanceGraph.h.
Enumeration Type Documentation
DeclKind
enum circt::firrtl::DeclKind strong
Enumerator
Port
Instance
Other
Definition at line 67 of file FIRRTLOps.h.
Direction
enum circt::firrtl::Direction strong
This represents the direction of a single port.
Enumerator
In
Out
Definition at line 27 of file FIRRTLAttributes.h.
Flow
enum circt::firrtl::Flow strong
Enumerator
Source
Sink
Duplex
Definition at line 49 of file FIRRTLOps.h.
ReadPortSubfield
enum circt::firrtl::ReadPortSubfield strong
Enumerator
addr
en
clk
data
Definition at line 71 of file FIRRTLOps.h.
ReadWritePortSubfield
enum circt::firrtl::ReadWritePortSubfield strong
Enumerator
addr
en
clk
rdata
wmode
wdata
wmask
Definition at line 73 of file FIRRTLOps.h.
WritePortSubfield
enum circt::firrtl::WritePortSubfield strong
Enumerator
addr
en
clk
data
mask
Definition at line 72 of file FIRRTLOps.h.
Function Documentation
areTypesEquivalent()
bool circt::firrtl::areTypesEquivalent (FIRRTLType destType, FIRRTLType srcType)
Returns whether the two types are equivalent.
See the FIRRTL spec for the full definition of type equivalence. This predicate differs from the spec in that it only compares passive types. Because of how the FIRRTL dialect uses flip types in module ports and aggregates, this definition, unlike the spec, ignores flips.
This implements the exact definition of type equivalence in the FIRRTL spec. If the types being compared have any outer flips that encode FIRRTL module directions (input or output), these should be stripped before using this method.
Definition at line 506 of file FIRRTLTypes.cpp.
Referenced by verifyConnectOp().
areTypesWeaklyEquivalent()
bool circt::firrtl::areTypesWeaklyEquivalent (FIRRTLType destType, FIRRTLType srcType, bool destFlip = false, bool srcFlip = false)
Returns true if two types are weakly equivalent.
Returns whether the two types are weakly equivalent.
See the FIRRTL spec, Section 4.6, for a full definition of this. Roughly, the oriented types (the types with any flips pushed to the leaves) must match. This allows for types with flips in different positions to be equivalent.
Definition at line 549 of file FIRRTLTypes.cpp.
Referenced by verifyPartialConnectOp().
createBlackBoxMemoryPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createBlackBoxMemoryPass ()
Definition at line 427 of file BlackBoxMemory.cpp.
createBlackBoxReaderPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createBlackBoxReaderPass (llvm::Optional< StringRef > inputPrefix = {}, llvm::Optional< StringRef > resourcePrefix = {})
Definition at line 333 of file BlackBoxReader.cpp.
createCheckCombCyclesPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createCheckCombCyclesPass ()
Definition at line 546 of file CheckCombCycles.cpp.
createCreateSiFiveMetadataPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createCreateSiFiveMetadataPass (bool replSeqMem = false, StringRef replSeqMemCircuit = "", StringRef replSeqMemFile = "")
Definition at line 460 of file CreateSiFiveMetadata.cpp.
createEmitOMIRPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createEmitOMIRPass (StringRef outputFilename = "")
Definition at line 814 of file EmitOMIR.cpp.
createExpandWhensPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createExpandWhensPass ()
Definition at line 579 of file ExpandWhens.cpp.
createGrandCentralPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createGrandCentralPass ()
Definition at line 1607 of file GrandCentral.cpp.
createGrandCentralSignalMappingsPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createGrandCentralSignalMappingsPass ()
Definition at line 259 of file GrandCentralSignalMappings.cpp.
createGrandCentralTapsPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createGrandCentralTapsPass ()
Definition at line 847 of file GrandCentralTaps.cpp.
createIMConstPropPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createIMConstPropPass ()
Definition at line 735 of file IMConstProp.cpp.
createInferResetsPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createInferResetsPass ()
Definition at line 532 of file InferResets.cpp.
createInferWidthsPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createInferWidthsPass ()
Definition at line 2052 of file InferWidths.cpp.
createInlinerPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createInlinerPass ()
Definition at line 361 of file ModuleInliner.cpp.
createLowerBundleVectorTypesPass()
std::unique_ptr<mlir::Pass> circt::firrtl::createLowerBundleVectorTypesPass ()
createLowerCHIRRTLPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerCHIRRTLPass ()
Definition at line 697 of file LowerCHIRRTL.cpp.
createLowerFIRRTLAnnotationsPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerFIRRTLAnnotationsPass (bool ignoreUnhandledAnnotations = false, bool ignoreClasslessAnnotations = false)
This is the pass constructor.
Definition at line 648 of file LowerAnnotations.cpp.
createLowerFIRRTLTypesPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerFIRRTLTypesPass (bool replSeqMem = false)
This is the pass constructor.
Definition at line 1253 of file LowerTypes.cpp.
createPrefixModulesPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createPrefixModulesPass ()
Definition at line 400 of file PrefixModules.cpp.
createPrintInstanceGraphPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createPrintInstanceGraphPass ()
Definition at line 63 of file PrintInstanceGraph.cpp.
exportFIRFile()
mlir::LogicalResult circt::firrtl::exportFIRFile (mlir::ModuleOp module, llvm::raw_ostream & os)
Definition at line 791 of file FIREmitter.cpp.
Referenced by registerToFIRFileTranslation().
foldFlow()
Flow circt::firrtl::foldFlow (Value val, Flow accumulatedFlow = Flow::Source)
Compute the flow for a Value, val, as determined by the FIRRTL specification.
This recursively walks backwards from val to the declaration. The resulting flow is a combination of the declaration flow (output ports and instance inputs are sinks, registers and wires are duplex, anything else is a source) and the number of intermediary flips. An even number of flips will result in the same flow as the declaration. An odd number of flips will result in reversed flow being returned. The reverse of source is sink. The reverse of sink is source. The reverse of duplex is duplex. The accumulatedFlow parameter sets the initial flow. A user should normally not have to change this from its default of Flow::Source.
Definition at line 107 of file FIRRTLOps.cpp.
References Duplex, Out, and swapFlow().
Referenced by verifyConnectOp(), and verifyPartialConnectOp().
foldWhenEncodedVerifOp()
ParseResult circt::firrtl::foldWhenEncodedVerifOp (ImplicitLocOpBuilder & builder, WhenOp whenStmt)
Chisel has a tendency to emit complex assert/assume/cover statements encoded as print operations with special formatting and metadata embedded in the message literal.
These always reside in a when block of the following form:
when invCond:
  printf(clock, UInt<1>(1), "...[verif-library-assert]...")
  stop(clock, UInt<1>(1), 1)
Depending on the nature the verification operation, the stop may be optional. The Scala implementation simply removes all stops that have the same condition as the printf.
Definition at line 206 of file FIRParserAsserts.cpp.
References Assert, AssertNotX, Assume, ChiselAssert, Cover, circt::calyx::direction::get(), circt::firrtl::UIntType::get(), NoMod, parseConditionalCompileToggle(), sost::printOp(), TrueOrIsX, VerifLibAssert, and VerifLibAssume.
formatInstancePath()
template<typename T > static T& circt::firrtl::formatInstancePath (T & into, const InstancePath & path) inline static
Definition at line 205 of file InstanceGraph.h.
Referenced by operator<<().
fromJSON()
bool circt::firrtl::fromJSON (llvm::json::Value & value, StringRef circuitTarget, llvm::StringMap< ArrayAttr > & annotationMap, llvm::json::Path path, CircuitOp circuit, size_t & nlaNumber)
fromJSONRaw()
bool circt::firrtl::fromJSONRaw (llvm::json::Value & value, StringRef circuitTarget, SmallVectorImpl< Attribute > & attrs, llvm::json::Path path, MLIRContext * context)
fromOMIRJSON()
bool circt::firrtl::fromOMIRJSON (llvm::json::Value & value, StringRef circuitTarget, llvm::StringMap< ArrayAttr > & annotationMap, llvm::json::Path path, MLIRContext * context)
Convert a JSON value containing OMIR JSON (an array of OMNodes), convert this to an OMIRAnnotation, and add it to a mutable annotationMap argument.
getAnnotationAttrName()
StringRef circt::firrtl::getAnnotationAttrName () inline
Return the name of the attribute used for annotations on FIRRTL ops.
Definition at line 28 of file FIRRTLAnnotations.h.
Referenced by addAnnotation(), circt::firrtl::AnnotationSet::applyToAttrList(), circt::firrtl::AnnotationSet::applyToDictionaryAttr(), circt::firrtl::AnnotationSet::applyToOperation(), and getAnnotationsFrom().
getBitWidth()
llvm::Optional< int32_t > circt::firrtl::getBitWidth (FIRRTLType type)
Definition at line 1009 of file FIRRTLTypes.cpp.
References circt::firrtl::BundleType::getElements(), circt::firrtl::IntType::getWidth(), and None.
Referenced by canonicalizeOrOfConcatsWithCstOperands(), and verifyBitCastOp().
getDeclarationKind()
DeclKind circt::firrtl::getDeclarationKind (Value val)
Definition at line 146 of file FIRRTLOps.cpp.
References Instance, Other, and Port.
Referenced by verifyConnectOp(), and verifyPartialConnectOp().
getDialectAnnotationAttrName()
StringRef circt::firrtl::getDialectAnnotationAttrName () inline
Return the name of the dialect-prefixed attribute used for annotations.
Definition at line 34 of file FIRRTLAnnotations.h.
Referenced by circt::firrtl::AnnotationSet::applyToPortAttrList(), and circt::firrtl::AnnotationSet::applyToPortDictionaryAttr().
getFieldName() [1/2]
std::string circt::firrtl::getFieldName (const FieldRef & fieldRef)
Get a string identifier representing the FieldRef.
Definition at line 80 of file FIRRTLDialect.cpp.
getFieldName() [2/2]
std::string circt::firrtl::getFieldName (const FieldRef & fieldRef, bool & rootKnown)
Definition at line 85 of file FIRRTLDialect.cpp.
References getDeclName(), circt::FieldRef::getFieldID(), and circt::FieldRef::getValue().
getFieldRefFromValue()
FieldRef circt::firrtl::getFieldRefFromValue (Value value)
Get the FieldRef from a value.
This will travel backwards to through the IR, following Subfield and Subindex to find the op which declares the location.
Definition at line 29 of file FIRRTLDialect.cpp.
References circt::FieldRef::getDefiningOp(), circt::firrtl::BundleType::getFieldID(), and circt::firrtl::FVectorType::getFieldID().
getNumPorts()
size_t circt::firrtl::getNumPorts (Operation * op)
Return the number of ports in a module-like thing (modules, memories, etc)
Definition at line 158 of file FIRRTLOps.cpp.
Referenced by addAnnotation().
getPassiveType()
mlir::Type circt::firrtl::getPassiveType (mlir::Type anyFIRRTLType)
Referenced by castFromFIRRTLType(), isZeroBitFIRRTLType(), and tryEliminatingConnectsToValue().
getPortAnnotationAttrName()
StringRef circt::firrtl::getPortAnnotationAttrName () inline
Return the name of the attribute used for port annotations on FIRRTL ops.
Definition at line 31 of file FIRRTLAnnotations.h.
Referenced by addAnnotation().
getVectorElementType()
mlir::Type circt::firrtl::getVectorElementType (mlir::Type array)
hasDontTouch() [1/2]
bool circt::firrtl::hasDontTouch (Operation * op)
Check whether an operation has a DontTouch annotation, or a symbol that should prevent certain types of canonicalizations.
Definition at line 166 of file FIRRTLOps.cpp.
References circt::hw::InnerName::getInnerNameAttrName(), and circt::firrtl::AnnotationSet::hasDontTouch().
hasDontTouch() [2/2]
bool circt::firrtl::hasDontTouch (Value value)
Check whether a block argument ("port") or the operation defining a value has a DontTouch annotation, or a symbol that should prevent certain types of canonicalizations.
Definition at line 174 of file FIRRTLOps.cpp.
References circt::firrtl::AnnotationSet::forPort(), and circt::firrtl::AnnotationSet::hasDontTouch().
Referenced by foldSingleSetConnect(), isDeletableWireOrReg(), and foldResetMux::matchAndRewrite().
hash_value()
llvm::hash_code circt::firrtl::hash_value (const BundleType::BundleElement & arg)
Definition at line 691 of file FIRRTLTypes.cpp.
References mlir::hash_value(), circt::firrtl::BundleType::BundleElement::name, and circt::firrtl::BundleType::BundleElement::type.
importFIRFile()
mlir::OwningModuleRef circt::firrtl::importFIRFile (llvm::SourceMgr & sourceMgr, mlir::MLIRContext * context, FIRParserOptions options = {})
Referenced by registerFromFIRFileTranslation().
isConstant() [1/2]
bool circt::firrtl::isConstant (Operation * op)
Return true if the specified operation has a constant value.
This trivially checks for firrtl.constant and friends, but also looks through subaccesses and correctly handles wires driven with only constant values.
Definition at line 2062 of file FIRRTLOps.cpp.
Referenced by isConstant().
isConstant() [2/2]
bool circt::firrtl::isConstant (Value value)
Return true if the specified value is a constant.
This trivially checks for firrtl.constant and friends, but also looks through subaccesses and correctly handles wires driven with only constant values.
Definition at line 2095 of file FIRRTLOps.cpp.
References isConstant().
isDuplexValue()
bool circt::firrtl::isDuplexValue (Value val)
Returns true if the value results from an expression with duplex flow.
Duplex values have special treatment in bundle connect operations, and their flip orientation is not used to determine the direction of each pairwise connect.
Definition at line 83 of file FIRRTLOps.cpp.
isExpression()
bool circt::firrtl::isExpression (Operation * op)
Return true if the specified operation is a firrtl expression.
Definition at line 1915 of file FIRRTLOps.cpp.
References circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchExprVisitor().
Referenced by isEmittedInline(), and circt::ExportVerilog::isVerilogExpression().
isOMIRStringEncodedPassthrough()
bool circt::firrtl::isOMIRStringEncodedPassthrough (StringRef type)
Check if an OMIR type is a string-encoded value that the FIRRTL dialect simply passes through as a string without any decoding.
Definition at line 442 of file FIRRTLAnnotations.cpp.
Referenced by scatterOMIR().
maybeStringToLocation()
std::pair<bool, llvm::Optional<mlir::LocationAttr> > circt::firrtl::maybeStringToLocation (llvm::StringRef spelling, bool skipParsing, mlir::StringAttr & locatorFilenameCache, FileLineColLoc & fileLineColLocCache, MLIRContext * context)
Referenced by scatterOMField(), and scatterOMNode().
operator<<() [1/2]
llvm::raw_ostream & circt::firrtl::operator<< (llvm::raw_ostream & os, const Direction & dir)
Prints the Direction to the stream as either "in" or "out".
Definition at line 103 of file FIRRTLAttributes.cpp.
References circt::firrtl::direction::toString().
operator<<() [2/2]
template<typename T > static T& circt::firrtl::operator<< (T & os, const InstancePath & path) static
Definition at line 213 of file InstanceGraph.h.
References formatInstancePath().
operator|()
MemDirAttr circt::firrtl::operator| (MemDirAttr lhs, MemDirAttr rhs) inline
Allow 'or'ing MemDirAttr.
This allows combining Read and Write into ReadWrite.
Definition at line 77 of file FIRRTLOps.h.
operator|=()
MemDirAttr& circt::firrtl::operator|= (MemDirAttr & lhs, MemDirAttr rhs) inline
Definition at line 83 of file FIRRTLOps.h.
registerFromFIRFileTranslation()
void circt::firrtl::registerFromFIRFileTranslation ()
Definition at line 3701 of file FIRParser.cpp.
References importFIRFile().
Referenced by circt::registerAllTranslations().
registerToFIRFileTranslation()
void circt::firrtl::registerToFIRFileTranslation ()
Definition at line 801 of file FIREmitter.cpp.
References exportFIRFile().
Referenced by circt::registerAllTranslations().
scatterCustomAnnotations()
bool circt::firrtl::scatterCustomAnnotations (llvm::StringMap< ArrayAttr > & annotationMap, CircuitOp circuit, unsigned & annotationID, Location loc, size_t & nlaNumber)
Convert known custom FIRRTL Annotations with compound targets to multiple attributes that are attached to IR operations where they have semantic meaning.
This rewrites the input annotationMap to convert non-specific Annotations targeting "~" to those targeting something more specific if possible.
Return a new identifier that can be used to link scattered annotations together. This mutates the by-reference parameter annotationID.
Add a don't touch annotation for a target.
Definition at line 1229 of file FIRAnnotations.cpp.
References buildNLA(), canonicalizeTarget(), expandNonLocal(), circt::calyx::direction::get(), omirAnnoClass, parseAugmentedType(), scatterOMIRAnnotation(), and splitAndAppendTarget().
swapFlow()
Flow circt::firrtl::swapFlow (Flow flow)
Get a flow's reverse.
Definition at line 95 of file FIRRTLOps.cpp.
References Duplex, Sink, and Source.
Referenced by foldFlow().
verifyModuleLikeOpInterface()
LogicalResult circt::firrtl::verifyModuleLikeOpInterface (FModuleLike module)
Verification hook for verifying module like operations.
Definition at line 23 of file FIRRTLOpInterfaces.cpp.
Variable Documentation
dataTapsClass
constexpr const char* circt::firrtl::dataTapsClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DataTapsAnnotation"
Definition at line 40 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::runOnOperation().
deletedKeyClass
constexpr const char* circt::firrtl::deletedKeyClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DeletedDataTapKey"
Definition at line 44 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::runOnOperation().
dontTouchAnnoClass
constexpr const char* circt::firrtl::dontTouchAnnoClass constexpr
Initial value:
=
    "firrtl.transforms.DontTouchAnnotation"
Definition at line 29 of file AnnotationDetails.h.
Referenced by circt::firrtl::AnnotationSet::addDontTouch(), circt::firrtl::AnnotationSet::hasDontTouch(), and circt::firrtl::AnnotationSet::removeDontTouch().
extractGrandCentralClass
constexpr const char* circt::firrtl::extractGrandCentralClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.ExtractGrandCentralAnnotation"
Definition at line 52 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::runOnOperation().
internalKeyClass
constexpr const char* circt::firrtl::internalKeyClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DataTapModuleSignalKey"
Definition at line 50 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::gatherAnnotations(), GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
literalKeyClass
constexpr const char* circt::firrtl::literalKeyClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.LiteralDataTapKey"
Definition at line 46 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
memTapClass
constexpr const char* circt::firrtl::memTapClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.MemTapAnnotation"
Definition at line 42 of file AnnotationDetails.h.
Referenced by GrandCentralTapsPass::gatherAnnotations(), GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
omirAnnoClass
constexpr const char* circt::firrtl::omirAnnoClass constexpr
Initial value:
=
    "freechips.rocketchip.objectmodel.OMIRAnnotation"
Definition at line 32 of file AnnotationDetails.h.
Referenced by scatterCustomAnnotations(), scatterOMField(), scatterOMIRAnnotation(), and scatterOMNode().
omirFileAnnoClass
constexpr const char* circt::firrtl::omirFileAnnoClass constexpr
Initial value:
=
    "freechips.rocketchip.objectmodel.OMIRFileAnnotation"
Definition at line 34 of file AnnotationDetails.h.
omirTrackerAnnoClass
constexpr const char* circt::firrtl::omirTrackerAnnoClass constexpr
Initial value:
=
    "freechips.rocketchip.objectmodel.OMIRTracker"
Definition at line 36 of file AnnotationDetails.h.
Referenced by scatterOMIR().
referenceKeyClass
constexpr const char* circt::firrtl::referenceKeyClass constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.ReferenceDataTapKey"
Definition at line 48 of file AnnotationDetails.h.
Referenced by isReferenceDataTapOfType(), and GrandCentralTapsPass::processAnnotation().