CIRCT: circt Namespace Reference
circt Namespace Reference
Namespaces
analysis
calyx
comb
esi
ExportVerilog
firrtl
handshake
hw
llhd
moore
msft
python
scheduling
seq
staticlogic
support
sv
test
Classes
class Backedge
Backedge is a wrapper class around a Value.
class BackedgeBuilder
Instantiate one of these and use it to build typed backedges.
class BuildBBRegs
Builds registers for each block argument in the program.
class BuildControl
Builds a control schedule by traversing the CFG of the function and associating this with the previously created groups.
class BuildOpGroups
Iterate through the operations of a source function and instantiate components or primitives based on the type of the operations.
class BuildReturnRegs
Builds registers for the return statement of the program and constant assignments to the component return value.
class BuildWhileGroups
In BuildWhileGroups, a register is created for each iteration argumenet of the while op.
struct CalyxMemoryInterface
The various lowering passes are agnostic wrt.
struct CalyxMemoryPorts
A structure representing a set of ports which act as a memory interface.
class CleanupFuncOps
Erases FuncOp operations.
class ComponentLoweringState
class ConvertIndexTypes
Connverts all index-typed operations and values to i32 values.
struct EliminateUnusedCombGroups
Removes calyx::CombGroupOps which are unused.
class FieldRef
This class represents a reference to a specific field or element of an aggregate value.
struct FuncOpConversion
Creates a new Calyx component for each FuncOp in the program.
class FuncOpPartialLoweringPattern
FuncOpPartialLoweringPatterns are patterns which intend to match on FuncOps and then perform their own walking of the IR.
class InlineCombGroups
This pass recursively inlines use-def chains of combinational logic (from non-stateful groups) into groups referenced in the control schedule.
class InlineExecuteRegionOpPattern
Inlines Calyx ExecuteRegionOp operations within their parent blocks.
class LateSSAReplacement
LateSSAReplacement contains various functions for replacing SSA values that were not replaced during op construction.
struct LoweringOptions
Options which control the emission from CIRCT to Verilog.
struct ModuleOpConversion
struct MultipleGroupDonePattern
When building groups which contain accesses to multiple sequential components, a group_done op is created for each of these.
struct NonTerminatingGroupDonePattern
GroupDoneOp's are terminator operations and should therefore be the last operator in a group.
class PartialLoweringPattern
Base class for partial lowering passes.
class ProgramLoweringState
ProgramLoweringState handles the current state of lowering of a Calyx program.
class RewriteMemoryAccesses
This pass rewrites memory accesses that have a width mismatch.
class SCFToCalyxPass
struct WhileScheduleable
Typedefs
using FuncMapping = DenseMap< FuncOp, calyx::ComponentOp >
A mapping is maintained between a function operation and its corresponding Calyx component.
using Scheduleable = std::variant< calyx::GroupOp, WhileScheduleable >
A variant of types representing scheduleable operations.
Functions
std::unique_ptr< mlir::Pass > createAffineToStaticLogic ()
std::unique_ptr< mlir::Pass > createCalyxToHWPass ()
std::unique_ptr< mlir::Pass > createExportVerilogPass (llvm::raw_ostream &os)
std::unique_ptr< mlir::Pass > createExportVerilogPass ()
std::unique_ptr< mlir::Pass > createExportSplitVerilogPass (llvm::StringRef directory="./")
mlir::LogicalResult exportVerilog (mlir::ModuleOp module, llvm::raw_ostream &os)
Export a module containing HW, and SV dialect code.
mlir::LogicalResult exportSplitVerilog (mlir::ModuleOp module, llvm::StringRef dirname)
Export a module containing HW, and SV dialect code, as one file per SV module.
std::unique_ptr< mlir::Pass > createLowerFIRRTLToHWPass (bool enableAnnotationWarning=false, bool nonConstAsyncResetValueIsError=false)
This is the pass constructor.
std::unique_ptr< mlir::Pass > createHandshakeToFIRRTLPass ()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createConvertHWToLLHDPass ()
Create a HW to LLHD conversion pass.
void populateLLHDToLLVMConversionPatterns (mlir::LLVMTypeConverter &converter, RewritePatternSet &patterns, size_t &sigCounter, size_t &regCounter)
Get the LLHD to LLVM conversion patterns.
std::unique_ptr< OperationPass< ModuleOp > > createConvertLLHDToLLVMPass ()
Create an LLHD to LLVM conversion pass.
std::unique_ptr< OperationPass< ModuleOp > > createConvertMooreToCorePass ()
Create an Moore to Comb/HW/LLHD conversion pass.
std::unique_ptr< OperationPass< ModuleOp > > createSCFToCalyxPass ()
Create an SCF to Calyx conversion pass.
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createHandshakeAnalysisPass ()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createHandshakeDataflowPass ()
std::unique_ptr< mlir::OperationPass< handshake::FuncOp > > createHandshakeCanonicalizePass ()
std::unique_ptr< mlir::OperationPass< handshake::FuncOp > > createHandshakeRemoveBlockPass ()
std::unique_ptr< mlir::OperationPass< handshake::FuncOp > > createHandshakeInsertBufferPass ()
std::unique_ptr< mlir::Pass > createCreatePipelinePass ()
void registerAllDialects (mlir::DialectRegistry &registry)
void registerAllPasses ()
void registerAllTranslations ()
APInt sextOrSelfZeroWidth (APInt value, unsigned width)
A safe version of APInt::sextOrSelf that will NOT assert on zero-width signed APSInts.
APSInt extOrTruncZeroWidth (APSInt value, unsigned width)
A safe version of APSInt::extOrTrunc that will NOT assert on zero-width signed APSInts.
inline ::llvm::hash_code hash_value (const FieldRef &fieldRef)
Get a hash code for a FieldRef.
void registerLoweringCLOptions ()
Register commandline options for the verilog emitter.
void applyLoweringCLOptions (ModuleOp module)
Apply any command line specified style options to the mlir module.
void appendPossiblyAbsolutePath (llvm::SmallVectorImpl< char > &base, const llvm::Twine &suffix)
Append a path to an existing path, replacing it if the other path is absolute.
std::unique_ptr< mlir::Pass > createFlattenMemRefPass ()
std::unique_ptr< mlir::Pass > createFlattenMemRefCallsPass ()
static bool matchConstantOp (Operation *op, APInt &value)
Tries to match a constant value defined by op.
static bool singleLoadFromMemory (Value memref)
Returns true if there exists only a single memref::LoadOp which loads from the memory referenced by loadOp.
static bool noStoresToMemory (Value memref)
Returns true if there are no memref::StoreOp uses with the referenced memory.
static DictionaryAttr getMandatoryPortAttr (MLIRContext *ctx, StringRef name)
Creates a DictionaryAttr containing a unit attribute 'name'.
static void addMandatoryComponentPorts (PatternRewriter &rewriter, SmallVectorImpl< calyx::PortInfo > &ports)
Adds the mandatory Calyx component I/O ports (->[clk, reset, go], [done]->) to ports.
template<typename TGroup >
static TGroup createGroup (PatternRewriter &rewriter, calyx::ComponentOp compOp, Location loc, Twine uniqueName)
Creates a new calyx::CombGroupOp or calyx::GroupOp group within compOp.
static Value getComponentOutput (calyx::ComponentOp compOp, unsigned outPortIdx)
Get the index'th output port of compOp.
static Type convIndexType (PatternRewriter &rewriter, Type type)
If the provided type is an index type, converts it to i32, else, returns the unmodified type.
static void buildAssignmentsForRegisterWrite (ComponentLoweringState &state, PatternRewriter &rewriter, calyx::GroupOp groupOp, calyx::RegisterOp &reg, Value inputValue)
Creates register assignment operations within the provided groupOp.
static calyx::GroupOp buildWhileIterArgAssignments (PatternRewriter &rewriter, ComponentLoweringState &state, Location loc, scf::WhileOp whileOp, Twine uniqueSuffix, ValueRange ops)
static calyx::RegisterOp createReg (ComponentLoweringState &compState, PatternRewriter &rewriter, Location loc, Twine prefix, size_t width)
Creates a new register within the component associated to 'compState'.
template<typename TAllocOp >
static LogicalResult buildAllocOp (ComponentLoweringState &componentState, PatternRewriter &rewriter, TAllocOp allocOp)
static void appendPortsForExternalMemref (PatternRewriter &rewriter, StringRef memName, Value memref, SmallVectorImpl< calyx::PortInfo > &inPorts, SmallVectorImpl< calyx::PortInfo > &outPorts)
Typedef Documentation
FuncMapping
using circt::FuncMapping = typedef DenseMap<FuncOp, calyx::ComponentOp>
A mapping is maintained between a function operation and its corresponding Calyx component.
Definition at line 41 of file SCFToCalyx.cpp.
Scheduleable
using circt::Scheduleable = typedef std::variant<calyx::GroupOp, WhileScheduleable>
A variant of types representing scheduleable operations.
Definition at line 52 of file SCFToCalyx.cpp.
Function Documentation
addMandatoryComponentPorts()
static void circt::addMandatoryComponentPorts (PatternRewriter & rewriter, SmallVectorImpl< calyx::PortInfo > & ports) static
Adds the mandatory Calyx component I/O ports (->[clk, reset, go], [done]->) to ports.
Definition at line 129 of file SCFToCalyx.cpp.
References getMandatoryPortAttr(), circt::calyx::Input, and circt::calyx::Output.
Referenced by circt::FuncOpConversion::PartiallyLowerFuncToComp().
appendPortsForExternalMemref()
static void circt::appendPortsForExternalMemref (PatternRewriter & rewriter, StringRef memName, Value memref, SmallVectorImpl< calyx::PortInfo > & inPorts, SmallVectorImpl< calyx::PortInfo > & outPorts) static
Read data
Done
Write data
Memory address outputs
Write enable
Definition at line 1236 of file SCFToCalyx.cpp.
References circt::calyx::direction::get(), circt::calyx::Input, and circt::calyx::Output.
Referenced by circt::FuncOpConversion::PartiallyLowerFuncToComp().
appendPossiblyAbsolutePath()
void circt::appendPossiblyAbsolutePath (llvm::SmallVectorImpl< char > & base, const llvm::Twine & suffix)
Append a path to an existing path, replacing it if the other path is absolute.
This mimicks the behaviour of foo/bar and /foo/bar being used in a working directory /home, resulting in /home/foo/bar and /foo/bar, respectively.
Definition at line 23 of file Path.cpp.
Referenced by createOutputFile(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), and HWExportModuleHierarchyPass::runOnOperation().
applyLoweringCLOptions()
void circt::applyLoweringCLOptions (ModuleOp module)
Apply any command line specified style options to the mlir module.
Definition at line 155 of file LoweringOptions.cpp.
References clOptions.
buildAllocOp()
template<typename TAllocOp > static LogicalResult circt::buildAllocOp (ComponentLoweringState & componentState, PatternRewriter & rewriter, TAllocOp allocOp) static
Definition at line 907 of file SCFToCalyx.cpp.
References circt::calyx::direction::get(), circt::ComponentLoweringState::getComponentOp(), circt::ComponentLoweringState::getUniqueName(), and circt::ComponentLoweringState::registerMemoryInterface().
Referenced by circt::BuildOpGroups::buildOp().
buildAssignmentsForRegisterWrite()
static void circt::buildAssignmentsForRegisterWrite (ComponentLoweringState & state, PatternRewriter & rewriter, calyx::GroupOp groupOp, calyx::RegisterOp & reg, Value inputValue) static
Creates register assignment operations within the provided groupOp.
Definition at line 513 of file SCFToCalyx.cpp.
References circt::ComponentLoweringState::getConstant(), and seq::reg().
Referenced by circt::BuildOpGroups::buildOp(), and buildWhileIterArgAssignments().
buildWhileIterArgAssignments()
static calyx::GroupOp circt::buildWhileIterArgAssignments (PatternRewriter & rewriter, ComponentLoweringState & state, Location loc, scf::WhileOp whileOp, Twine uniqueSuffix, ValueRange ops) static
Pass iteration arguments through registers. This follows closely to what is done for branch ops.
Definition at line 527 of file SCFToCalyx.cpp.
References buildAssignmentsForRegisterWrite(), circt::ComponentLoweringState::getComponentOp(), circt::ComponentLoweringState::getWhileIterReg(), and seq::reg().
Referenced by circt::BuildOpGroups::buildOp(), and circt::BuildWhileGroups::PartiallyLowerFuncToComp().
convIndexType()
static Type circt::convIndexType (PatternRewriter & rewriter, Type type) static
If the provided type is an index type, converts it to i32, else, returns the unmodified type.
Definition at line 165 of file SCFToCalyx.cpp.
Referenced by circt::BuildOpGroups::buildOp(), circt::ConvertIndexTypes::PartiallyLowerFuncToComp(), circt::FuncOpConversion::PartiallyLowerFuncToComp(), and circt::BuildReturnRegs::PartiallyLowerFuncToComp().
createAffineToStaticLogic()
std::unique_ptr< mlir::Pass > mlir::circt::createAffineToStaticLogic ()
Definition at line 252 of file AffineToStaticLogic.cpp.
createCalyxToHWPass()
std::unique_ptr< mlir::Pass > mlir::circt::createCalyxToHWPass ()
Definition at line 58 of file CalyxToHW.cpp.
createConvertHWToLLHDPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::createConvertHWToLLHDPass ()
Create a HW to LLHD conversion pass.
Definition at line 47 of file HWToLLHD.cpp.
createConvertLLHDToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::circt::createConvertLLHDToLLVMPass ()
Create an LLHD to LLVM conversion pass.
Definition at line 2715 of file LLHDToLLVM.cpp.
createConvertMooreToCorePass()
std::unique_ptr< OperationPass< ModuleOp > > circt::createConvertMooreToCorePass ()
Create an Moore to Comb/HW/LLHD conversion pass.
Create a Moore to core dialects conversion pass.
Definition at line 35 of file MooreToCore.cpp.
createCreatePipelinePass()
std::unique_ptr< mlir::Pass > circt::createCreatePipelinePass ()
Definition at line 122 of file StandardToStaticLogic.cpp.
createExportSplitVerilogPass()
std::unique_ptr<mlir::Pass> circt::createExportSplitVerilogPass (llvm::StringRef directory = "./")
createExportVerilogPass() [1/2]
std::unique_ptr< mlir::Pass > circt::createExportVerilogPass ()
Definition at line 4346 of file ExportVerilog.cpp.
References createExportVerilogPass().
createExportVerilogPass() [2/2]
std::unique_ptr< mlir::Pass > circt::createExportVerilogPass (llvm::raw_ostream & os)
Definition at line 4342 of file ExportVerilog.cpp.
Referenced by createExportVerilogPass().
createFlattenMemRefCallsPass()
std::unique_ptr< mlir::Pass > circt::createFlattenMemRefCallsPass ()
Definition at line 367 of file FlattenMemRefs.cpp.
createFlattenMemRefPass()
std::unique_ptr< mlir::Pass > circt::createFlattenMemRefPass ()
Definition at line 363 of file FlattenMemRefs.cpp.
createGroup()
template<typename TGroup > static TGroup circt::createGroup (PatternRewriter & rewriter, calyx::ComponentOp compOp, Location loc, Twine uniqueName) static
Creates a new calyx::CombGroupOp or calyx::GroupOp group within compOp.
Definition at line 146 of file SCFToCalyx.cpp.
createHandshakeAnalysisPass()
std::unique_ptr<mlir::OperationPass<mlir::ModuleOp> > circt::createHandshakeAnalysisPass ()
createHandshakeCanonicalizePass()
std::unique_ptr<mlir::OperationPass<handshake::FuncOp> > circt::createHandshakeCanonicalizePass ()
createHandshakeDataflowPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > mlir::circt::createHandshakeDataflowPass ()
Definition at line 1659 of file StandardToHandshake.cpp.
createHandshakeInsertBufferPass()
std::unique_ptr< mlir::OperationPass< handshake::FuncOp > > mlir::circt::createHandshakeInsertBufferPass ()
Definition at line 1669 of file StandardToHandshake.cpp.
createHandshakeRemoveBlockPass()
std::unique_ptr< mlir::OperationPass< handshake::FuncOp > > mlir::circt::createHandshakeRemoveBlockPass ()
Definition at line 1664 of file StandardToHandshake.cpp.
createHandshakeToFIRRTLPass()
std::unique_ptr< mlir::Pass > mlir::circt::createHandshakeToFIRRTLPass ()
Definition at line 2510 of file HandshakeToFIRRTL.cpp.
createLowerFIRRTLToHWPass()
std::unique_ptr< mlir::Pass > circt::createLowerFIRRTLToHWPass (bool enableAnnotationWarning = false, bool nonConstAsyncResetValueIsError = false)
This is the pass constructor.
Definition at line 388 of file LowerToHW.cpp.
createReg()
static calyx::RegisterOp circt::createReg (ComponentLoweringState & compState, PatternRewriter & rewriter, Location loc, Twine prefix, size_t width) static
Creates a new register within the component associated to 'compState'.
Definition at line 579 of file SCFToCalyx.cpp.
References circt::ComponentLoweringState::getComponentOp().
Referenced by circt::BuildOpGroups::buildOp(), circt::BuildWhileGroups::PartiallyLowerFuncToComp(), and circt::BuildReturnRegs::PartiallyLowerFuncToComp().
createSCFToCalyxPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::createSCFToCalyxPass ()
Create an SCF to Calyx conversion pass.
Definition at line 2159 of file SCFToCalyx.cpp.
exportSplitVerilog()
mlir::LogicalResult circt::exportSplitVerilog (mlir::ModuleOp module, llvm::StringRef dirname)
Export a module containing HW, and SV dialect code, as one file per SV module.
Requires that the SV dialect is loaded in to the context.
Files are created in the directory indicated by dirname.
Referenced by mlirExportSplitVerilog().
exportVerilog()
mlir::LogicalResult circt::exportVerilog (mlir::ModuleOp module, llvm::raw_ostream & os)
Export a module containing HW, and SV dialect code.
Requires that the SV dialect is loaded in to the context.
Referenced by mlirExportVerilog(), and circt::llhd::registerToVerilogTranslation().
extOrTruncZeroWidth()
APSInt circt::extOrTruncZeroWidth (APSInt value, unsigned width)
A safe version of APSInt::extOrTrunc that will NOT assert on zero-width signed APSInts.
Instead of asserting, this will zero extend.
Definition at line 23 of file APInt.cpp.
Referenced by getExtendedConstant().
getComponentOutput()
static Value circt::getComponentOutput (calyx::ComponentOp compOp, unsigned outPortIdx) static
Get the index'th output port of compOp.
Definition at line 155 of file SCFToCalyx.cpp.
Referenced by circt::BuildReturnRegs::PartiallyLowerFuncToComp().
getMandatoryPortAttr()
static DictionaryAttr circt::getMandatoryPortAttr (MLIRContext * ctx, StringRef name) static
Creates a DictionaryAttr containing a unit attribute 'name'.
Used for defining mandatory port attributes for calyx::ComponentOp's.
Definition at line 121 of file SCFToCalyx.cpp.
References circt::calyx::direction::get().
Referenced by addMandatoryComponentPorts().
hash_value()
inline ::llvm::hash_code circt::hash_value (const FieldRef & fieldRef)
Get a hash code for a FieldRef.
Definition at line 74 of file FieldRef.h.
References circt::FieldRef::getFieldID(), and circt::FieldRef::getValue().
Referenced by llvm::DenseMapInfo< circt::FieldRef >::getHashValue(), llvm::DenseMapInfo< Dependence >::getHashValue(), and llvm::DenseMapInfo< ResetSignal >::getHashValue().
matchConstantOp()
static bool circt::matchConstantOp (Operation * op, APInt & value) static
Tries to match a constant value defined by op.
If the match was successful, returns true and binds the constant to 'value'. If unsuccessful, the value is unmodified.
Definition at line 99 of file SCFToCalyx.cpp.
Referenced by circt::BuildOpGroups::buildOp().
noStoresToMemory()
static bool circt::noStoresToMemory (Value memref) static
Returns true if there are no memref::StoreOp uses with the referenced memory.
Definition at line 113 of file SCFToCalyx.cpp.
Referenced by circt::BuildOpGroups::buildOp().
populateLLHDToLLVMConversionPatterns()
void circt::populateLLHDToLLVMConversionPatterns (mlir::LLVMTypeConverter & converter, RewritePatternSet & patterns, size_t & sigCounter, size_t & regCounter)
Get the LLHD to LLVM conversion patterns.
registerAllDialects()
void circt::registerAllDialects (mlir::DialectRegistry & registry) inline
Definition at line 35 of file InitAllDialects.h.
registerAllPasses()
void circt::registerAllPasses () inline
Definition at line 31 of file InitAllPasses.h.
References circt::llhd::initLLHDTransformationPasses(), circt::esi::registerESIPasses(), circt::msft::registerMSFTPasses(), registerPasses(), and circt::seq::registerSeqPasses().
registerAllTranslations()
void circt::registerAllTranslations () inline
Definition at line 29 of file InitAllTranslations.h.
References circt::esi::registerESITranslations(), circt::firrtl::registerFromFIRFileTranslation(), circt::calyx::registerToCalyxTranslation(), circt::firrtl::registerToFIRFileTranslation(), and circt::llhd::registerToVerilogTranslation().
registerLoweringCLOptions()
void circt::registerLoweringCLOptions ()
Register commandline options for the verilog emitter.
Definition at line 153 of file LoweringOptions.cpp.
References clOptions.
sextOrSelfZeroWidth()
APInt circt::sextOrSelfZeroWidth (APInt value, unsigned width)
A safe version of APInt::sextOrSelf that will NOT assert on zero-width signed APSInts.
Instead of asserting, this will zero extend.
Definition at line 18 of file APInt.cpp.
singleLoadFromMemory()
static bool circt::singleLoadFromMemory (Value memref) static
Returns true if there exists only a single memref::LoadOp which loads from the memory referenced by loadOp.
Definition at line 105 of file SCFToCalyx.cpp.
Referenced by circt::BuildOpGroups::buildOp(), and circt::LateSSAReplacement::PartiallyLowerFuncToComp().