CIRCT: sost Namespace Reference
sost Namespace Reference
Functions
void addAttributes (OperationState &result, int size, Type dataType, bool alwaysControl=false)
static ParseResult parseIntInSquareBrackets (OpAsmParser &parser, int &v)
static ParseResult parseOperation (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operands, OperationState &result, int &size, Type &type, bool explicitSize, bool alwaysControl=false)
static void printOp (OpAsmPrinter &p, Operation *op, bool explicitSize)
Function Documentation
addAttributes()
void sost::addAttributes (OperationState & result, int size, Type dataType, bool alwaysControl = false)
Definition at line 56 of file HandshakeOps.cpp.
References circt::calyx::direction::get(), and size().
Referenced by parseMuxOp(), and parseOperation().
parseIntInSquareBrackets()
static ParseResult sost::parseIntInSquareBrackets (OpAsmParser & parser, int & v) static
Definition at line 66 of file HandshakeOps.cpp.
Referenced by parseOperation().
parseOperation()
static ParseResult sost::parseOperation (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & operands, OperationState & result, int & size, Type & type, bool explicitSize, bool alwaysControl = false) static
Definition at line 73 of file HandshakeOps.cpp.
References addAttributes(), parseIntInSquareBrackets(), and size().
Referenced by parseBranchOp(), parseBufferOp(), parseControlMergeOp(), parseForkOp(), parseJoinOp(), parseMergeOp(), and parseSinkOp().
printOp()
static void sost::printOp (OpAsmPrinter & p, Operation * op, bool explicitSize) static
Definition at line 93 of file HandshakeOps.cpp.
References size().
Referenced by circt::firrtl::foldWhenEncodedVerifOp(), printBranchOp(), printBufferOp(), printControlMergeOp(), printForkOp(), printJoinOp(), printLazyForkOp(), printMergeOp(), and printSinkOp().