CIRCT: lib/Scheduling/TestPasses.cpp File Reference
TestPasses.cpp File Reference
#include "circt/Scheduling/Algorithms.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
Namespaces
circt
circt::test
Functions
static SmallVector< SmallVector< unsigned > > parseArrayOfArrays (ArrayAttr attr)
static SmallVector< std::pair< llvm::StringRef, unsigned > > parseArrayOfDicts (ArrayAttr attr, StringRef key)
static void constructProblem (Problem &prob, FuncOp func)
static void constructCyclicProblem (CyclicProblem &prob, FuncOp func)
static void constructSharedOperatorsProblem (SharedOperatorsProblem &prob, FuncOp func)
static void emitSchedule (Problem &prob, StringRef attrName, OpBuilder &builder)
void circt::test::registerSchedulingTestPasses ()
Function Documentation
constructCyclicProblem()
static void constructCyclicProblem (CyclicProblem & prob, FuncOp func) static
Definition at line 88 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), parseArrayOfArrays(), and circt::scheduling::CyclicProblem::setDistance().
constructProblem()
static void constructProblem (Problem & prob, FuncOp func) static
Definition at line 48 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), circt::scheduling::Problem::getOrInsertOperatorType(), circt::scheduling::Problem::insertDependence(), circt::scheduling::Problem::insertOperation(), parseArrayOfArrays(), parseArrayOfDicts(), circt::scheduling::Problem::setLatency(), and circt::scheduling::Problem::setLinkedOperatorType().
constructSharedOperatorsProblem()
static void constructSharedOperatorsProblem (SharedOperatorsProblem & prob, FuncOp func) static
Definition at line 104 of file TestPasses.cpp.
References circt::scheduling::Problem::getOrInsertOperatorType(), parseArrayOfDicts(), and circt::scheduling::SharedOperatorsProblem::setLimit().
emitSchedule()
static void emitSchedule (Problem & prob, StringRef attrName, OpBuilder & builder) static
Definition at line 115 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), and circt::scheduling::Problem::getStartTime().
parseArrayOfArrays()
static SmallVector<SmallVector<unsigned> > parseArrayOfArrays (ArrayAttr attr) static
Definition at line 26 of file TestPasses.cpp.
Referenced by constructCyclicProblem(), and constructProblem().
parseArrayOfDicts()
static SmallVector<std::pair<llvm::StringRef, unsigned> > parseArrayOfDicts (ArrayAttr attr, StringRef key) static
Definition at line 37 of file TestPasses.cpp.
Referenced by constructProblem(), and constructSharedOperatorsProblem().