CIRCT: lib/Conversion/StandardToHandshake/StandardToHandshake.cpp File Reference
StandardToHandshake.cpp File Reference
#include "circt/Conversion/StandardToHandshake.h"
#include "../PassDetail.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Dialect/StaticLogic/StaticLogic.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
Classes
class LowerFuncOpTarget< TFuncOp >
struct PartialLowerFuncOp< TFuncOp >
Default function for partial lowering of handshake::FuncOp.
struct HandshakeCanonicalizePattern
Macros
#define returnOnError(logicalResult)
Typedefs
typedef DenseMap< Block *, std::vector< Value > > BlockValues
typedef DenseMap< Block *, std::vector< Operation * > > BlockOps
typedef DenseMap< Value, Operation * > blockArgPairs
typedef llvm::MapVector< Value, std::vector< Operation * > > MemRefToMemoryAccessOp
Functions
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
LogicalResult setControlOnlyPath (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
BlockValues getBlockUses (handshake::FuncOp f)
BlockValues getBlockDefs (handshake::FuncOp f)
std::vector< Value > vectorUnion (ArrayRef< Value > v1, ArrayRef< Value > v2)
std::vector< Value > vectorDiff (ArrayRef< Value > v1, ArrayRef< Value > v2)
BlockValues livenessAnalysis (handshake::FuncOp f)
unsigned getBlockPredecessorCount (Block *block)
Operation * insertMerge (Block *block, Value val, ConversionPatternRewriter &rewriter)
BlockOps insertMergeOps (handshake::FuncOp f, BlockValues blockLiveIns, blockArgPairs &mergePairs, ConversionPatternRewriter &rewriter)
bool blockHasSrcOp (Value val, Block *block)
Value getMergeOperand (Operation *op, Block *predBlock, BlockOps blockMerges)
void removeBlockOperands (handshake::FuncOp f)
template<typename TOp >
Operation * getFirstOp (Block *block)
Returns the first occurance of an operation of type TOp, else, returns null op.
Operation * getControlMerge (Block *block)
Operation * getStartOp (Block *block)
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs &mergePairs)
LogicalResult addMergeOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
bool isLiveOut (Value val)
int getBranchCount (Value val, Block *block)
Value getSuccResult (Operation *termOp, Operation *newOp, Block *succBlock)
LogicalResult addBranchOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
LogicalResult connectConstantsToControl (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
LogicalResult checkUseCount (Operation *op, Value res)
LogicalResult checkSuccessorBlocks (Operation *op, Value res)
LogicalResult checkMergePredecessors (MergeLikeOpInterface mergeOp)
LogicalResult checkDataflowConversion (handshake::FuncOp f)
Value getBlockControlValue (Block *block)
LogicalResult getOpMemRef (Operation *op, Value &out)
bool isMemoryOp (Operation *op)
LogicalResult replaceMemoryOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter, MemRefToMemoryAccessOp &memRefOps)
std::vector< Block * > getOperationBlocks (ArrayRef< Operation * > ops)
SmallVector< Value, 8 > getResultsToMemory (Operation *op)
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addJoinOps (ConversionPatternRewriter &rewriter, ArrayRef< Value > controlVals)
std::vector< Value > getControlValues (ArrayRef< Operation * > memOps)
void addValueToOperands (Operation *op, Value val)
void setLoadDataInputs (ArrayRef< Operation * > memOps, Operation *memOp)
LogicalResult setJoinControlInputs (ArrayRef< Operation * > memOps, Operation *memOp, int offset, ArrayRef< int > cntrlInd)
void setMemOpControlInputs (ConversionPatternRewriter &rewriter, ArrayRef< Operation * > memOps, Operation *memOp, int offset, ArrayRef< int > cntrlInd)
LogicalResult connectToMemory (handshake::FuncOp f, MemRefToMemoryAccessOp memRefOps, bool lsq, ConversionPatternRewriter &rewriter)
static Operation * findStartOp (Region *region)
template<typename TConv , typename TFuncOp , typename... TArgs>
LogicalResult lowerToHandshake (TFuncOp op, MLIRContext *context, TArgs &...args)
Calls to rewriter.replaceOpWithNewOp are invalid, given the commitment of all side-effects of of any op replacements are deferred until after the return of matchAndRewrite.
template<typename TFuncOp >
LogicalResult partiallyLowerFuncOp (const std::function< LogicalResult(TFuncOp, ConversionPatternRewriter &)> &loweringFunc, MLIRContext *ctx, TFuncOp funcOp)
LogicalResult rewriteAffineFor (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
Rewrite affine.for operations in a handshake.func into its representations as a CFG in the standard dialect.
LogicalResult replaceCallOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
LogicalResult lowerFuncOp (mlir::FuncOp funcOp, MLIRContext *ctx)
Macro Definition Documentation
returnOnError
#define returnOnError (logicalResult)
Value:
  if (failed(logicalResult))                                                   \
    return logicalResult;
Definition at line 1407 of file StandardToHandshake.cpp.
Typedef Documentation
blockArgPairs
typedef DenseMap<Value, Operation *> blockArgPairs
Definition at line 48 of file StandardToHandshake.cpp.
BlockOps
typedef DenseMap<Block *, std::vector<Operation *> > BlockOps
Definition at line 47 of file StandardToHandshake.cpp.
BlockValues
typedef DenseMap<Block *, std::vector<Value> > BlockValues
Definition at line 46 of file StandardToHandshake.cpp.
MemRefToMemoryAccessOp
typedef llvm::MapVector<Value, std::vector<Operation *> > MemRefToMemoryAccessOp
Definition at line 716 of file StandardToHandshake.cpp.
Function Documentation
addBranchOps()
LogicalResult addBranchOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 476 of file StandardToHandshake.cpp.
References getBranchCount(), getSuccResult(), and isLiveOut().
Referenced by lowerFuncOp().
addJoinOps()
void addJoinOps (ConversionPatternRewriter & rewriter, ArrayRef< Value > controlVals)
Definition at line 911 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
addLazyForks()
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 846 of file StandardToHandshake.cpp.
References getBlockControlValue(), and circt::handshake::insertFork().
Referenced by connectToMemory().
addMemOpForks()
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 855 of file StandardToHandshake.cpp.
References circt::handshake::insertFork().
Referenced by connectToMemory().
addMergeOps()
LogicalResult addMergeOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 418 of file StandardToHandshake.cpp.
References insertMergeOps(), livenessAnalysis(), and reconnectMergeOps().
Referenced by lowerFuncOp().
addValueToOperands()
void addValueToOperands (Operation * op, Value val)
Definition at line 944 of file StandardToHandshake.cpp.
Referenced by setJoinControlInputs(), setLoadDataInputs(), and setMemOpControlInputs().
blockHasSrcOp()
bool blockHasSrcOp (Value val, Block * block)
Definition at line 288 of file StandardToHandshake.cpp.
Referenced by getMergeOperand().
checkDataflowConversion()
LogicalResult checkDataflowConversion (handshake::FuncOp f)
Definition at line 660 of file StandardToHandshake.cpp.
References checkMergePredecessors(), checkSuccessorBlocks(), and checkUseCount().
Referenced by lowerFuncOp().
checkMergePredecessors()
LogicalResult checkMergePredecessors (MergeLikeOpInterface mergeOp)
Definition at line 620 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
Referenced by checkDataflowConversion().
checkSuccessorBlocks()
LogicalResult checkSuccessorBlocks (Operation * op, Value res)
Definition at line 594 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
checkUseCount()
LogicalResult checkUseCount (Operation * op, Value res)
Definition at line 579 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
connectConstantsToControl()
LogicalResult connectConstantsToControl (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 546 of file StandardToHandshake.cpp.
References getControlMerge(), and getStartOp().
Referenced by lowerFuncOp().
connectToMemory()
LogicalResult connectToMemory (handshake::FuncOp f, MemRefToMemoryAccessOp memRefOps, bool lsq, ConversionPatternRewriter & rewriter)
Definition at line 1015 of file StandardToHandshake.cpp.
References addJoinOps(), addLazyForks(), addMemOpForks(), getControlValues(), getResultsToMemory(), removeAllocOps(), removeRedundantSinks(), setJoinControlInputs(), setLoadDataInputs(), and setMemOpControlInputs().
Referenced by lowerFuncOp().
findStartOp()
static Operation* findStartOp (Region * region) static
Definition at line 1147 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
getBlockControlValue()
Value getBlockControlValue (Block * block)
Definition at line 681 of file StandardToHandshake.cpp.
Referenced by addLazyForks(), getControlValues(), and setJoinControlInputs().
getBlockDefs()
BlockValues getBlockDefs (handshake::FuncOp f)
Definition at line 138 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBlockPredecessorCount()
unsigned getBlockPredecessorCount (Block * block)
Definition at line 225 of file StandardToHandshake.cpp.
Referenced by checkMergePredecessors(), insertMerge(), and reconnectMergeOps().
getBlockUses()
BlockValues getBlockUses (handshake::FuncOp f)
Definition at line 107 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBranchCount()
int getBranchCount (Value val, Block * block)
Definition at line 447 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
getControlMerge()
Operation* getControlMerge (Block * block)
Definition at line 358 of file StandardToHandshake.cpp.
Referenced by connectConstantsToControl(), reconnectMergeOps(), replaceCallOps(), and setMemOpControlInputs().
getControlValues()
std::vector<Value> getControlValues (ArrayRef< Operation * > memOps)
Definition at line 928 of file StandardToHandshake.cpp.
References getBlockControlValue().
Referenced by connectToMemory().
getFirstOp()
template<typename TOp > Operation* getFirstOp (Block * block)
Returns the first occurance of an operation of type TOp, else, returns null op.
Definition at line 351 of file StandardToHandshake.cpp.
getMergeOperand()
Value getMergeOperand (Operation * op, Block * predBlock, BlockOps blockMerges)
Definition at line 299 of file StandardToHandshake.cpp.
References blockHasSrcOp().
Referenced by reconnectMergeOps().
getOperationBlocks()
std::vector<Block *> getOperationBlocks (ArrayRef< Operation * > ops)
Definition at line 815 of file StandardToHandshake.cpp.
getOpMemRef()
LogicalResult getOpMemRef (Operation * op, Value & out)
Definition at line 696 of file StandardToHandshake.cpp.
Referenced by replaceMemoryOps().
getResultsToMemory()
SmallVector<Value, 8> getResultsToMemory (Operation * op)
Definition at line 828 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
getStartOp()
Operation* getStartOp (Block * block)
Definition at line 362 of file StandardToHandshake.cpp.
Referenced by connectConstantsToControl(), replaceCallOps(), and setMemOpControlInputs().
getSuccResult()
Value getSuccResult (Operation * termOp, Operation * newOp, Block * succBlock)
Definition at line 462 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
insertMerge()
Operation* insertMerge (Block * block, Value val, ConversionPatternRewriter & rewriter)
Definition at line 233 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
Referenced by insertMergeOps().
insertMergeOps()
BlockOps insertMergeOps (handshake::FuncOp f, BlockValues blockLiveIns, blockArgPairs & mergePairs, ConversionPatternRewriter & rewriter)
Definition at line 260 of file StandardToHandshake.cpp.
References insertMerge().
Referenced by addMergeOps().
isLiveOut()
bool isLiveOut (Value val)
Definition at line 434 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
isMemoryOp()
bool isMemoryOp (Operation * op)
Definition at line 711 of file StandardToHandshake.cpp.
Referenced by replaceMemoryOps().
livenessAnalysis()
BlockValues livenessAnalysis (handshake::FuncOp f)
Definition at line 181 of file StandardToHandshake.cpp.
References getBlockDefs(), getBlockUses(), vectorDiff(), and vectorUnion().
Referenced by addMergeOps().
lowerFuncOp()
LogicalResult lowerFuncOp (mlir::FuncOp funcOp, MLIRContext * ctx)
Definition at line 1411 of file StandardToHandshake.cpp.
References addBranchOps(), circt::handshake::addForkOps(), addMergeOps(), circt::handshake::addSinkOps(), checkDataflowConversion(), connectConstantsToControl(), connectToMemory(), findStartOp(), replaceCallOps(), replaceMemoryOps(), returnOnError, rewriteAffineFor(), and setControlOnlyPath().
lowerToHandshake()
template<typename TConv , typename TFuncOp , typename... TArgs> LogicalResult lowerToHandshake (TFuncOp op, MLIRContext * context, TArgs &... args)
Calls to rewriter.replaceOpWithNewOp are invalid, given the commitment of all side-effects of of any op replacements are deferred until after the return of matchAndRewrite.
This is incompatible with the design of the StandardToHandshake pass, which converts a top-level FuncOp in a sequential manner, assuming any side-effects from operand replacements (in particular rewriting of SSA use-def's) are performed instantly. The following convenience function wraps a replacement pattern TConv inside a distinct call to applyPartialConversion, ensuring that any call to rewrite replacement methods have been fully performed after this call. Each replacement pattern is expected to define their own conversion target, to guide pattern matching.
Definition at line 1226 of file StandardToHandshake.cpp.
partiallyLowerFuncOp()
template<typename TFuncOp > LogicalResult partiallyLowerFuncOp (const std::function< LogicalResult(TFuncOp, ConversionPatternRewriter &)> & loweringFunc, MLIRContext * ctx, TFuncOp funcOp)
Definition at line 1240 of file StandardToHandshake.cpp.
reconnectMergeOps()
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs & mergePairs)
Definition at line 364 of file StandardToHandshake.cpp.
References getBlockPredecessorCount(), getControlMerge(), getMergeOperand(), and removeBlockOperands().
Referenced by addMergeOps().
removeAllocOps()
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
TODO(mortbopet): use explicit template parameter when moving to C++20
Definition at line 870 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
removeBasicBlocks()
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
This allows the result to be a valid graph region, since multi-basic block regions are not allowed to be graph regions currently.
Definition at line 53 of file StandardToHandshake.cpp.
removeBlockOperands()
void removeBlockOperands (handshake::FuncOp f)
Definition at line 336 of file StandardToHandshake.cpp.
Referenced by reconnectMergeOps().
removeRedundantSinks()
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 890 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
replaceCallOps()
LogicalResult replaceCallOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
An instance is activated whenever control arrives at the basic block of the source callOp.
Definition at line 1380 of file StandardToHandshake.cpp.
References getControlMerge(), and getStartOp().
Referenced by lowerFuncOp().
replaceMemoryOps()
LogicalResult replaceMemoryOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter, MemRefToMemoryAccessOp & memRefOps)
Definition at line 722 of file StandardToHandshake.cpp.
References getOpMemRef(), and isMemoryOp().
Referenced by lowerFuncOp().
rewriteAffineFor()
LogicalResult rewriteAffineFor (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Rewrite affine.for operations in a handshake.func into its representations as a CFG in the standard dialect.
Affine expressions in loop bounds will be expanded to code in the standard dialect that actually computes them. We combine the lowering of affine loops in the following two conversions: AffineToStandard, SCFToStandard into this function. The affine memory operations will be preserved until other rewrite functions, e.g.,replaceMemoryOps, are called. Any affine analysis, e.g., getting dependence information, should be carried out before calling this function; otherwise, the affine for loops will be destructed and key information will be missing.
Definition at line 1260 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
setControlOnlyPath()
LogicalResult setControlOnlyPath (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 79 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
setJoinControlInputs()
LogicalResult setJoinControlInputs (ArrayRef< Operation * > memOps, Operation * memOp, int offset, ArrayRef< int > cntrlInd)
Definition at line 960 of file StandardToHandshake.cpp.
References addValueToOperands(), and getBlockControlValue().
Referenced by connectToMemory().
setLoadDataInputs()
void setLoadDataInputs (ArrayRef< Operation * > memOps, Operation * memOp)
Definition at line 951 of file StandardToHandshake.cpp.
References addValueToOperands().
Referenced by connectToMemory().
setMemOpControlInputs()
void setMemOpControlInputs (ConversionPatternRewriter & rewriter, ArrayRef< Operation * > memOps, Operation * memOp, int offset, ArrayRef< int > cntrlInd)
Definition at line 977 of file StandardToHandshake.cpp.
References addValueToOperands(), getControlMerge(), and getStartOp().
Referenced by connectToMemory().
vectorDiff()
std::vector<Value> vectorDiff (ArrayRef< Value > v1, ArrayRef< Value > v2)
Definition at line 170 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
vectorUnion()
std::vector<Value> vectorUnion (ArrayRef< Value > v1, ArrayRef< Value > v2)
Definition at line 158 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().