CIRCT: lib/Dialect/StaticLogic/StaticLogicOps.cpp File Reference
StaticLogicOps.cpp File Reference
#include "circt/Dialect/StaticLogic/StaticLogic.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "circt/Dialect/StaticLogic/StaticLogicDialect.cpp.inc"
#include "circt/Dialect/StaticLogic/StaticLogic.cpp.inc"
Macros
#define GET_OP_CLASSES
#define GET_OP_LIST
Functions
static ParseResult parsePipelineWhileOp (OpAsmParser &parser, OperationState &result)
static void printPipelineWhileOp (OpAsmPrinter &p, PipelineWhileOp op)
static LogicalResult verifyPipelineWhileOp (PipelineWhileOp op)
static LogicalResult verifyPipelineRegisterOp (PipelineRegisterOp op)
static LogicalResult verifyPipelineTerminatorOp (PipelineTerminatorOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 251 of file StaticLogicOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parsePipelineWhileOp()
static ParseResult parsePipelineWhileOp (OpAsmParser & parser, OperationState & result) static
Definition at line 28 of file StaticLogicOps.cpp.
printPipelineWhileOp()
static void printPipelineWhileOp (OpAsmPrinter & p, PipelineWhileOp op) static
Definition at line 70 of file StaticLogicOps.cpp.
References circt::calyx::direction::get().
verifyPipelineRegisterOp()
static LogicalResult verifyPipelineRegisterOp (PipelineRegisterOp op) static
Definition at line 193 of file StaticLogicOps.cpp.
verifyPipelineTerminatorOp()
static LogicalResult verifyPipelineTerminatorOp (PipelineTerminatorOp op) static
Definition at line 215 of file StaticLogicOps.cpp.
verifyPipelineWhileOp()
static LogicalResult verifyPipelineWhileOp (PipelineWhileOp op) static
Definition at line 94 of file StaticLogicOps.cpp.
References circt::calyx::direction::get(), and if().