CIRCT: circt::sv::CaseZPattern Struct Reference
circt::sv::CaseZPattern Struct Reference
#include <SVOps.h>
Public Member Functions
size_t getWidth () const
CaseZPatternBit getBit (size_t bitNumber) const
Return the specified bit, bit 0 is the least significant bit.
bool isDefault () const
Return true if this pattern always matches.
CaseZPattern (ArrayRef< CaseZPatternBit > bits, MLIRContext *context)
Get a CaseZPattern from a specified list of CaseZPatternBit.
CaseZPattern (const APInt &value, MLIRContext *context)
Get a CaseZPattern for the specified constant value.
CaseZPattern (IntegerAttr attr)
Get a CaseZPattern with a correctly encoded attribute.
Static Public Member Functions
static CaseZPattern getDefault (unsigned width, MLIRContext *context)
Public Attributes
IntegerAttr attr
Detailed Description
Definition at line 48 of file SVOps.h.
Constructor & Destructor Documentation
CaseZPattern() [1/3]
CaseZPattern::CaseZPattern (ArrayRef< CaseZPatternBit > bits, MLIRContext * context)
Get a CaseZPattern from a specified list of CaseZPatternBit.
Bits are specified in most least significant order - element zero is the least significant bit.
Definition at line 599 of file SVOps.cpp.
References attr, bits(), and circt::calyx::direction::get().
Referenced by getDefault().
CaseZPattern() [2/3]
CaseZPattern::CaseZPattern (const APInt & value, MLIRContext * context)
Get a CaseZPattern for the specified constant value.
Definition at line 588 of file SVOps.cpp.
CaseZPattern() [3/3]
circt::sv::CaseZPattern::CaseZPattern (IntegerAttr attr) inline
Get a CaseZPattern with a correctly encoded attribute.
Definition at line 69 of file SVOps.h.
Member Function Documentation
getBit()
auto CaseZPattern::getBit (size_t bitNumber) const
Return the specified bit, bit 0 is the least significant bit.
Definition at line 564 of file SVOps.cpp.
Referenced by isDefault().
getDefault()
CaseZPattern CaseZPattern::getDefault (unsigned width, MLIRContext * context) static
Definition at line 591 of file SVOps.cpp.
References circt::sv::Any, and CaseZPattern().
getWidth()
size_t circt::sv::CaseZPattern::getWidth () const inline
Definition at line 52 of file SVOps.h.
References attr.
Referenced by isDefault().
isDefault()
bool CaseZPattern::isDefault () const
Return true if this pattern always matches.
Definition at line 569 of file SVOps.cpp.
References circt::sv::Any, getBit(), and getWidth().
Member Data Documentation
attr
IntegerAttr circt::sv::CaseZPattern::attr
Definition at line 49 of file SVOps.h.
Referenced by CaseZPattern(), and getWidth().
The documentation for this struct was generated from the following files:
include/circt/Dialect/SV/SVOps.h
lib/Dialect/SV/SVOps.cpp