CIRCT: llvm::GraphTraits< circt::firrtl::InstanceGraphNode * > Struct Reference
llvm::GraphTraits< circt::firrtl::InstanceGraphNode * > Struct Reference
#include <InstanceGraph.h>
Public Types
using NodeType = circt::firrtl::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::iterator, decltype(&getChild)>
Static Public Member Functions
static NodeRef getChild (const circt::firrtl::InstanceRecord *record)
static NodeRef getEntryNode (NodeRef node)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 243 of file InstanceGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::ChildIteratorType = llvm::mapped_iterator<NodeType::iterator, decltype(&getChild)>
Definition at line 253 of file InstanceGraph.h.
NodeRef
using llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::NodeRef = NodeType *
Definition at line 245 of file InstanceGraph.h.
NodeType
using llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::NodeType = circt::firrtl::InstanceGraphNode
Definition at line 244 of file InstanceGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::child_begin (NodeRef node) inline static
Definition at line 256 of file InstanceGraph.h.
References circt::firrtl::InstanceGraphNode::begin().
child_end()
static ChildIteratorType llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::child_end (NodeRef node) inline static
Definition at line 259 of file InstanceGraph.h.
References circt::firrtl::InstanceGraphNode::end().
getChild()
static NodeRef llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::getChild (const circt::firrtl::InstanceRecord * record) inline static
Definition at line 248 of file InstanceGraph.h.
References circt::firrtl::InstanceRecord::getTarget().
getEntryNode()
static NodeRef llvm::GraphTraits< circt::firrtl::InstanceGraphNode * >::getEntryNode (NodeRef node) inline static
Definition at line 255 of file InstanceGraph.h.
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/InstanceGraph.h