CIRCT: circt::LoweringOptions Struct Reference
circt::LoweringOptions Struct Reference
Options which control the emission from CIRCT to Verilog.
#include <LoweringOptions.h>
Public Types
enum { DEFAULT_TOKEN_NUMBER = 40000 }
This parameter limits the maximum number of tokes per one expression.
enum { DEFAULT_LINE_LENGTH = 90 }
This is the target width of lines in an emitted Verilog source file in columns.
using ErrorHandlerT = function_ref< void(llvm::Twine)>
Error callback type used to indicate errors parsing the options string.
Public Member Functions
LoweringOptions ()=default
Create a LoweringOptions with the default values.
LoweringOptions (StringRef options, ErrorHandlerT errorHandler)
Create a LoweringOptions and read in options from a string, overriding only the set options in the string.
LoweringOptions (mlir::ModuleOp module)
Create a LoweringOptions with values loaded from an MLIR ModuleOp.
void parse (StringRef options, ErrorHandlerT callback)
Read in options from a string, overriding only the set options in the string.
std::string toString () const
Returns a string representation of the options.
void setAsAttribute (mlir::ModuleOp module)
Write the verilog emitter options to a module's attributes.
void parseFromAttribute (mlir::ModuleOp module)
Load any emitter options from the module.
Static Public Member Functions
static StringAttr getAttributeFrom (ModuleOp module)
Return the value of the circt.loweringOptions in the specified module if present, or a null attribute if not.
Public Attributes
bool noAlwaysComb = false
If true, emits sv.alwayscomb as Verilog always @(*) statements.
bool allowExprInEventControl = false
If true, expressions are allowed in the sensitivity list of always statements, otherwise they are forced to be simple wires.
bool disallowPackedArrays = false
If true, eliminate packed arrays for tools that don't support them (e.g.
bool disallowLocalVariables = false
If true, do not emit SystemVerilog locally scoped "automatic" or logic declarations - emit top level wire and reg's instead.
bool enforceVerifLabels = false
If true, verification statements like assert, assume, and cover will always be emitted with a label.
unsigned maximumNumberOfTokensPerExpression = DEFAULT_TOKEN_NUMBER
unsigned emittedLineLength = DEFAULT_LINE_LENGTH
Detailed Description
Options which control the emission from CIRCT to Verilog.
Definition at line 26 of file LoweringOptions.h.
Member Typedef Documentation
ErrorHandlerT
using circt::LoweringOptions::ErrorHandlerT = function_ref<void(llvm::Twine)>
Error callback type used to indicate errors parsing the options string.
Definition at line 28 of file LoweringOptions.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
This parameter limits the maximum number of tokes per one expression.
https://github.com/verilator/verilator/issues/2752
Enumerator
DEFAULT_TOKEN_NUMBER
Definition at line 86 of file LoweringOptions.h.
anonymous enum
anonymous enum
This is the target width of lines in an emitted Verilog source file in columns.
Enumerator
DEFAULT_LINE_LENGTH
Definition at line 91 of file LoweringOptions.h.
Constructor & Destructor Documentation
LoweringOptions() [1/3]
circt::LoweringOptions::LoweringOptions () default
Create a LoweringOptions with the default values.
LoweringOptions() [2/3]
LoweringOptions::LoweringOptions (StringRef options, ErrorHandlerT errorHandler)
Create a LoweringOptions and read in options from a string, overriding only the set options in the string.
Definition at line 25 of file LoweringOptions.cpp.
References parse().
LoweringOptions() [3/3]
LoweringOptions::LoweringOptions (mlir::ModuleOp module)
Create a LoweringOptions with values loaded from an MLIR ModuleOp.
This loads a string attribute with the key circt.loweringOptions. If there is an error parsing the attribute this will print an error using the ModuleOp.
Definition at line 30 of file LoweringOptions.cpp.
References parseFromAttribute().
Member Function Documentation
getAttributeFrom()
StringAttr LoweringOptions::getAttributeFrom (ModuleOp module) static
Return the value of the circt.loweringOptions in the specified module if present, or a null attribute if not.
Definition at line 102 of file LoweringOptions.cpp.
Referenced by parseFromAttribute().
parse()
void LoweringOptions::parse (StringRef options, ErrorHandlerT callback)
Read in options from a string, overriding only the set options in the string.
Definition at line 34 of file LoweringOptions.cpp.
References allowExprInEventControl, DEFAULT_LINE_LENGTH, DEFAULT_TOKEN_NUMBER, disallowLocalVariables, disallowPackedArrays, emittedLineLength, enforceVerifLabels, maximumNumberOfTokensPerExpression, and noAlwaysComb.
Referenced by LoweringOptions(), and parseFromAttribute().
parseFromAttribute()
void LoweringOptions::parseFromAttribute (mlir::ModuleOp module)
Load any emitter options from the module.
If there is an error validating the attribute, this will print an error using the ModuleOp.
Definition at line 111 of file LoweringOptions.cpp.
References getAttributeFrom(), and parse().
Referenced by LoweringOptions().
setAsAttribute()
void LoweringOptions::setAsAttribute (mlir::ModuleOp module)
Write the verilog emitter options to a module's attributes.
Definition at line 106 of file LoweringOptions.cpp.
References circt::calyx::direction::get(), and toString().
toString()
std::string LoweringOptions::toString () const
Returns a string representation of the options.
Definition at line 74 of file LoweringOptions.cpp.
References allowExprInEventControl, DEFAULT_LINE_LENGTH, DEFAULT_TOKEN_NUMBER, disallowLocalVariables, disallowPackedArrays, emittedLineLength, enforceVerifLabels, maximumNumberOfTokensPerExpression, and noAlwaysComb.
Referenced by setAsAttribute().
Member Data Documentation
allowExprInEventControl
bool circt::LoweringOptions::allowExprInEventControl = false
If true, expressions are allowed in the sensitivity list of always statements, otherwise they are forced to be simple wires.
Some EDA tools rely on these being simple wires.
Definition at line 68 of file LoweringOptions.h.
Referenced by parse(), circt::ExportVerilog::prepareHWModule(), and toString().
disallowLocalVariables
bool circt::LoweringOptions::disallowLocalVariables = false
If true, do not emit SystemVerilog locally scoped "automatic" or logic declarations - emit top level wire and reg's instead.
Definition at line 76 of file LoweringOptions.h.
Referenced by getVerilogDeclWord(), parse(), circt::ExportVerilog::prepareHWModule(), and toString().
disallowPackedArrays
bool circt::LoweringOptions::disallowPackedArrays = false
If true, eliminate packed arrays for tools that don't support them (e.g.
Yosys).
Definition at line 72 of file LoweringOptions.h.
Referenced by parse(), and toString().
emittedLineLength
unsigned circt::LoweringOptions::emittedLineLength = DEFAULT_LINE_LENGTH
Definition at line 92 of file LoweringOptions.h.
Referenced by parse(), and toString().
enforceVerifLabels
bool circt::LoweringOptions::enforceVerifLabels = false
If true, verification statements like assert, assume, and cover will always be emitted with a label.
If the statement has no label in the IR, a generic one will be created. Some EDA tools require verification statements to be labeled.
Definition at line 82 of file LoweringOptions.h.
Referenced by parse(), and toString().
maximumNumberOfTokensPerExpression
unsigned circt::LoweringOptions::maximumNumberOfTokensPerExpression = DEFAULT_TOKEN_NUMBER
Definition at line 87 of file LoweringOptions.h.
Referenced by parse(), and toString().
noAlwaysComb
bool circt::LoweringOptions::noAlwaysComb = false
If true, emits sv.alwayscomb as Verilog always @(*) statements.
Otherwise, print them as always_comb.
Definition at line 63 of file LoweringOptions.h.
Referenced by parse(), and toString().
The documentation for this struct was generated from the following files:
include/circt/Support/LoweringOptions.h
lib/Support/LoweringOptions.cpp