CIRCT: circt::FuncOpConversion Struct Reference
circt::FuncOpConversion Struct Reference
Creates a new Calyx component for each FuncOp in the program.
Public Member Functions
LogicalResult PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override
Partial lowering implementation.
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
Public Member Functions inherited from circt::FuncOpPartialLoweringPattern
FuncOpPartialLoweringPattern (MLIRContext *context, LogicalResult &resRef, FuncMapping &_funcMap, ProgramLoweringState &pls)
LogicalResult partiallyLower (mlir::FuncOp funcOp, PatternRewriter &rewriter) const override final
calyx::ComponentOp * getComponent () const
ComponentLoweringState & getComponentState () const
ProgramLoweringState & progState () const
Public Member Functions inherited from circt::PartialLoweringPattern< mlir::FuncOp >
PartialLoweringPattern (MLIRContext *ctx, LogicalResult &resRef)
LogicalResult matchAndRewrite (mlir::FuncOp op, PatternRewriter &rewriter) const override
Additional Inherited Members
Protected Attributes inherited from circt::FuncOpPartialLoweringPattern
FuncMapping & funcMap
Detailed Description
Creates a new Calyx component for each FuncOp in the program.
Definition at line 1275 of file SCFToCalyx.cpp.
Member Function Documentation
FuncOpPartialLoweringPattern()
circt::FuncOpPartialLoweringPattern::FuncOpPartialLoweringPattern inline
Definition at line 599 of file SCFToCalyx.cpp.
PartiallyLowerFuncToComp()
LogicalResult circt::FuncOpConversion::PartiallyLowerFuncToComp (mlir::FuncOp funcOp, PatternRewriter & rewriter) const inline override virtual
Partial lowering implementation.
Maintain a mapping between funcOp input arguments and the port index which the argument will eventually map to.
Maintain a mapping between funcOp output indexes and the component output port index which the return value will eventually map to.
Maintain a mapping between an external memory argument (identified by a memref) and eventual component input- and output port indices that will map to the memory ports. The pair denotes the start index of the memory ports in the in- and output ports of the component. Ports are expected to be ordered in the same manner as they are added by appendPortsForExternalMemref.
Create I/O ports. Maintain separate in/out port vectors to determine which port index each function argument will eventually map to.
External memories
Single-port arguments
We've now recorded all necessary indices. Merge in- and output ports and add the required mandatory component ports.
Create a calyx::ComponentOp corresponding to the to-be-lowered function.
Store the function-to-component mapping.
Rewrite funcOp SSA argument values to the CompOp arguments.
Register external memories
Create a mapping for the in- and output ports using the Calyx memory port structure.
Register the external memory ports as a memory interface within the component.
Implements circt::FuncOpPartialLoweringPattern.
Definition at line 1279 of file SCFToCalyx.cpp.
References circt::addMandatoryComponentPorts(), circt::CalyxMemoryPorts::addrPorts, circt::appendPortsForExternalMemref(), circt::convIndexType(), circt::CalyxMemoryPorts::done, circt::calyx::direction::get(), circt::calyx::Input, circt::calyx::Output, circt::CalyxMemoryPorts::readData, circt::CalyxMemoryPorts::writeData, and circt::CalyxMemoryPorts::writeEn.
The documentation for this struct was generated from the following file:
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp