CIRCT: circt::ExportVerilog::GlobalNameTable Struct Reference
circt::ExportVerilog::GlobalNameTable Struct Reference
This class keeps track of global names at the module/interface level.
#include <ExportVerilogInternals.h>
Public Member Functions
GlobalNameTable (GlobalNameTable &&)=default
StringRef getPortVerilogName (Operation *module, const hw::PortInfo &port) const
Return the string to use for the specified port in the specified module.
StringRef getPortVerilogName (Operation *module, ssize_t portArgNum) const
Return the string to use for the specified port in the specified module.
StringRef getParameterVerilogName (Operation *module, StringAttr paramName) const
Return the string to use for the specified parameter name in the specified module.
StringRef getDeclarationVerilogName (Operation *op) const
Return the string to use for the specified declaration.
StringRef getInterfaceVerilogName (Operation *op) const
Return the string to use for the specified interface.
Private Member Functions
GlobalNameTable ()
GlobalNameTable (const GlobalNameTable &)=delete
void operator= (const GlobalNameTable &)=delete
void addRenamedPort (Operation *module, const hw::PortInfo &port, StringRef newName)
void addRenamedParam (Operation *module, StringAttr oldName, StringRef newName)
void addRenamedDeclaration (Operation *declOp, StringRef newName)
void addRenamedInterfaceOp (Operation *interfaceOp, StringRef newName)
Private Attributes
DenseMap< std::pair< Operation *, ssize_t >, StringAttr > renamedPorts
This contains entries for any ports that got renamed.
DenseMap< std::pair< Operation *, Attribute >, StringAttr > renamedParams
This contains entries for any parameters that got renamed.
DenseMap< Operation *, StringAttr > renamedDecls
This contains entries for any declarations that got renamed.
DenseMap< Operation *, StringAttr > renamedInterfaceOp
This contains entries for interface operations (sv.interface, sv.interface.signal, and sv.interface.modport) that need to be renamed due to conflicts.
Friends
class GlobalNameResolver
Detailed Description
This class keeps track of global names at the module/interface level.
It is built in a global pass over the entire design and then frozen to allow concurrent accesses.
Definition at line 32 of file ExportVerilogInternals.h.
Constructor & Destructor Documentation
GlobalNameTable() [1/3]
circt::ExportVerilog::GlobalNameTable::GlobalNameTable (GlobalNameTable &&) default
GlobalNameTable() [2/3]
circt::ExportVerilog::GlobalNameTable::GlobalNameTable () inline private
Definition at line 103 of file ExportVerilogInternals.h.
GlobalNameTable() [3/3]
circt::ExportVerilog::GlobalNameTable::GlobalNameTable (const GlobalNameTable &) private delete
Member Function Documentation
addRenamedDeclaration()
void circt::ExportVerilog::GlobalNameTable::addRenamedDeclaration (Operation * declOp, StringRef newName) inline private
Definition at line 119 of file ExportVerilogInternals.h.
References circt::calyx::direction::get(), and renamedDecls.
addRenamedInterfaceOp()
void circt::ExportVerilog::GlobalNameTable::addRenamedInterfaceOp (Operation * interfaceOp, StringRef newName) inline private
Definition at line 123 of file ExportVerilogInternals.h.
References circt::calyx::direction::get(), and renamedInterfaceOp.
addRenamedParam()
void circt::ExportVerilog::GlobalNameTable::addRenamedParam (Operation * module, StringAttr oldName, StringRef newName) inline private
Definition at line 113 of file ExportVerilogInternals.h.
References circt::calyx::direction::get(), and renamedParams.
addRenamedPort()
void circt::ExportVerilog::GlobalNameTable::addRenamedPort (Operation * module, const hw::PortInfo & port, StringRef newName) inline private
Definition at line 107 of file ExportVerilogInternals.h.
References circt::calyx::direction::get(), circt::hw::PortInfo::getId(), and renamedPorts.
getDeclarationVerilogName()
StringRef circt::ExportVerilog::GlobalNameTable::getDeclarationVerilogName (Operation * op) const inline
Return the string to use for the specified declaration.
The operation is commonly a declaration within the module, like WireOp and friends, which have a name attribute. Values may be renamed for a variety of reasons (e.g. conflicting with ports or Verilog keywords), and this returns the legalized name to use.
Definition at line 85 of file ExportVerilogInternals.h.
References circt::ExportVerilog::getDeclarationName(), and renamedDecls.
getInterfaceVerilogName()
StringRef circt::ExportVerilog::GlobalNameTable::getInterfaceVerilogName (Operation * op) const inline
Return the string to use for the specified interface.
Interfaces and their signals may be renamed for a variety of reasons (e.g. conflicting with Verilog keywords), and this returns the legalized name to use.
Definition at line 94 of file ExportVerilogInternals.h.
References renamedInterfaceOp.
getParameterVerilogName()
StringRef circt::ExportVerilog::GlobalNameTable::getParameterVerilogName (Operation * module, StringAttr paramName) const inline
Return the string to use for the specified parameter name in the specified module.
Parameters may be renamed for a variety of reasons (e.g. conflicting with ports or Verilog keywords), and this returns the legalized name to use.
Definition at line 74 of file ExportVerilogInternals.h.
References renamedParams.
getPortVerilogName() [1/2]
StringRef circt::ExportVerilog::GlobalNameTable::getPortVerilogName (Operation * module, const hw::PortInfo & port) const inline
Return the string to use for the specified port in the specified module.
Ports may be renamed for a variety of reasons (e.g. conflicting with Verilog keywords), and this returns the legalized name to use.
Definition at line 38 of file ExportVerilogInternals.h.
References circt::hw::PortInfo::getId(), circt::hw::PortInfo::name, and renamedPorts.
getPortVerilogName() [2/2]
StringRef circt::ExportVerilog::GlobalNameTable::getPortVerilogName (Operation * module, ssize_t portArgNum) const inline
Return the string to use for the specified port in the specified module.
Ports may be renamed for a variety of reasons (e.g. conflicting with Verilog keywords), and this returns the legalized name to use.
Definition at line 47 of file ExportVerilogInternals.h.
References circt::hw::getModuleNumInputs(), and renamedPorts.
operator=()
void circt::ExportVerilog::GlobalNameTable::operator= (const GlobalNameTable &) private delete
Friends And Related Function Documentation
GlobalNameResolver
friend class GlobalNameResolver friend
Definition at line 102 of file ExportVerilogInternals.h.
Member Data Documentation
renamedDecls
DenseMap<Operation *, StringAttr> circt::ExportVerilog::GlobalNameTable::renamedDecls private
This contains entries for any declarations that got renamed.
Definition at line 139 of file ExportVerilogInternals.h.
Referenced by addRenamedDeclaration(), and getDeclarationVerilogName().
renamedInterfaceOp
DenseMap<Operation *, StringAttr> circt::ExportVerilog::GlobalNameTable::renamedInterfaceOp private
This contains entries for interface operations (sv.interface, sv.interface.signal, and sv.interface.modport) that need to be renamed due to conflicts.
Definition at line 144 of file ExportVerilogInternals.h.
Referenced by addRenamedInterfaceOp(), and getInterfaceVerilogName().
renamedParams
DenseMap<std::pair<Operation *, Attribute>, StringAttr> circt::ExportVerilog::GlobalNameTable::renamedParams private
This contains entries for any parameters that got renamed.
The key is a moduleop/paramName tuple, the value is the name to use.
Definition at line 136 of file ExportVerilogInternals.h.
Referenced by addRenamedParam(), and getParameterVerilogName().
renamedPorts
DenseMap<std::pair<Operation *, ssize_t>, StringAttr> circt::ExportVerilog::GlobalNameTable::renamedPorts private
This contains entries for any ports that got renamed.
The key is a moduleop/portIdx tuple, the value is the name to use. The portIdx is the index of the port in the list returned by getAllModulePortInfos. Note, PortInfo::getId() returns ssize_t.
Definition at line 132 of file ExportVerilogInternals.h.
Referenced by addRenamedPort(), and getPortVerilogName().
The documentation for this struct was generated from the following file:
lib/Conversion/ExportVerilog/ExportVerilogInternals.h