CIRCT: lib/Dialect/SV/Transforms/SVExtractTestCode.cpp File Reference
SVExtractTestCode.cpp File Reference
#include "PassDetail.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVPasses.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include <set>
Functions
static void getBackwardSliceSimple (Operation *rootOp, SetVector< Operation * > &backwardSlice, std::function< bool(Operation *)> filter)
static void dataflowSlice (SetVector< Operation * > &ops, SetVector< Operation * > &results)
static void blockSlice (SetVector< Operation * > &ops, SetVector< Operation * > &blocks)
static SetVector< Operation * > computeCloneSet (SetVector< Operation * > &roots)
static StringRef getNameForPort (Value val, ArrayAttr modulePorts)
static hw::HWModuleOp createModuleForCut (hw::HWModuleOp op, SetVector< Value > &inputs, BlockAndValueMapping &cutMap, StringRef suffix, Attribute path, Attribute fileName)
static void setInsertPointToEndOrTerminator (OpBuilder &builder, Block *block)
static void addBlockMapping (BlockAndValueMapping &cutMap, Operation *oldOp, Operation *newOp)
static bool hasOoOArgs (hw::HWModuleOp newMod, Operation *op)
static void migrateOps (hw::HWModuleOp oldMod, hw::HWModuleOp newMod, SetVector< Operation * > &depOps, BlockAndValueMapping &cutMap)
Function Documentation
addBlockMapping()
static void addBlockMapping (BlockAndValueMapping & cutMap, Operation * oldOp, Operation * newOp) static
Definition at line 201 of file SVExtractTestCode.cpp.
Referenced by migrateOps().
blockSlice()
static void blockSlice (SetVector< Operation * > & ops, SetVector< Operation * > & blocks) static
Definition at line 94 of file SVExtractTestCode.cpp.
Referenced by computeCloneSet().
computeCloneSet()
static SetVector<Operation *> computeCloneSet (SetVector< Operation * > & roots) static
Definition at line 107 of file SVExtractTestCode.cpp.
References blockSlice(), and dataflowSlice().
createModuleForCut()
static hw::HWModuleOp createModuleForCut (hw::HWModuleOp op, SetVector< Value > & inputs, BlockAndValueMapping & cutMap, StringRef suffix, Attribute path, Attribute fileName) static
Definition at line 142 of file SVExtractTestCode.cpp.
References getNameForPort(), circt::hw::getVerilogModuleNameAttr(), and circt::hw::INPUT.
dataflowSlice()
static void dataflowSlice (SetVector< Operation * > & ops, SetVector< Operation * > & results) static
Definition at line 83 of file SVExtractTestCode.cpp.
References getBackwardSliceSimple().
Referenced by computeCloneSet().
getBackwardSliceSimple()
static void getBackwardSliceSimple (Operation * rootOp, SetVector< Operation * > & backwardSlice, std::function< bool(Operation *)> filter) static
Definition at line 35 of file SVExtractTestCode.cpp.
Referenced by dataflowSlice().
getNameForPort()
static StringRef getNameForPort (Value val, ArrayAttr modulePorts) static
Definition at line 127 of file SVExtractTestCode.cpp.
References seq::reg().
Referenced by createModuleForCut().
hasOoOArgs()
static bool hasOoOArgs (hw::HWModuleOp newMod, Operation * op) static
Definition at line 213 of file SVExtractTestCode.cpp.
Referenced by migrateOps().
migrateOps()
static void migrateOps (hw::HWModuleOp oldMod, hw::HWModuleOp newMod, SetVector< Operation * > & depOps, BlockAndValueMapping & cutMap) static
Definition at line 226 of file SVExtractTestCode.cpp.
References addBlockMapping(), hasOoOArgs(), and setInsertPointToEndOrTerminator().
setInsertPointToEndOrTerminator()
static void setInsertPointToEndOrTerminator (OpBuilder & builder, Block * block) static
Definition at line 192 of file SVExtractTestCode.cpp.
Referenced by migrateOps().