CIRCT: lib/Dialect/SV/SVOps.cpp File Reference
SVOps.cpp File Reference
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/SV/SV.cpp.inc"
#include "circt/Dialect/SV/SVEnums.cpp.inc"
#include "circt/Dialect/SV/SVStructs.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static Operation * lookupSymbolInNested (Operation *symbolTableOp, StringRef symbol)
Returns the operation registered with the given symbol name with the regions of 'symbolTableOp'.
static ParseResult parseImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static void getVerbatimExprAsmResultNames (Operation *op, function_ref< void(Value, StringRef)> setNameFn)
Get the asm name for sv.verbatim.expr and sv.verbatim.expr.se.
static LogicalResult verifyLocalParamOp (LocalParamOp op)
static bool isEmptyBlockExceptForTerminator (Block *block)
static void replaceOpWithRegion (PatternRewriter &rewriter, Operation *op, Region &region)
Replaces the given op with the contents of the given single-block region.
static LogicalResult verifyAlwaysOp (AlwaysOp op)
Ensure that the symbol being instantiated exists and is an InterfaceOp.
static ParseResult parseEventList (OpAsmParser &p, Attribute &eventsAttr, SmallVectorImpl< OpAsmParser::OperandType > &clocksOperands)
static void printEventList (OpAsmPrinter &p, AlwaysOp op, ArrayAttr portsAttr, OperandRange operands)
static SmallVector< CaseZPatternBit > getPatternBitsForValue (const APInt &value)
static ParseResult parseCaseZOp (OpAsmParser &parser, OperationState &result)
static void printCaseZOp (OpAsmPrinter &p, CaseZOp op)
static LogicalResult verifyCaseZOp (CaseZOp op)
static LogicalResult verifyBPAssignOp (BPAssignOp op)
static LogicalResult verifyPAssignOp (PAssignOp op)
static ParseResult parseModportStructs (OpAsmParser &parser, ArrayAttr &portsAttr)
static void printModportStructs (OpAsmPrinter &p, Operation *, ArrayAttr portsAttr)
static LogicalResult verifyInterfaceInstanceOp (InterfaceInstanceOp op)
Ensure that the symbol being instantiated exists and is an InterfaceOp.
static LogicalResult verifyGetModportOp (GetModportOp op)
Ensure that the symbol being instantiated exists and is an InterfaceModportOp.
ParseResult parseIfaceTypeAndSignal (OpAsmParser &p, Type &ifaceTy, FlatSymbolRefAttr &signalName)
void printIfaceTypeAndSignal (OpAsmPrinter &p, Operation *op, Type type, FlatSymbolRefAttr signalName)
LogicalResult verifySignalExists (Value ifaceVal, FlatSymbolRefAttr signalName)
static LogicalResult verifyWireOp (WireOp op)
Ensure that the symbol being instantiated exists and is an InterfaceOp.
static LogicalResult verifyIndexedPartSelectOp (Operation *op)
static LogicalResult verifyAliasOp (AliasOp op)
static hw::InstanceOp findInstanceSymbolInBlock (StringAttr name, Block *body)
Instances must be at the top level of the hw.module (or within a `ifdef)
static LogicalResult verifyBindOp (BindOp op)
Ensure that the symbol being instantiated exists and is an InterfaceOp.
static LogicalResult verifyBindInterfaceOp (BindInterfaceOp op)
Ensure that the symbol being instantiated exists and is an InterfaceOp.
ParseResult parseXMRPath (::mlir::OpAsmParser &parser, ArrayAttr &pathAttr, StringAttr &terminalAttr)
void printXMRPath (OpAsmPrinter &p, XMROp op, ArrayAttr pathAttr, StringAttr terminalAttr)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1384 of file SVOps.cpp.
Function Documentation
findInstanceSymbolInBlock()
static hw::InstanceOp findInstanceSymbolInBlock (StringAttr name, Block * body) static
Instances must be at the top level of the hw.module (or within a `ifdef)
Definition at line 1257 of file SVOps.cpp.
getPatternBitsForValue()
static SmallVector<CaseZPatternBit> getPatternBitsForValue (const APInt & value) static
Definition at line 576 of file SVOps.cpp.
getVerbatimExprAsmResultNames()
static void getVerbatimExprAsmResultNames (Operation * op, function_ref< void(Value, StringRef)> setNameFn) static
Get the asm name for sv.verbatim.expr and sv.verbatim.expr.se.
Definition at line 140 of file SVOps.cpp.
isEmptyBlockExceptForTerminator()
static bool isEmptyBlockExceptForTerminator (Block * block) static
Definition at line 279 of file SVOps.cpp.
lookupSymbolInNested()
static Operation* lookupSymbolInNested (Operation * symbolTableOp, StringRef symbol) static
Returns the operation registered with the given symbol name with the regions of 'symbolTableOp'.
recurse through nested regions which don't contain the symboltable trait. Returns nullptr if no valid symbol was found.
Definition at line 51 of file SVOps.cpp.
References circt::calyx::direction::get().
parseCaseZOp()
static ParseResult parseCaseZOp (OpAsmParser & parser, OperationState & result) static
Definition at line 623 of file SVOps.cpp.
References circt::sv::Any, circt::sv::One, and circt::sv::Zero.
parseEventList()
static ParseResult parseEventList (OpAsmParser & p, Attribute & eventsAttr, SmallVectorImpl< OpAsmParser::OperandType > & clocksOperands) static
Definition at line 419 of file SVOps.cpp.
parseIfaceTypeAndSignal()
ParseResult parseIfaceTypeAndSignal (OpAsmParser & p, Type & ifaceTy, FlatSymbolRefAttr & signalName)
Definition at line 934 of file SVOps.cpp.
References circt::calyx::direction::get().
parseImplicitSSAName()
static ParseResult parseImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 78 of file SVOps.cpp.
References circt::calyx::direction::get(), and isdigit.
parseModportStructs()
static ParseResult parseModportStructs (OpAsmParser & parser, ArrayAttr & portsAttr) static
Definition at line 804 of file SVOps.cpp.
References circt::calyx::direction::get().
parseXMRPath()
ParseResult parseXMRPath (::mlir::OpAsmParser & parser, ArrayAttr & pathAttr, StringAttr & terminalAttr)
Definition at line 1348 of file SVOps.cpp.
References if().
printCaseZOp()
static void printCaseZOp (OpAsmPrinter & p, CaseZOp op) static
Definition at line 705 of file SVOps.cpp.
References circt::sv::getLetter().
printEventList()
static void printEventList (OpAsmPrinter & p, AlwaysOp op, ArrayAttr portsAttr, OperandRange operands) static
Definition at line 449 of file SVOps.cpp.
printIfaceTypeAndSignal()
void printIfaceTypeAndSignal (OpAsmPrinter & p, Operation * op, Type type, FlatSymbolRefAttr signalName)
Definition at line 947 of file SVOps.cpp.
References circt::calyx::direction::get().
printImplicitSSAName()
static void printImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 106 of file SVOps.cpp.
References isdigit.
printModportStructs()
static void printModportStructs (OpAsmPrinter & p, Operation * , ArrayAttr portsAttr) static
Definition at line 827 of file SVOps.cpp.
printXMRPath()
void printXMRPath (OpAsmPrinter & p, XMROp op, ArrayAttr pathAttr, StringAttr terminalAttr)
Definition at line 1373 of file SVOps.cpp.
replaceOpWithRegion()
static void replaceOpWithRegion (PatternRewriter & rewriter, Operation * op, Region & region) static
Replaces the given op with the contents of the given single-block region.
Definition at line 329 of file SVOps.cpp.
verifyAliasOp()
static LogicalResult verifyAliasOp (AliasOp op) static
Definition at line 1185 of file SVOps.cpp.
verifyAlwaysOp()
static LogicalResult verifyAlwaysOp (AlwaysOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceOp.
Definition at line 412 of file SVOps.cpp.
verifyBindInterfaceOp()
static LogicalResult verifyBindInterfaceOp (BindInterfaceOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceOp.
Definition at line 1335 of file SVOps.cpp.
verifyBindOp()
static LogicalResult verifyBindOp (BindOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceOp.
Definition at line 1299 of file SVOps.cpp.
verifyBPAssignOp()
static LogicalResult verifyBPAssignOp (BPAssignOp op) static
Definition at line 757 of file SVOps.cpp.
verifyCaseZOp()
static LogicalResult verifyCaseZOp (CaseZOp op) static
Definition at line 727 of file SVOps.cpp.
verifyGetModportOp()
static LogicalResult verifyGetModportOp (GetModportOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceModportOp.
Definition at line 880 of file SVOps.cpp.
verifyIndexedPartSelectOp()
static LogicalResult verifyIndexedPartSelectOp (Operation * op) static
Definition at line 1142 of file SVOps.cpp.
verifyInterfaceInstanceOp()
static LogicalResult verifyInterfaceInstanceOp (InterfaceInstanceOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceOp.
Definition at line 862 of file SVOps.cpp.
verifyLocalParamOp()
static LogicalResult verifyLocalParamOp (LocalParamOp op) static
Definition at line 196 of file SVOps.cpp.
References circt::hw::checkParameterInContext().
verifyPAssignOp()
static LogicalResult verifyPAssignOp (PAssignOp op) static
Definition at line 765 of file SVOps.cpp.
verifySignalExists()
LogicalResult verifySignalExists (Value ifaceVal, FlatSymbolRefAttr signalName)
Definition at line 956 of file SVOps.cpp.
verifyWireOp()
static LogicalResult verifyWireOp (WireOp op) static
Ensure that the symbol being instantiated exists and is an InterfaceOp.
Definition at line 1059 of file SVOps.cpp.